### ISSUE TITLE
Kubernetes Volume Support

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#10]
This is a tracker issue to work on Kubernetes volume support for peer pods
Ephemeral (directory or memory) might work out-of-box. Need to test it out.
Persistent volume support needs to be worked out.

**Comment by liudalibj** [comment]
I tred the hostPath volume, it works well too.
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  runtimeClassName: kata
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/local/aaa
          name: mydir
        - mountPath: /var/local/aaa/1.txt
          name: myfile
  volumes:
    - name: mydir
      hostPath:
        path: /var/local/aaa
        type: DirectoryOrCreate
    - name: myfile
      hostPath:
        path: /var/local/aaa/1.txt
        type: FileOrCreate
```
<details>
  <summary>Some debug logs</summary>

- inside container

```
root@peer-pod-x86-worker:~# kubectl exec -it nginx bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@nginx:/# mount
tmpfs on / type tmpfs (rw,relatime,mode=755)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
tmpfs on /tmp type tmpfs (rw,relatime,mode=755)
tmpfs on /etc/resolv.conf type tmpfs (rw,relatime,mode=755)
shm on /dev/shm type tmpfs (rw,relatime)
tmpfs on /etc/hosts type tmpfs (rw,relatime,mode=755)
tmpfs on /dev/termination-log type tmpfs (rw,relatime,mode=755)
tmpfs on /etc/hostname type tmpfs (rw,relatime,mode=755)
tmpfs on /var/local/aaa/1.txt type tmpfs (rw,relatime,mode=755)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
root@nginx:/# echo inside container > /var/local/aaa/22.txt

```

- in the podvm 
```
root@peer-pod-x86-worker-default-nginx-4eb19ba1:/run/kata-containers/nginx_latest/rootfs/var/local/aaa# pwd
/run/kata-containers/nginx_latest/rootfs/var/local/aaa
root@peer-pod-x86-worker-default-nginx-4eb19ba1:/run/kata-containers/nginx_latest/rootfs/var/local/aaa# cat 22.txt
inside container
```
- the oci config.json inside podvm, `/run/kata-containers/nginx_latest/config.json`
```json
{
	"ociVersion": "1.0.0",
	"process": {
		"terminal": true,
		"user": {
			"uid": 0,
			"gid": 0
		},
		"args": [
			"/docker-entrypoint.sh",
			"nginx",
			"-g",
			"daemon off;"
		],
		"env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm",
			"NGINX_VERSION=1.21.6",
			"NJS_VERSION=0.7.3",
			"PKG_RELEASE=1~bullseye",
			"HOME=/root"
		],
		"cwd": "/",
		"capabilities": {
			"bounding": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"effective": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"inheritable": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"permitted": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"ambient": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			]
		},
		"rlimits": [
			{
				"type": "RLIMIT_NOFILE",
				"hard": 1024,
				"soft": 1024
			}
		],
		"noNewPrivileges": true
	},
	"root": {
		"path": "rootfs"
	},
	"hostname": "umoci-default",
	"mounts": [
		{
			"destination": "/proc",
			"type": "proc",
			"source": "proc"
		},
		{
			"destination": "/dev",
			"type": "tmpfs",
			"source": "tmpfs",
			"options": [
				"nosuid",
				"strictatime",
				"mode=755",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/pts",
			"type": "devpts",
			"source": "devpts",
			"options": [
				"nosuid",
				"noexec",
				"newinstance",
				"ptmxmode=0666",
				"mode=0620",
				"gid=5"
			]
		},
		{
			"destination": "/dev/shm",
			"type": "tmpfs",
			"source": "shm",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"mode=1777",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/mqueue",
			"type": "mqueue",
			"source": "mqueue",
			"options": [
				"nosuid",
				"noexec",
				"nodev"
			]
		},
		{
			"destination": "/sys",
			"type": "sysfs",
			"source": "sysfs",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"ro"
			]
		},
		{
			"destination": "/sys/fs/cgroup",
			"type": "cgroup",
			"source": "cgroup",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"relatime",
				"ro"
			]
		}
	],
	"annotations": {
		"maintainer": "NGINX Docker Maintainers \u003cdocker-maint@nginx.com\u003e",
		"org.opencontainers.image.architecture": "amd64",
		"org.opencontainers.image.author": "",
		"org.opencontainers.image.created": "2022-05-17T22:36:01.937472358Z",
		"org.opencontainers.image.exposedPorts": "80/tcp",
		"org.opencontainers.image.os": "linux",
		"org.opencontainers.image.stopSignal": "SIGQUIT"
	},
	"linux": {
		"resources": {
			"devices": [
				{
					"allow": false,
					"access": "rwm"
				}
			]
		},
		"namespaces": [
			{
				"type": "pid"
			},
			{
				"type": "network"
			},
			{
				"type": "ipc"
			},
			{
				"type": "uts"
			},
			{
				"type": "mount"
			}
		],
		"maskedPaths": [
			"/proc/kcore",
			"/proc/latency_stats",
			"/proc/timer_list",
			"/proc/timer_stats",
			"/proc/sched_debug",
			"/sys/firmware",
			"/proc/scsi"
		],
		"readonlyPaths": [
			"/proc/asound",
			"/proc/bus",
			"/proc/fs",
			"/proc/irq",
			"/proc/sys",
			"/proc/sysrq-trigger"
		]
	}
}
```
the kata-agent logs:

> May 19 03:13:37 peer-pod-x86-worker-default-nginx-4eb19ba1 kata-agent[715]: {"msg":"receive createcontainer, spec: Spec { version: \"1.0.2-dev\", process: Some(Process { terminal: false, console_size: None, user: User { uid: 0, gid: 0, additional_gids: [], username: \"\" }, args: [], env: [\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"HOSTNAME=nginx\", \"KUBERNETES_SERVICE_PORT=443\", \"KUBERNETES_PORT=tcp://10.96.0.1:443\", \"KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443\", \"NGINX_SERVICE_SERVICE_HOST=10.101.93.178\", \"KUBERNETES_PORT_443_TCP_PORT=443\", \"NGINX_SERVICE_SERVICE_PORT=80\", \"NGINX_SERVICE_SERVICE_PORT_PORT80=80\", \"NGINX_SERVICE_PORT=tcp://10.101.93.178:80\", \"KUBERNETES_SERVICE_HOST=10.96.0.1\", \"KUBERNETES_SERVICE_PORT_HTTPS=443\", \"KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1\", \"NGINX_SERVICE_PORT_80_TCP=tcp://10.101.93.178:80\", \"NGINX_SERVICE_PORT_80_TCP_ADDR=10.101.93.178\", \"KUBERNETES_PORT_443_TCP_PROTO=tcp\", \"NGINX_SERVICE_PORT_80_TCP_PROTO=tcp\", \"NGINX_SERVICE_PORT_80_TCP_PORT=80\"], cwd: \"/\", capabilities: Some(LinuxCapabilities { bounding: [\"CAP_CHOWN\", \"CAP_DAC_OVERRIDE\", \"CAP_FSETID\", \"CAP_FOWNER\", \"CAP_MKNOD\", \"CAP_NET_RAW\", \"CAP_SETGID\", \"CAP_SETUID\", \"CAP_SETFCAP\", \"CAP_SETPCAP\", \"CAP_NET_BIND_SERVICE\", \"CAP_SYS_CHROOT\", \"CAP_KILL\", \"CAP_AUDIT_WRITE\"], effective: [\"CAP_CHOWN\", \"CAP_DAC_OVERRIDE\", \"CAP_FSETID\", \"CAP_FOWNER\", \"CAP_MKNOD\", \"CAP_NET_RAW\", \"CAP_SETGID\", \"CAP_SETUID\", \"CAP_SETFCAP\", \"CAP_SETPCAP\", \"CAP_NET_BIND_SERVICE\", \"CAP_SYS_CHROOT\", \"CAP_KILL\", \"CAP_AUDIT_WRITE\"], inheritable: [\"CAP_CHOWN\", \"CAP_DAC_OVERRIDE\", \"CAP_FSETID\", \"CAP_FOWNER\", \"CAP_MKNOD\", \"CAP_NET_RAW\", \"CAP_SETGID\", \"CAP_SETUID\", \"CAP_SETFCAP\", \"CAP_SETPCAP\", \"CAP_NET_BIND_SERVICE\", \"CAP_SYS_CHROOT\", \"CAP_KILL\", \"CAP_AUDIT_WRITE\"], permitted: [\"CAP_CHOWN\", \"CAP_DAC_OVERRIDE\", \"CAP_FSETID\", \"CAP_FOWNER\", \"CAP_MKNOD\", \"CAP_NET_RAW\", \"CAP_SETGID\", \"CAP_SETUID\", \"CAP_SETFCAP\", \"CAP_SETPCAP\", \"CAP_NET_BIND_SERVICE\", \"CAP_SYS_CHROOT\", \"CAP_KILL\", \"CAP_AUDIT_WRITE\"], ambient: [] }), rlimits: [], no_new_privileges: false, apparmor_profile: \"cri-containerd.apparmor.d\", oom_score_adj: Some(1000), selinux_label: \"\" }), root: Some(Root { path: \"/run/kata-containers/shared/containers/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4/rootfs\", readonly: false }), hostname: \"\", mounts: [Mount { destination: \"/proc\", type: \"proc\", source: \"proc\", options: [\"nosuid\", \"noexec\", \"nodev\"] }, Mount { destination: \"/dev\", type: \"tmpfs\", source: \"tmpfs\", options: [\"nosuid\", \"strictatime\", \"mode=755\", \"size=65536k\"] }, Mount { destination: \"/dev/pts\", type: \"devpts\", source: \"devpts\", options: [\"nosuid\", \"noexec\", \"newinstance\", \"ptmxmode=0666\", \"mode=0620\", \"gid=5\"] }, Mount { destination: \"/dev/mqueue\", type: \"mqueue\", source: \"mqueue\", options: [\"nosuid\", \"noexec\", \"nodev\"] }, Mount { destination: \"/sys\", type: \"sysfs\", source: \"sysfs\", options: [\"nosuid\", \"noexec\", \"nodev\", \"ro\"] }, Mount { destination: \"/sys/fs/cgroup\", type: \"cgroup\", source: \"cgroup\", options: [\"nosuid\", \"noexec\", \"nodev\", \"relatime\", \"ro\"] }, Mount { destination: \"/tmp\", type: \"local\", source: \"/run/kata-containers/shared/containers/4eb19ba13dd4943668a8d7c1f1311582b00fbfcbd1ba20d12b93dbd0739bee8d/rootfs/local/ephemeral\", options: [\"rbind\", \"rprivate\", \"rw\"] }, Mount { destination: \"/etc/resolv.conf\", type: \"bind\", source: \"/run/kata-containers/shared/containers/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4-0abf43be0731258b-resolv.conf\", options: [\"rbind\", \"rprivate\", \"rw\"] }, Mount { destination: \"/dev/shm\", type: \"bind\", source: \"/run/kata-containers/sandbox/shm\", options: [\"rbind\"] }, Mount { destination: \"/etc/hosts\", type: \"bind\", source: \"/run/kata-containers/shared/containers/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4-3a2d6bb16e1731f2-hosts\", options: [\"rbind\", \"rprivate\", \"rw\"] }, Mount { destination: \"/dev/termination-log\", type: \"bind\", source: \"/run/kata-containers/shared/containers/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4-4ed93118ed13568e-termination-log\", options: [\"rbind\", \"rprivate\", \"rw\"] }, Mount { destination: \"/etc/hostname\", type: \"bind\", source: \"/run/kata-containers/shared/containers/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4-de32e1cd57293e11-hostname\", options: [\"rbind\", \"rprivate\", \"rw\"] }, Mount { destination: \"/var/local/aaa/1.txt\", type: \"bind\", source: \"/run/kata-containers/shared/containers/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4-86062dffdfd6b79d-1.txt\", options: [\"rbind\", \"rprivate\", \"rw\"] }], hooks: None, annotations: {\"io.kubernetes.cri.sandbox-id\": \"4eb19ba13dd4943668a8d7c1f1311582b00fbfcbd1ba20d12b93dbd0739bee8d\", \"io.katacontainers.pkg.oci.container_type\": \"pod_container\", \"io.kubernetes.cri.container-name\": \"nginx\", \"io.katacontainers.pkg.oci.bundle_path\": \"/run/containerd/io.containerd.runtime.v2.task/k8s.io/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4\", \"io.kubernetes.cri.container-type\": \"container\", \"io.kubernetes.cri.sandbox-namespace\": \"default\", \"io.kubernetes.cri.sandbox-name\": \"nginx\", \"io.kubernetes.cri.image-name\": \"nginx:latest\"}, linux: Some(Linux { uid_mappings: [], gid_mappings: [], sysctl: {}, resources: Some(LinuxResources { devices: [], memory: Some(LinuxMemory { limit: Some(0), reservation: Some(0), swap: Some(0), kernel: Some(0), kernel_tcp: Some(0), swappiness: Some(0), disable_oom_killer: Some(false) }), cpu: Some(LinuxCpu { shares: Some(2), quota: Some(0), period: Some(100000), realtime_runtime: Some(0), realtime_period: Some(0), cpus: \"\", mems: \"\" }), pids: None, block_io: None, hugepage_limits: [], network: None, rdma: {} }), cgroups_path: \"/cri-containerd/6d6c7b21faf4c6b81b724d69a27b2a99378124ed46a9fae4cfa9bae93fa261a4\", namespaces: [LinuxNamespace { type: \"ipc\", path: \"\" }, LinuxNamespace { type: \"uts\", path: \"\" }, LinuxNamespace { type: \"mount\", path: \"\" }], devices: [], seccomp: None, rootfs_propagation: \"\", masked_paths: [\"/proc/acpi\", \"/proc/kcore\", \"/proc/keys\", \"/proc/latency_stats\", \"/proc/timer_list\", \"/proc/timer_stats\", \"/proc/sched_debug\", \"/proc/scsi\", \"/sys/firmware\"], readonly_paths: [\"/proc/asound\", \"/proc/bus\", \"/proc/fs\", \"/proc/irq\", \"/proc/sys\", \"/proc/sysrq-trigger\"], mount_label: \"\", intel_rdt: None }), solaris: None, windows: None, vm: None }","level":"INFO","ts":"2022-05-19T03:13:37.010635056+00:00","subsystem":"rpc","pid":"715","source":"agent","name":"kata-agent","version":"0.1.0"}

</details>

**Comment by huoqifeng** [comment]
@liudalibj @yoheiueda @genjuro214 and I discussed it ever for persistent volume support, here is an approach what we're working on, @bpradipt we might have a discussion on the details and problems we meet today:
![image](https://user-images.githubusercontent.com/15607193/180198604-89e9d7b4-fc77-4acc-87a3-e852bfc35163.png)

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
@ariel-adam this is still relevant and @liudalibj @huoqifeng demonstrated a solution in the community meeting to support persistent volumes
https://zoom.us/rec/share/MqZzBOeTcKR8M5lM4sU-KkibWCVYr1Dap5uIDuG8BgJQH66KysDGT2MC-JI6XuWU.OiCQQu1EAHSpgttK 

@huoqifeng @liudalibj plan to raise a PR soon.

**Comment by liudalibj** [comment]
> @huoqifeng @liudalibj plan to raise a PR soon.

I am preparing the PR, here is the branch that I used https://github.com/liudalibj/cloud-api-adaptor/tree/csi-volumes/volumes/csi-wrapper

When the document is finished and verified I will open the PR from the branch.

**Comment by bpradipt** [comment]
Initial support for Kubernetes persistent volume using CSI-wrapper solution is available. This is currently tested only for ibmcloud. Using the same for other providers is WIP and tracked separately. Closing this issue.
