### ISSUE TITLE
Fix imagePullPolicy(always) limitation in PeerPod

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#100]
Currently, `imagePullPolicy: Always` need be applied to container so that the image in peerpod can be pulled, it's OK for a workload but not convenient for a sidecar as the sidecar descriptor is usually set by admission controller which is out of the deployer's control. So, we'd better to fix the problem so that container can be run in peerpod when imagePullPolicy equals IfNotPresent

**Comment by yoheiueda** [comment]
I think we need to modify the custom containerd (or Kubernetes) to fix this issue.

Kubernetes checks whether an image already exits or not using the`ImageStatus` CRI call by embeding pod annotations  in `ImageSpec`. So, when  containerd serves `ImageStatusRequest`, it can check pod annotations in `ImageSpec`, and returns NotFound if the request is for peer pod.

https://github.com/kubernetes/kubernetes/blob/f19a26a22ebe26de32319d57231da9812862aaf6/pkg/kubelet/images/image_manager.go#L104-L133
```
	var podAnnotations []kubecontainer.Annotation
	for k, v := range pod.GetAnnotations() {
		podAnnotations = append(podAnnotations, kubecontainer.Annotation{
			Name:  k,
			Value: v,
		})
	}


	spec := kubecontainer.ImageSpec{
		Image:       image,
		Annotations: podAnnotations,
	}
	imageRef, err := m.imageService.GetImageRef(spec)
	if err != nil {
		msg := fmt.Sprintf("Failed to inspect image %q: %v", container.Image, err)
		m.logIt(ref, v1.EventTypeWarning, events.FailedToInspectImage, logPrefix, msg, klog.Warning)
		return "", msg, ErrImageInspect
	}


	present := imageRef != ""
	if !shouldPullImage(container, present) {
		if present {
			msg := fmt.Sprintf("Container image %q already present on machine", container.Image)
			m.logIt(ref, v1.EventTypeNormal, events.PulledImage, logPrefix, msg, klog.Info)
			return imageRef, "", nil
		}
		msg := fmt.Sprintf("Container image %q is not present with pull policy of Never", container.Image)
		m.logIt(ref, v1.EventTypeWarning, events.ErrImageNeverPullPolicy, logPrefix, msg, klog.Warning)
		return "", msg, ErrImageNeverPull
	}
```

https://github.com/kubernetes/cri-api/blob/c75ef5b473bbe2d0a4fc92f82235efd665ea8e9f/pkg/apis/runtime/v1/api.proto#L666-L673
```
message ImageSpec {
    // Container's Image field (e.g. imageID or imageDigest).
    string image = 1;
    // Unstructured key-value map holding arbitrary metadata.
    // ImageSpec Annotations can be used to help the runtime target specific
    // images in multi-arch images.
    map<string, string> annotations = 2;
}
```

Another possible solutions is a work around in cloud-api-adaptor (or kata-shim).

When cloud-api-adaptor (or kata-shim) serves a CreateContainer request, it always send a PullImage request beforehand to ensure image is available. The limitation of this approach is that image registry credentials are not available when pulling a image.

**Comment by yoheiueda** [comment]
@huoqifeng 

This PR get merged, and `imagePullPolicy: IfNotPresent` should work now. Could you confirm it?
- #110

**Comment by huoqifeng** [comment]
Thank you @yoheiueda , I'll check it later...

**Comment by huoqifeng** [comment]
This issue is fixed by commit https://github.com/confidential-containers/cloud-api-adaptor/commit/631daaeab09d6b956babedde335b2197cca7ae26
