### ISSUE TITLE
e2e-test: Add a new e2e test case to verify the SE enabled podvm image be used.

### ISSUE THREAD

**Issue by liudalibj** [confidential-containers/cloud-api-adaptor#1014]
We built out the se-enabled podvm image and we have the s390x-secure-execution pipeline to using the built out se-enabled podvm image. eg https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/5076259472/jobs/9118266186

We need add a common test case to verify the workload container are protect by the secure execution.
- just return true for the provider not support SE yet
- do the real SE feature check for ibmcloud

How to verify one VPC VSI is SE enabled https://github.com/confidential-containers/cloud-api-adaptor/pull/880#issuecomment-1543289370

**Comment by wyuany** [comment]
@liudalibj I submitted a PR to test SE pod for ibmcloud https://github.com/confidential-containers/cloud-api-adaptor/pull/1024 
Would you please help review the PR? Thanks!
