### ISSUE TITLE
IBM Cloud: Remove old terraform scripts

### ISSUE THREAD

**Issue by Jordan9500** [confidential-containers/cloud-api-adaptor#1039]
Since moving to the operator, the old method of configuring the Cloud api adaptor was moved to here: [cloud-api-adaptor/ibmcloud/terraform](https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud/terraform).
With the new method fully tested and working, we should look to remove these older scripts to avoid confusion. This will also remove the need to maintain deprecated code.

**Comment by stevenhorsman** [comment]
@Amulyam24 - I don't think you are using this legacy scripts, but I think you might have updated them in the past, so just wanted to double check you don't need any of the old scripts?

**Comment by Amulyam24** [comment]
Hi @stevenhorsman, I'm not using them anymore. Would be good to remove them, Thanks!
