### ISSUE TITLE
Remove maintainer access for Bandan

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#1049]
@whitebrandy is no longer working on this project and hence maintainer access needs to be revoked.

**Comment by bpradipt** [comment]
cc @jensfr

**Comment by fitzthum** [comment]
Do you have privileges to do this?

**Comment by bpradipt** [comment]
@fitzthum yeah

**Comment by bpradipt** [comment]
I could do it. We'll need to create at least a light weight process for maintainer onboarding and de-boarding across the org. 

Ref: https://github.com/confidential-containers/community/issues/50
