### ISSUE TITLE
webhook: No longer creating the `kata.peerpods.io/vm` allocations

### ISSUE THREAD

**Issue by Jordan9500** [confidential-containers/cloud-api-adaptor#1070]
Running a self-managed cluster following the steps here: https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud I noticed that when the webhook is applied it no longer creates the `kata.peerpods.io/vm` against the node. 

**Expected:**
`kubectl get node <node-name> -o=jsonpath='{.status.allocatable}' | jq`
```
{
  "cpu": "2",
  "ephemeral-storage": "93492209510",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "kata.peerpods.io/vm": "20",
  "memory": "8050760Ki",
  "pods": "110"
}
```

**Actual:**
`kubectl get node <node-name> -o=jsonpath='{.status.allocatable}' | jq`
```
{
  "cpu": "2",
  "ephemeral-storage": "94578447818",
  "hugepages-1Mi": "0",
  "memory": "8124140Ki",
  "pods": "110"
}
```

This means when the CAA operator is running it can not create the pod due to this error: 
```
Warning  FailedScheduling  27s   default-scheduler  0/1 nodes are available: 1 Insufficient kata.peerpods.io/vm. preemption: not eligible due to preemptionPolicy=Never..
```

The extended resource that gets created also seems to be failing after running: 
```
pushd webhook/hack/extended-resources/
./setup.sh
popd
```
`kubectl get pods -n kube-system`
```
coredns-5d78c9869d-9bmcm                            1/1     Running                0          113m
coredns-5d78c9869d-ft9pv                            1/1     Running                0          113m
etcd-jj-s390x-z-cluster-node-0                      1/1     Running                0          113m
ext-res-updater-drf5b                               0/1     CreateContainerError   0          5m44s
kube-apiserver-jj-s390x-z-cluster-node-0            1/1     Running                0          113m
kube-controller-manager-jj-s390x-z-cluster-node-0   1/1     Running                0          113m
kube-proxy-9z7bc                                    1/1     Running                0          113m
kube-proxy-l6lgx                                    1/1     Running                0          112m
kube-scheduler-jj-s390x-z-cluster-node-0            1/1     Running                0          113m
```
Note `ext-res-updater-drf5b` is failing on: 
`kubectl describe pod ext-res-updater-drf5b -n kube-system`
```
  Warning  Failed       4m35s                 kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount619294443: no users found
  Normal   Pulling      85s (x20 over 5m29s)  kubelet            Pulling image "curlimages/curl"
```

@bpradipt

**Comment by stevenhorsman** [comment]
I wonder if this changes is because the version of the webhook image we install is out of date and we've updated the code recently. I raised https://github.com/confidential-containers/cloud-api-adaptor/issues/1067 to add an automatic build of the webhook, but in the short-term we could also do a manual rebuild and push to see if that fixes the issue?

**Comment by Jordan9500** [comment]
I tried manually building the webhook using: 
```
make docker-load docker-push IMG=<my registry>
```
And then pulled from that but still hit the same issues

**Comment by bpradipt** [comment]
Looks like the webhook is working as you get this message which indicates there are no extended resources `kata.peerpods.io/vm`
 
```
Warning  FailedScheduling  27s   default-scheduler  0/1 nodes are available: 1 Insufficient kata.peerpods.io/vm. preemption: not eligible due to preemptionPolicy=Never..
```

And the extended resources is not getting created by the script due the following error "mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount619294443: no users found"

Need to figure out what's causing the above error.

**Comment by stevenhorsman** [comment]
> Need to figure out what's causing the above error.

My guess is that it's something to do with the USER
https://github.com/confidential-containers/cloud-api-adaptor/blame/034329e085e7105e8c77d4c08c29467a40126522/webhook/Dockerfile#LL27C1-L27C17
not existing? though I'm not sure what has changed there.

**Comment by Jordan9500** [comment]
Having a look in the linked repo: 

https://github.com/confidential-containers/cloud-api-adaptor/blob/034329e085e7105e8c77d4c08c29467a40126522/webhook/Dockerfile#LL23C4-L23C4

I can see a recent ish commit: https://github.com/GoogleContainerTools/distroless/commit/fb94acc429d87523020a0a801446f178708e2a10 
That looks at changing the rules, this relates to : gcr.io/distroless/static:nonroot base image that is used. From looking at some of the changes there is mentions of updates to the user. 

There is also these release notes: https://cloud.google.com/container-registry/docs/release-notes#May_15_2023
That mention that gcr.io is going to be deprecated. But from another story inside the Distroless repo, https://github.com/GoogleContainerTools/distroless/issues/1320 they mention it should be safe for another year.

**Comment by Jordan9500** [comment]
Another look with the above in mind, I tested changing the extended resources. 

And found the issue is with the curl image that is pulled in as per: https://github.com/curl/curl-container/issues/3 

A workaround is to switch to using `- image: curlimages/curl:8.1.1` which does not include the bug

Still investigating what has caused the issues

**Comment by Jordan9500** [comment]
One question is, do we want to add the workaround or wait for a fix to be added

**Comment by stevenhorsman** [comment]
> One question is, do we want to add the workaround or wait for a fix to be added/add the fix

I think we make a PR to pin that image for now, but leave this issue open to unpin it once upstream has been fixed?

**Comment by Jordan9500** [comment]
Reopened as per the above discussion

**Comment by jtumber-ibm** [comment]
> > One question is, do we want to add the workaround or wait for a fix to be added/add the fix
> 
> I think we make a PR to pin that image for now, but leave this issue open to unpin it once upstream has been fixed?
> 
> Nice job on the investigation!

@stevenhorsman I disagree here that we should unpin when upstream is fixed. I think it is better to keep it a pinned value from now on.

**Comment by stevenhorsman** [comment]
> > > One question is, do we want to add the workaround or wait for a fix to be added/add the fix
> > 
> > 
> > I think we make a PR to pin that image for now, but leave this issue open to unpin it once upstream has been fixed?
> > Nice job on the investigation!
> 
> @stevenhorsman I disagree here that we should unpin when upstream is fixed. I think it is better to keep it a pinned value from now on.

Yeah - I was discussing with Jordan earlier that I think we want to track this in the version.yaml file and expose the fact that we are either explicitly using a pinned version, or implicitly using latest. I'm always stuck between the pull to pick up latest to make sure we pick up any bug fixes and security vulnerabilities and be on a pinned version for stability. I guess in an ideal world we'd pin it, but be able to stay on top of the changes and regularly bump it, but I don't think that is realistic 😿

**Comment by bpradipt** [comment]
Closing this issue as it's no longer seen
