### ISSUE TITLE
Webhook: Move all extended resources into one file

### ISSUE THREAD

**Issue by Jordan9500** [confidential-containers/cloud-api-adaptor#1095]
## Description
When applying the webhook extended resources, make it so we only need to apply the one file rather than run a script. 

This can be done by combining:  
- ext-res-rbac.yaml
- ext-res-cm.yaml
- ext-res-ds.yaml

Into one file called `extended-resources.yaml` or `ext-res.yaml`. This will then ensure that the applied yaml will be in the correct order and allow the user to apply the yaml without the need to run a script. 

By doing something like: 
```
kubectl apply -f github.com/confidential-containers/cloud-api-adaptor/webhook/hack/extended-resources
```

**Comment by bpradipt** [comment]
Ref: https://github.com/confidential-containers/cloud-api-adaptor/issues/1976
