### ISSUE TITLE
Secure Kata runtime (shim) and kata-agent communication

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#11]
This is a tracker issue to investigate and arrive at a solution for securing the communication between shim and kata-agent. Currently the communication is over plain HTTP (vsock over http).

**Comment by huoqifeng** [comment]
Not sure is it reasonable but looks cert-manager is a kind control plane solution, similar as the CSI driver described here https://cert-manager.io/docs/usage/csi/#enabling-mtls-of-pods-using-the-cert-manager-csi-driver and code repo here https://github.com/cert-manager/cert-manager, cloud-api-adaptor can apply private key and certificates for every Pod, just like CSI for every volume. let's revisit the details when implement this feature.

**Comment by yoheiueda** [comment]
To enable TLS, we need to update these lines.

https://github.com/confidential-containers/cloud-api-adaptor/blob/2e7978759c8066af7585e041a88be810f42aaa76/pkg/adaptor/proxy/service.go#L69-L70

https://github.com/confidential-containers/cloud-api-adaptor/blob/2e7978759c8066af7585e041a88be810f42aaa76/pkg/forwarder/daemon.go#L79

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
@ariel-adam yes.

**Comment by bpradipt** [comment]
I have started prototyping this - https://github.com/bpradipt/cloud-api-adaptor/tree/tls
