### ISSUE TITLE
Add a release checklist

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/cloud-api-adaptor#1108]
Now that peer pods is fully (or almost?) integrated with CoCo's operator,  the two projects are hooked with respect to release. @stevenhorsman has improved the [CoCo's release checklist](https://github.com/confidential-containers/community/blob/main/.github/ISSUE_TEMPLATE/release-check-list.md) (see https://github.com/confidential-containers/community/pull/97) to include steps and information about the changes needed to release peer pods alongside.  But perhaps we should have our own checklist; which beyond leaving the process better documented, it will allow others to help on the release (our releases falling on @stevenhorsman and @bpradipt 's shoulders, let's share the burden ;)

**Comment by stevenhorsman** [comment]
Yeah - there is an outstanding issue on me to document our release process in here and then work on improving it, so I'll take this issue. Thanks for chasing my Wainer and welcome back!
