### ISSUE TITLE
Create version tags of images on release, so users can install stable versions

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1109]
At the moment, on release we build the podvm container images and tag them as `latest`, but don't create a version tag e.g. `v0.6.0` of these images, so users can't go back to previous release if they want to.

We also don't produce any tags for the webhook and cloud-api-adaptor images, so if changes are made post release for new function that introduces incompatibilities, then users won't be able to easily find the release version.

To fix these I think we should create tags for each release and we can update the `kustomization` overlays to point to the version based release. This would mean people could use the release tag to install the stable version of peer pods.

**Comment by wainersm** [comment]
@stevenhorsman on the 0.7.0 I pinned the cloud-api-adaptor image (https://github.com/confidential-containers/cloud-api-adaptor/pull/1239) but I used the commit sha-1 of the built release candidate image. Here we have chicken-and-eggs problem (again) to automate this: if the `cloud-adaptor:<RELEASE>` image is built at the time we cut the release, how can we have the kustomization overlays updated before tagging? :)

I think we will have a similar problem for the webhook image.

Are the podvm images referenced somewhere in the code? If not, yeah, I need no problem on tagging them at the time we cut the release.
