### ISSUE TITLE
Add flexible instance types support for ibmcloud

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#1115]

**Comment by bpradipt** [comment]
@yoheiueda @Amulyam24 @huoqifeng @stevenhorsman does anyone of you or from your team want to handle this issue ?
Unfortunately I don't have access to a paid IBM cloud account and won't be able to test the code

**Comment by huoqifeng** [comment]
@bpradipt , let me talk it with @stevenhorsman and assign it to right person.
