### ISSUE TITLE
Update dynamic container image registry authentication to use new method

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1119]
We currently have a system, as documented in https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/registries-authentication.md, and that lets a user set auth.json secrets in their kustomize overlay and then base64 encodes that files content and add it to `/etc/aa-offline_fs_kbc-resources.json` so that it can get picked up by the offline_fs_kbc module of the attestation-agent. This means that in order to use this functionality the 'main' attestation-agent built into the podvm has to be [configured to use offline_fs_kbc](https://github.com/confidential-containers/cloud-api-adaptor/blob/48742e9edbe9042f78bb8cdd7236984ae8320fe3/podvm/Dockerfile.podvm_binaries#L13)

Recently in https://github.com/kata-containers/kata-containers/pull/6707, support has been added for overriding the default path used for credentials (and signature and policy info) so that rather than using the kbs, if can be read directly from the file, by setting  the `image_registry_auth_file` parameter. So in theory we could update the logic that currently encoded and adds the auth.json into `/etc/aa-offline_fs_kbc-resources.json` to instead write it somewhere like `/etc/auth.json` and then add `image_registry_auth_file=file:///etc/auth.json` into the agent-config.toml and we'd not longer have the offline_fs_kbc requirement on the registry credentials feature (note we'd still need an attestation-agent running I'd guess).

We'd then be free to update the podvm built attestation-agent to use a remote module (e.g. cc_kbc) if that suited.

**Note:** this hasn't currently been tested in kata-containers until https://github.com/kata-containers/tests/issues/5688 is implemented and I might have got some of the details wrong.

**Comment by stevenhorsman** [comment]
cc @mkulke, @snir911  - I think this might be interesting to you?

**Comment by mkulke** [comment]
sounds like a good option 👍

**Comment by bpradipt** [comment]
nice.. This will avoid us having two AA builds for some use cases

**Comment by bpradipt** [comment]
Just checking if anyone has started working on this one ?

**Comment by bpradipt** [comment]
As mentioned in the community call today, I have started working on this issue.
