### ISSUE TITLE
test/e2e/libvirt: allow to overwrite the Libvirt connection

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/cloud-api-adaptor#1164]
Currently the URI used to connect to Libvirt is hard-coded to `qemu:///system`.  Let's allow to overwrite the URI (e.g. you might want to connect to a remote instance) via properties file.

This feature is very similar to https://github.com/confidential-containers/cloud-api-adaptor/issues/1163

**Comment by wainersm** [comment]
The exact line where the connection is set: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/test/provisioner/provision_libvirt.go#L68

**Comment by bookinabox** [comment]
Thought I had made this PR a while ago, but I guess I did not.
