### ISSUE TITLE
Switch to pure go implementation for libvirt

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#119]
The current libvirt provider uses `cgo` bindings which makes it difficult to use with different distros.
Switch the libvirt provider to use the go implementation from https://github.com/digitalocean/go-libvirt

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
@ariel-adam this is a future item. But let this be open for now

**Comment by bpradipt** [comment]
This is tricky as the official libvirt go bindings require cgo. For now we'll continue using the official libvirt go bindings.
