### ISSUE TITLE
attestation-agent and RPC

### ISSUE THREAD

**Issue by jepio** [confidential-containers/cloud-api-adaptor#1205]
We have the following constraints:
- `/usr/local/bin/attestation-agent` needs to be compiled with ttrpc because that is required by `kata-agent`
- ttrpc only supports unix domain sockets
- the `attestation-agent.service` passes arguments to `/usr/local/bin/attestation-agent` that imply gRPC usage and an localhost network endpoint

These constraints mean that the current setup is broken. Fix it by allowing a second, gRPC based attestation-agent to be built into the podvm image.

**Comment by jepio** [comment]
Mostly the same as: #1015

**Comment by mkulke** [comment]
caa has since switched to ttrpc comm in the guest-components
