### ISSUE TITLE
Unable to checkout on Windows

### ISSUE THREAD

**Issue by RedCarsten** [confidential-containers/cloud-api-adaptor#1231]
When trying to checkout the code on a windows machine via

```bash
git clone git@github.com:confidential-containers/cloud-api-adaptor.git
```

it fails with

```
error: invalid path 'podvm/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers.mount'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by jtumber-ibm** [comment]
Hi @RedCarsten is it possible for you to use WSL for now? I think there will be quite a few parts of this repo that won't work directly on windows

**Comment by bookinabox** [comment]
The backslash in the filename is throwing it off:
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by CarstenLeue** [comment]
> Hi @RedCarsten is it possible for you to use WSL for now? I think there will be quite a few parts of this repo that won't work directly on windows

Yes, as a workaround I can use WSL
