### ISSUE TITLE
cloud-api-adaptor image release build taking a long time

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1234]
During the release process Wainer pointed out that the cloud-api-adaptor [image workflow](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/image.yaml) have grown to take >50mins now. Looking back it seems to have been triggered but the golang-fedora builder change: https://github.com/confidential-containers/cloud-api-adaptor/pull/1116 so we might want to revisit that and see if there are any steps we can do to improve release performance - particularly for multi-arch builds I think.

**Comment by wainersm** [comment]
The last "fast" build took ~12min (https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/5424819216/job/14691935075) and the build times are:

 * ppc64le 
    ```
    #39 [linux/amd64->ppc64le builder 10/10] RUN make ARCH=ppc64le COMMIT=c10fa643486f98abd637e58003512eea08989df0 VERSION=v0.6.0-dev RELEASE_BUILD=true cloud-api-adaptor
   #39 DONE 553.9s
   ```

 * s390x
    ```
   #38 [linux/amd64->s390x builder 10/10] RUN make ARCH=s390x COMMIT=c10fa643486f98abd637e58003512eea08989df0 VERSION=v0.6.0-dev RELEASE_BUILD=true cloud-api-adaptor
   #38 DONE 573.6s
   ```

 * amd64 
    ```
    #40 [linux/amd64 builder 10/10] RUN make ARCH=amd64 COMMIT=c10fa643486f98abd637e58003512eea08989df0 VERSION=v0.6.0-dev RELEASE_BUILD=true cloud-api-adaptor
    #40 DONE 582.5s
   ```

[One of the last builds](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/5646326401/job/15293980614) took > 1h. The build times:


 * ppc64le 
    ```
    #35 [linux/ppc64le builder 8/8] RUN make ARCH=ppc64le COMMIT=6d7d2a3fe8243809b3c3a710792c8498292e2fc3 VERSION=v0.7.0-alpha.2-dev RELEASE_BUILD=true cloud-api-adaptor
   #35 DONE 2949.9s
    ```

 * s390x
    ```
    #40 [linux/s390x builder 8/8] RUN make ARCH=s390x COMMIT=6d7d2a3fe8243809b3c3a710792c8498292e2fc3 VERSION=v0.7.0-alpha.2-dev RELEASE_BUILD=true cloud-api-adaptor
   #40 DONE 3578.2s
    ```

 * amd64 
    ```
    #30 [linux/amd64 builder 8/8] RUN make ARCH=amd64 COMMIT=6d7d2a3fe8243809b3c3a710792c8498292e2fc3 VERSION=v0.7.0-alpha.2-dev RELEASE_BUILD=true cloud-api-adaptor
    #30 DONE 512.5s
    ```

The ppc64le and s390x builds increased a lot!

@katexochen do you have any idea what introduced that regression with the new fedora go builder?

**Comment by katexochen** [comment]
I'll take a look. No idea on the first glance, sorry. :disappointed:
