### ISSUE TITLE
azure: we should not echo the secret in the make image output

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/cloud-api-adaptor#1245]
We should not echo the secret verbatim in the output of a Makefile, currently we'll see the following:

```bash
cd azure/image
PODVM_IMAGE=ubuntu make image
...
# export the required packer variables as PKR_VAR_<var_name>
...
# export PKR_VAR_client_secret="123abc"
```

This risks leaking secrets when pasting the log for debugging purposes

**Comment by bpradipt** [comment]
@mkulke is this related - https://github.com/confidential-containers/cloud-api-adaptor/issues/1181 ?

**Comment by mkulke** [comment]
> @mkulke is this related - #1181 ?

related, but not the same. This is simply about echoing in makefiles, before packet is invoked.
