### ISSUE TITLE
release process: build podvm images at the release candidate phase

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/cloud-api-adaptor#1253]
**Context**

On the [release candidate testing](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#release-candidate-testing) phase of our release process, we update the podvm dockerfile files to use the Kata Containers release candidate (usually the same commit SHA-1 where kata's runtime-payload-ci was built for testing).

Ideally at this phase we should test with the latest and greatest cloud-apid-adaptor and podvm images, and report to Kata Containers/CoCo community any integration issues. However, currently we have automation to build the cloud-api-adaptor image on every PR merged but *not* to rebuild the podvm images, and the main reason being that the podvm image builds are very time and resources demanding.

Important to say the the podvm images are rebuilt when we open a release or pre-release of the cloud-api-adaptor project, when the podvm [builder](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm_builder.yaml), [binaries](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm_binaries.yaml), and [image](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm.yaml) workflows successively run.

**Problem**

As a result, at the release candidate testing phase, we don´t have a suitable podvm image for testing. Unless that the release team build it manually somehow.

Real story: I drove my first release (0.7.0) and I didn't rebuild the podvm images locally. Next day @liudalibj noticed they were not getting built and [provided a fix](https://github.com/confidential-containers/cloud-api-adaptor/pull/1229). I am glad the error was found early in the process, otherwise I would had noticed only later when the cloud-api-adaptor pre-release was created.

**Solutions**

I can think on the following approaches:

* Adding the `workflow_dispatch` event to the [podvm builder workflow](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm_builder.yaml) so that committers can rebuild the image manually. Document this as an required step on the release candidate testing phase
* Adding the `push` event to  [podvm builder workflow](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm_builder.yaml) and filtering by files changed (i.e. triggering only when certain files under `podvm/**` changed). This will re-generate the podvm images for every PR merged, though.
* Like above, but adding the `pull_request` even so triggering on pull requests

**Comment by jtumber-ibm** [comment]
> - Adding the workflow_dispatch event to the [podvm builder workflow](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm_builder.yaml) so that committers can rebuild the image manually. Document this as an required step on the release candidate testing phase

Sounds like the best option to me, the podvm creation is very compute expensive so we should avoid doing it unnecessarily

**Comment by stevenhorsman** [comment]
The podvm is now build during the pre-release creation: see https://quay.io/repository/confidential-containers/podvm-generic-ubuntu-amd64?tab=tags for an example, so I think we can close this.
