### ISSUE TITLE
Azure: Encrypt the podvm image in the shared gallery

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1271]
Right now we don't specify anything regarding the podvm encryption, I think it can be enabled for Azure. Here are some of the resources:

- https://learn.microsoft.com/en-us/azure/virtual-machines/image-version-encryption#cli
- https://developer.hashicorp.com/packer/plugins/builders/azure/arm#disk_encryption_set_id

**Comment by katexochen** [comment]
What would be the benefit of encrypting the podvm image? Are we storing any secrets in it?

**Comment by surajssd** [comment]
@katexochen I was wondering since we don't do measurements of the components like kata-agent, AA, etc. this could be one of the ways to ensure security to the tenant from CSP?

**Comment by katexochen** [comment]
How would the key release for the image work when booting? With MAA + Azure KMS?

And why aren't we measuring these components? If I remember correctly they are part of the VM image so they should be measured by the bootloader and into a vTPM PCR on Azure.

**Comment by surajssd** [comment]
> How would the key release for the image work when booting? With MAA + Azure KMS?

I am not sure yet, will have to look into it.

> And why aren't we measuring these components? If I remember correctly they are part of the VM image so they should be measured by the bootloader and into a vTPM PCR on Azure.

Right now we don't have a mechanism to do it: `ERR_NOT_IMPLEMENTED` 😬

**Comment by katexochen** [comment]
> Right now we don't have a mechanism to do it: ERR_NOT_IMPLEMENTED :grimacing:

Your right, somehow I assumed the Ubuntu CVM image would do some magic, but it doesn't.

**Comment by mkulke** [comment]
closing since packer-based images are being retired and mkosi images use measured-boot
