### ISSUE TITLE
Allow modifying the VM image used for the podvm instance

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#1282]
Currently the VM image used for the pod vm instance is configured during the start of CAA. 
However, there is a need to use a different VM image for the pod vm instance.  

One option is to use pod annotation like what we use for specifying the instance type.

**Comment by clenimar** [comment]
Hi @bpradipt, any new info on this particular issue? We are interested in this use case and wanted to understand a little more about the work involved in making this happen. If we're going down the annotation path, would enabling the appropriate hypervisor annotation in the runtime and then leveraging that on the provider side be enough?

Do you see any extra effort required to upstream it (e.g. any considerations with regard to attestation)?

**Comment by ajaypvictor** [comment]
Raised an issue in kata-containers for enabling the new annotation fields: https://github.com/kata-containers/kata-containers/issues/10240
