### ISSUE TITLE
ibmcloud | doc: Add documentation to clean up the demo resources

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#13]
In https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/ibmcloud/README.md we have some documentation of how to create a peer-pod enabled cluster and demo it, but there isn't currently any instructions of how to clean up the artefacts, that do cost money to leave running.

**Comment by liudalibj** [comment]
IBM cloud clean demo resources instructions are added, I am fine to close this issue, if still need this, please feel free to reopen it.

**Comment by liudalibj** [comment]
@stevenhorsman do you know, how can we config github to close issue when the related PR is merged when the pr has `fix #xxx`?

**Comment by stevenhorsman** [comment]
> @stevenhorsman do you know, how can we config github to close issue when the related PR is merged when the pr has `fix #xxx`?

I was just wondering the same. I *think* from experience with kata-containers and `CCv0` that if the PR is merged into a 'non-main' branch (i.e. staging in our case) then the linking and closing doesn't necessarily work. You you can see from the history I had to manually link the PR from this issue, which I forgot to do before it was closed.

**Comment by stevenhorsman** [comment]
Having a quick search of the github doc seems to back up my experience:
From https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword:
> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message. The pull request must be on the default branch.

**Comment by liudalibj** [comment]
it seems that we are using `main` branch as the default branch in this repo, should we change it to using `staging` as the default one before the codes are ready to main?

**Comment by bpradipt** [comment]
> > it seems that we are using `main` branch as the default branch in this repo, should we change it to using `staging` as the default one before the codes are ready to main?
> 
> Another great question that I was also led to. I'm not sure if there are any negative side effects of it, but I'll sit on it for a little while and chat to some other open-source developers to see if we can think of any reasons against it.

Ah I see this now when looking at the planning tasks. But I had already made the "staging" branch default so that the docs etc are readily visible to anyone.

**Comment by stevenhorsman** [comment]
> > > it seems that we are using `main` branch as the default branch in this repo, should we change it to using `staging` as the default one before the codes are ready to main?
> > 
> > 
> > Another great question that I was also led to. I'm not sure if there are any negative side effects of it, but I'll sit on it for a little while and chat to some other open-source developers to see if we can think of any reasons against it.
> 
> Ah I see this now when looking at the planning tasks. But I had already made the "staging" branch default so that the docs etc are readily visible to anyone.

Thanks Pradipta - if it works well for you, then that's good enough for me :)
