### ISSUE TITLE
Install: pod cc-operator-daemon-install cannot be running

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#1308]
Try `make deploy` to install CAA via operator.

Pod **cc-operator-daemon-install** crashed. 

Check the logs:
```
/opt/kata-artifacts/scripts/kata-deploy.sh: line 17: SHIMS: unbound variable
```

It looks like related to recent changes to [kata-deploy.sh](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/scripts/kata-deploy.sh):
https://github.com/kata-containers/kata-containers/commit/7164ced4dc2fedf5cee381bad36e31959563cdcb#diff-08a680425cfe93e69c4108dc8fd91a9aeaefbf016bd9941b03c66834bf87a341L16

Also related to operator issues: 
https://github.com/confidential-containers/operator/issues/229
https://github.com/confidential-containers/operator/issues/230

**Comment by genjuro214** [comment]
Tried a quick fix to add required env variables:
https://github.com/genjuro214/operator/blob/main/config/samples/ccruntime/base/ccruntime.yaml

`kubectl apply -k "github.com/genjuro214/operator/config/samples/ccruntime/peer-pods"`

**Comment by fidencio** [comment]
> Tried a quick fix to add required env variables: https://github.com/genjuro214/operator/blob/main/config/samples/ccruntime/base/ccruntime.yaml
> 
> `kubectl apply -k "github.com/genjuro214/operator/config/samples/ccruntime/peer-pods"`

I have a PR on the operator side that needs to be merged and it should solve this issue: https://github.com/confidential-containers/operator/pull/240

**Comment by genjuro214** [comment]
The operator issue has been fixed by the PR above.
