### ISSUE TITLE
Failed to create VM because pod name is missing in annotations

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#1313]
I'm trying peer pod feature, and check e2e test results for ibmcloud. Daily jobs still failed, and no VM for Peer Pod is created.

Check the cloud-api-adaptor logs, and there are messages:
```
2023/08/08 08:46:15 [adaptor/cloud] pod name io.kubernetes.cri.sandbox-name is missing in annotations
```

Try to print annotations in CreateVMRequest:
```
2023/08/08 08:46:11 [adaptor/cloud] [debug] annotation: map[io.katacontainers.config.hypervisor.default_memory:0 io.katacontainers.config.hypervisor.default_vcpus:0 io.katacontainers.config.hypervisor.machine_type: io.kubernetes.cri.sandbox-name: io.kubernetes.cri.sandbox-namespace:]
```
The values are empty.

The values should be set in kata. However, checking the kata code and I found the related code are deleted in this commit:
https://github.com/kata-containers/kata-containers/commit/7164ced4dc2fedf5cee381bad36e31959563cdcb#diff-a6e45adf0a559c18c61d84b1ea3225f62c1cf6166c7bf1f5b24e5c034921db09L614
```
	if len(sandboxConfig.Containers) > 0 {
		// These values are required by remote hypervisor
		for _, a := range []string{cri.SandboxName, crio.SandboxName} {
			if value, ok := sandboxConfig.Containers[0].Annotations[a]; ok {
				sandboxConfig.HypervisorConfig.SandboxName = value
			}
		}
```

@fidencio , can you help to check if the changes are expected to remove the code to set pod name and namespace in kata?

**Comment by stevenhorsman** [comment]
I've created https://github.com/kata-containers/kata-containers/pull/7589 to add this change back in

**Comment by stevenhorsman** [comment]
The kata PR has merged, so hopefully this issue has been resolved now

**Comment by stevenhorsman** [comment]
Sorry, I spoke too soon, I'm still hitting this error:
```
  Warning  FailedCreatePodSandBox  3m39s (x411 over 23m)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: remote hypervisor call failed: rpc error: code = Unknown desc = pod name io.kubernetes.cri.sandbox-name is missing in annotations: unknown
```
I think it's because we need another cloud-api-adaptor build to pull in the kata changes before it will be fixed, so I've kicked that off now.

**Comment by stevenhorsman** [comment]
I ran the tests locally and all apart from one passed, so I think this problem is actually fixed. I'm happy to wait for the daily-e2e tests to demonstrate that though before we close it

**Comment by genjuro214** [comment]
Most test cases in daily job passed. The problem in this issue should be resolved.
