### ISSUE TITLE
Evaluate if we can continue to use Packer for building Azure images

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1326]
Hashicorp recently [announced](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license) that they are moving from MPL to BUSL license. With this change a lot of communities are evaluating if we can safely continue to use Terraform & related tooling. 

In our project we use Terraform for setting up CI infrastructure and packer to build images. This issue is mainly to discuss what limitations exists in using Hashicorp tooling. If there is no inhibitions in using the tooling we can safely close this issue.

- CNCF issue regarding the same: https://github.com/cncf/foundation/issues/617

**Comment by mkulke** [comment]
Related discussion on kubernetes: https://github.com/kubernetes-sigs/image-builder/issues/1246

Apparently you can raise an exception to CNCF, it might be viable to this project if there are no alternatives for certain archs. 

Another option would be to move the packer builds into a dedicated downstream repo (not part of CoCO)
