### ISSUE TITLE
Add committer access for Iago

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#1373]
cc @mkulke @surajssd

**Comment by surajssd** [comment]
Do I need to create a PR somewhere for this?

**Comment by bpradipt** [comment]
Currently user onboarding or de-boarding is via github issues. No PR is needed.
@iaguis  should have received an email invite

**Comment by iaguis** [comment]
Got the invite and accepted it. Thank you!
