### ISSUE TITLE
peerpod-ctrl controller pod crashed

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#1399]
Try to deploy peerpod-ctrl with command `make deploy`. The controller pod is not running:
```
confidential-containers-system   peerpod-ctrl-controller-manager-5d64f7bc59-cw6pn         1/2     CrashLoopBackOff   38 (3m39s ago)   172m
```

Error is as bellow:
```
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/manager": stat /manager: no such file or directory: unknown
```

Extract image `quay.io/confidential-containers/peerpod-ctrl:latest`, and there is no `/manager`

Check the image push action last week: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/5998707765/job/16267734278

I doubt it's not built from the correct Dockerfile for peerpod-ctrl?

**Comment by genjuro214** [comment]
@bpradipt

**Comment by mkulke** [comment]
I can confirm this. I ran into the same issue, there is some mixup, this containers appears to container binaries from cloud-api-adaptor in /usr/local/bin

**Comment by genjuro214** [comment]
I did some investigation.

We set **working-directory** as "peerpod-ctrl" for **jobs.run** by default. However, it seems just applied for **steps.run** according to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun:
"*You can use defaults.run to provide default shell and working-directory options for all [run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) steps in a workflow.*"

So **steps.uses** "docker/build-push-action@v3" is not running in directory "peerpod-ctrl", but the directory of "cloud-api-adaptor". As a result, docker build image with the Dockerfile of "cloud-api-adaptor"

I tried a fix to set context as "peerpod-ctrl": https://github.com/confidential-containers/cloud-api-adaptor/pull/1404

Not sure if we still need specify Dockerfile path via **file**. I don't have the permission to run a workflow to verify the fix.

@snir911 , can you help with it?

**Comment by genjuro214** [comment]
Try to run the workflow from a branch (because we don't have a chance to change the files under `peerpod-ctrl` on main branch): https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6104713559

New image `quay.io/confidential-containers/peerpod-ctrl:latest` has been built and pushed.

Verified the `peerpod-ctrl-controller-manage` pod can be running in my cluster. I'm OK to close this issue.

by the way, @snir911 do we have a plan to create similar workflow for `peerpodconfig-ctrl`? And currently the image `quay.io/confidential-containers/peerpodconfig-ctrl:latest` seems not public?

**Comment by snir911** [comment]
@genjuro214 I think we need one, IDK if there's issue for that, we should have one if not.
cc @jensfr ^
