### ISSUE TITLE
podvm binaries updates

### ISSUE THREAD

**Issue by tumberino** [confidential-containers/cloud-api-adaptor#1410]
1. Increase frequency of the `confidential-containers/podvm-binaries-*` image builds
2. Tag `confidential-containers/podvm-binaries-*` image with hash of versions.yaml
3. Remove agent-protocol-forwarder from this set of binaries / Include agent-protocol forwarder build in the image build step (so it is picks up recent changes)
4. Update the local build steps to check for existing binaries with the hash? 

I think for 1. we can set a trigger based on if the contents changes as part of a merge into main? 

Two related issues:
1. pin kata-containers in versions.yaml
2. agree on cadence for updating versions.yaml in between releases

I hope I've covered what was agreed in the call, please correct/add suggestions.

@stevenhorsman @katexochen @mkulke @bpradipt @huoqifeng

**Comment by katexochen** [comment]
> I think for 1. we can set a trigger based on if the contents changes as part of a merge into main?

:+1:

**Comment by katexochen** [comment]
I've created a separate issue regarding the `versions.yaml` update: https://github.com/confidential-containers/cloud-api-adaptor/issues/1411

**Comment by mkulke** [comment]
ad 1) yup, we can do that on merge to main and then verify whether `confidential-containers/podvm-binaries-*:$(HASH_OF_VERSION_FILE)` exists and skip a build if it does.

**Comment by katexochen** [comment]
> ad 1) yup, we can do that on merge to main and then verify whether confidential-containers/podvm-binaries-*:$(HASH_OF_VERSION_FILE) exists and skip a build if it does.

I think we can use the following trigger, to only trigger a build if the file changed:

```yaml
on:
  push:
    branches:
      - 'main'
    paths:
      - 'versions.yaml'
```

**Comment by wainersm** [comment]
> ```yaml
> versions.yaml
> ```

Notice that it's not the hash of `versions.yaml` that should be tracked, but also all the sources used to build the podvm-binaries image. For example, changes on the `podvm/podvm/Dockerfile.podvm_binaries*`, `podvm/Makefile*`, and so on, should all trigger a re-build of the image I think.

The podvm build workflow starts with building the podvm-builder image, then podvm-binaries and finally the podvm. So perhaps we should start thinking about the caching of podvm-builder first?

Sorry if I missed something as I didn't attend the meeting that you guys discussed this. My interest on this topic is because I added recently a workflow to run the libvirt e2e tests on pull request time, however, it leverages the built podvms from quay.io (i.e. it doesn't rebuild the podvms); and it seems a consensuous that this workflow should be building podvm (unless it is cached properly :)

**Comment by mkulke** [comment]
good points, thanks for chiming in.

We cannot just cache depending on the source, but also on _how_ we build it. And this, ofc, is subject to change in each commit. This applies to all sort of caches, docker and binary-based on github actions.

A lternative options I can imagine:

1) Cache rust `{kata-containers/src/agent,guest-components}/target` folders with github actions and mount them into the podvm docker builds (they probably need to be converted into `docker run` invocations). This way the object files are reused, if possible and afaik it shouldn't hurt if the wrong files are in there. It would speed up things somewhat, the horrible link-time of kata-agent will remain bad (unless we want to change the linker options for CAA).

2) Do not build kata-agent + guest-components in CAA, but retrieve the bins from canonical kata.containers + guest-components. Not sure how feasible this is, possibly more for kata-agent, less for guest-components, which we build w/ specific args.

**Comment by jtumber-ibm** [comment]
As we might add or remove what files are included in the build process, instead of tracking each for changes could we include a `version` field in the versions.yaml file that we can bump without changing the values of any of the references. e.g. when the build process changes? So that the hash would also be updated?

**Comment by wainersm** [comment]
> As we might add or remove what files are included in the build process, instead of tracking each for changes could we include a `version` field in the versions.yaml file that we can bump without changing the values of any of the references. e.g. when the build process changes? So that the hash would also be updated?

I did not understand completely. Are you suggesting to have a `version` for the build process so that any change we will need to bump the that `version` field? If yes, the kernel builds on kata containers have a similar approach that I particularly find error prone.

**Comment by wainersm** [comment]
> good points, thanks for chiming in.
> 
> We cannot just cache depending on the source, but also on _how_ we build it. And this, ofc, is subject to change in each commit. This applies to all sort of caches, docker and binary-based on github actions.
> 
> A lternative options I can imagine:
> 
>     1. Cache rust `{kata-containers/src/agent,guest-components}/target` folders with github actions and mount them into the podvm docker builds (they probably need to be converted into `docker run` invocations). This way the object files are reused, if possible and afaik it shouldn't hurt if the wrong files are in there. It would speed up things somewhat, the horrible link-time of kata-agent will remain bad (unless we want to change the linker options for CAA).
> 
>     2. Do not build kata-agent + guest-components in CAA, but retrieve the bins from canonical kata.containers + guest-components. Not sure how feasible this is, possibly more for kata-agent, less for guest-components, which we build w/ specific args.

The solution can even be a mix of 1) and 2).

But regarding 2), on the CAA meeting today @stevenhorsman pointed out to this https://github.com/kata-containers/kata-containers/pull/7835 . Kata Containers uses a cache mechanism which essentially caches tarballs on Jenkins, and @fidencio has worked to switch to docker images (i.e. cache the built components in docker images). One possibility would be to consume built kata-agent from those images... a similar approach could be taken on guest-components maybe?

**Comment by stevenhorsman** [comment]
I think we can close this issue now. We support guest-components and kata-agent caching, so build the podvm binaries every night and on all the PRs to ghcr.io
