### ISSUE TITLE
e2e test: Random namespaces for tests are not generated

### ISSUE THREAD

**Issue by mattarnoatibm** [confidential-containers/cloud-api-adaptor#1425]
In the cloud-provider common e2e test functions each test function should start by generating a random namespace name, however that's not what actually happens when calling the function:

```
namespace := envconf.RandomName("default", 7)
```

This is because `envconf.RandomName(prefix, length)` doesn't generate a string with the prefix `prefix` and `length` random characters, instead it generates a string of length `length` with the prefix `prefix`. So when `prefix := "default"` and `length := 7` the string generated is always `"default"` and has no random part because the `prefix` is already 7 characters long.

Setting `length := 9` the tests cases don't run because there is no code to create a namespace resource that doesn't exist in the test case `WithSetup` function - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/test/e2e/common_suite_test.go#L129

As a fix, we could either remove then code that looks like it's there to generate a random namespace and run all the tests in the `default` namespace, which is the approach Kata takes, or we could use a longer namespace name length so the namespaces names generated by `envconf.RandomName` include random elements, and fix the tests case setup and teardown to create and delete, respectively, new namespaces.

**Comment by stevenhorsman** [comment]
Super-ceded by #1652
