### ISSUE TITLE
Azure: e2e test panics when using preinstalled cluster

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1441]
I had a cluster pre-installed so this is how I ran the tests. The test fails as follows:

```bash
$ make test-e2e
go test -v -tags=azure -timeout 60m -count=1 ./test/e2e
time="2023-09-15T00:41:23Z" level=info msg="Do setup"
time="2023-09-15T00:41:24Z" level=info msg="Deploy the Cloud API Adaptor"
=== RUN   TestDeletePodAzure
=== RUN   TestDeletePodAzure/DeletePod_test
    common_suite_test.go:198: Expected Pod State: Running
    common_suite_test.go:199: Current Pod State: Running
=== RUN   TestDeletePodAzure/DeletePod_test/Deletion_complete
--- FAIL: TestDeletePodAzure (115.68s)
    --- FAIL: TestDeletePodAzure/DeletePod_test (115.68s)
        --- FAIL: TestDeletePodAzure/DeletePod_test/Deletion_complete (0.07s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2e863c4]

goroutine 182 [running]:
testing.tRunner.func1.2({0x319f460, 0x4ba8390})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x319f460, 0x4ba8390})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/confidential-containers/cloud-api-adaptor/test/e2e.AzureCloudAssert.HasPodVM({0xc0003ae990?}, 0xc0007684e0, {0xc0020fcf90, 0xd})
        /home/suraj/code/work/cloud-api-adaptor/test/e2e/azure_test.go:75 +0x64
github.com/confidential-containers/cloud-api-adaptor/test/e2e.(*testCase).run.func2({0x3a3ea10, 0xc000116010}, 0xc0007684e0, 0xc0003e09a0?)
        /home/suraj/code/work/cloud-api-adaptor/test/e2e/common_suite_test.go:295 +0xbc2
sigs.k8s.io/e2e-framework/pkg/env.(*testEnv).executeSteps(0xc0002c4140, {0x3a3ea10?, 0xc000116010?}, 0x456ab80?, {0xc002365f50?, 0x1, 0x14e1bc5?})
        /home/suraj/go/pkg/mod/sigs.k8s.io/e2e-framework@v0.1.0/pkg/env/env.go:421 +0xa3
sigs.k8s.io/e2e-framework/pkg/env.(*testEnv).execFeature.func1.1(0xc0007684e0)
        /home/suraj/go/pkg/mod/sigs.k8s.io/e2e-framework@v0.1.0/pkg/env/env.go:452 +0xad
testing.tRunner(0xc0007684e0, 0xc0019b1aa0)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/confidential-containers/cloud-api-adaptor/test/e2e   115.791s
FAIL
make: *** [Makefile:93: test-e2e] Error 1
```

Panic originates here: https://github.com/confidential-containers/cloud-api-adaptor/blob/c30eaac2f971229c9059f4a7a935294c8d9f8524/test/e2e/azure_test.go#L73-L75

Steps to recreate it:

```bash
export TEST_PROVISION=no
export CLOUD_PROVIDER=azure
export BUILTIN_CLOUD_PROVIDERS=azure
export TEST_PROVISION_FILE=/tmp/provision_azure.properties

cat <<EOF >/tmp/provision_azure.properties
AZURE_CLIENT_ID=""
AZURE_SUBSCRIPTION_ID=""
RESOURCE_GROUP_NAME=""
CLUSTER_NAME=""
LOCATION="eastus"
SSH_KEY_ID="id_rsa.pub"
IS_CI_MANAGED_CLUSTER="true"
AZURE_CLI_AUTH="true"
AZURE_IMAGE_ID="/CommunityGalleries/cocopodvm-d0e4f35f-5530-4b9c-8596-112487cdea85/Images/podvm_image0/Versions/2023.09.15"
CAA_IMAGE="quay.io/confidential-containers/cloud-api-adaptor:latest"
MANAGED_IDENTITY_NAME="caa-identity"
EOF

make test-e2e
```

When running these commands the resource group is never populated. Since I have set `TEST_PROVISION` to `no` this is never called: https://github.com/confidential-containers/cloud-api-adaptor/blob/c30eaac2f971229c9059f4a7a935294c8d9f8524/test/e2e/main_test.go#L102-L104

Hence this part is never called: https://github.com/confidential-containers/cloud-api-adaptor/blob/c30eaac2f971229c9059f4a7a935294c8d9f8524/test/provisioner/provision_azure.go#L169-L172

hence this is never called: https://github.com/confidential-containers/cloud-api-adaptor/blob/c30eaac2f971229c9059f4a7a935294c8d9f8524/test/provisioner/provision_azure.go#L98-L99

hence this is never called which populates the resourcegroup object:

https://github.com/confidential-containers/cloud-api-adaptor/blob/c30eaac2f971229c9059f4a7a935294c8d9f8524/test/provisioner/provision_azure.go#L36-L47

**Comment by kartikjoshi21** [comment]
Looking into it. Thanks @surajssd

**Comment by surajssd** [comment]
Just for documenting, here is the workaround that works for me:

```diff
diff --git test/e2e/main_test.go test/e2e/main_test.go
index c8d9f0d..fba6a58 100644
--- test/e2e/main_test.go
+++ test/e2e/main_test.go
@@ -99,12 +99,12 @@ func TestMain(m *testing.M) {
                log.Info("Do setup")
                var err error

-               if shouldProvisionCluster {
-                       log.Info("Cluster provisioning")
-                       if err = provisioner.CreateVPC(ctx, cfg); err != nil {
-                               return ctx, err
-                       }
+               log.Info("Cluster provisioning")
+               if err = provisioner.CreateVPC(ctx, cfg); err != nil {
+                       return ctx, err
+               }

+               if shouldProvisionCluster {
                        if err = provisioner.CreateCluster(ctx, cfg); err != nil {
                                return ctx, err
                        }
@@ -120,10 +120,10 @@ func TestMain(m *testing.M) {
                if cloudAPIAdaptor, err = pv.NewCloudAPIAdaptor(cloudProvider, relativeInstallDirectory); err != nil {
                        return ctx, err
                }
-               log.Info("Deploy the Cloud API Adaptor")
-               if err = cloudAPIAdaptor.Deploy(ctx, cfg, provisioner.GetProperties(ctx, cfg)); err != nil {
-                       return ctx, err
-               }
+               // log.Info("Deploy the Cloud API Adaptor")
+               // if err = cloudAPIAdaptor.Deploy(ctx, cfg, provisioner.GetProperties(ctx, cfg)); err != nil {
+               //      return ctx, err
+               // }
                return ctx, nil
        })

```

And the config looks like the following:

```bash
export TEST_PROVISION=no
export TEST_TEARDOWN=no
export CLOUD_PROVIDER=azure
export BUILTIN_CLOUD_PROVIDERS=azure
export TEST_PROVISION_FILE=/tmp/provision_azure.properties

cat <<EOF >/tmp/provision_azure.properties
AZURE_CLIENT_ID=""
AZURE_SUBSCRIPTION_ID=""
RESOURCE_GROUP_NAME="caa-rg-202309Sep22205749"
CLUSTER_NAME="caa-202309Sep22214501"
LOCATION="eastus"
SSH_KEY_ID="id_rsa.pub"
IS_CI_MANAGED_CLUSTER="true"
AZURE_CLI_AUTH="true"
AZURE_IMAGE_ID=""
CAA_IMAGE="quay.io/surajd/cloud-api-adaptor:latest"
MANAGED_IDENTITY_NAME="caa-identity"
EOF

go test -v -tags=azure -timeout 60m -run -count=1 ./test/e2e
```

**Comment by kartikjoshi21** [comment]
> Just for documenting, here is the workaround that works for me:
> 
> ```diff
> diff --git test/e2e/main_test.go test/e2e/main_test.go
> index c8d9f0d..fba6a58 100644
> --- test/e2e/main_test.go
> +++ test/e2e/main_test.go
> @@ -99,12 +99,12 @@ func TestMain(m *testing.M) {
>                 log.Info("Do setup")
>                 var err error
> 
> -               if shouldProvisionCluster {
> -                       log.Info("Cluster provisioning")
> -                       if err = provisioner.CreateVPC(ctx, cfg); err != nil {
> -                               return ctx, err
> -                       }
> +               log.Info("Cluster provisioning")
> +               if err = provisioner.CreateVPC(ctx, cfg); err != nil {
> +                       return ctx, err
> +               }
> 
> +               if shouldProvisionCluster {
>                         if err = provisioner.CreateCluster(ctx, cfg); err != nil {
>                                 return ctx, err
>                         }
> @@ -120,10 +120,10 @@ func TestMain(m *testing.M) {
>                 if cloudAPIAdaptor, err = pv.NewCloudAPIAdaptor(cloudProvider, relativeInstallDirectory); err != nil {
>                         return ctx, err
>                 }
> -               log.Info("Deploy the Cloud API Adaptor")
> -               if err = cloudAPIAdaptor.Deploy(ctx, cfg, provisioner.GetProperties(ctx, cfg)); err != nil {
> -                       return ctx, err
> -               }
> +               // log.Info("Deploy the Cloud API Adaptor")
> +               // if err = cloudAPIAdaptor.Deploy(ctx, cfg, provisioner.GetProperties(ctx, cfg)); err != nil {
> +               //      return ctx, err
> +               // }
>                 return ctx, nil
>         })
> ```
> 
> And the config looks like the following:
> 
> ```shell
> export TEST_PROVISION=no
> export TEST_TEARDOWN=no
> export CLOUD_PROVIDER=azure
> export BUILTIN_CLOUD_PROVIDERS=azure
> export TEST_PROVISION_FILE=/tmp/provision_azure.properties
> 
> cat <<EOF >/tmp/provision_azure.properties
> AZURE_CLIENT_ID=""
> AZURE_SUBSCRIPTION_ID=""
> RESOURCE_GROUP_NAME="caa-rg-202309Sep22205749"
> CLUSTER_NAME="caa-202309Sep22214501"
> LOCATION="eastus"
> SSH_KEY_ID="id_rsa.pub"
> IS_CI_MANAGED_CLUSTER="true"
> AZURE_CLI_AUTH="true"
> AZURE_IMAGE_ID=""
> CAA_IMAGE="quay.io/surajd/cloud-api-adaptor:latest"
> MANAGED_IDENTITY_NAME="caa-identity"
> EOF
> 
> go test -v -tags=azure -timeout 60m -run -count=1 ./test/e2e
> ```

I think its better to use self provisioner class differently as if in future we have some other requirement that code is extendable and we dont have to change things for every provider. What do you think ? Thanks
