### ISSUE TITLE
Azure Nightly Builds fail to find the `versions.yaml` file

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1446]
With the addition of the ability to read versions from the `versions.yaml` file currently the nightly builds fail as follows:

```bash
...
Error: open versions.yaml: no such file or directory
Error: Process completed with exit code 1.
```

source ^^ : https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6229388473/job/16907802165

My guess is that the current working directory is: `cloud-api-adaptor/azure/image`. So when accessing `versions.yaml` we should access it as `../../versions.yaml`.
https://github.com/confidential-containers/cloud-api-adaptor/blob/d64c9d4241a4ff34ccc4b855257c54c9b397bdd7/.github/workflows/azure-podvm-image-build.yml#L51-L63

**Comment by surajssd** [comment]
Even though the https://github.com/confidential-containers/cloud-api-adaptor/pull/1451 tried to remedy this problem, but it seems like the code still fails to find the `versions.yaml` file. e6860f29360c8346db28ecc97c2d0a01a0c52e1a is the latest commit but this workflow failed: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6229388473/job/16973686120.

<img width="780" alt="image" src="https://github.com/confidential-containers/cloud-api-adaptor/assets/5815795/efce34cc-7231-489e-b1c3-dd207f04a9c7">

**Comment by mkulke** [comment]
I suspect this is because the jobs have been rerun. AFAIU this means changes in the workflow file would not be reflected in re-run, and apparently that applies to nested workflows too.

A manual launch from main seems to work. lets hope the nightly build passes in a few hours

<img width="579" alt="image" src="https://github.com/confidential-containers/cloud-api-adaptor/assets/273280/754e8519-638e-4b25-8672-e99ee5cdbc5e">

**Comment by surajssd** [comment]
@mkulke gotcha :-)

**Comment by mkulke** [comment]
the build still fails, but the breakage is caused by another error apparently: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701

**Comment by surajssd** [comment]
Yes it fails because of the following error:

```bash
make image BINARIES=
  echo "successfully built $IMAGE_ID"
  echo "image-id=${IMAGE_ID}" >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash -e {0}
  env:
    AZURE_PODVM_IMAGE_DEF_NAME: podvm_image0
    AZURE_PODVM_IMAGE_VERSION: 202[3](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:3).09.21
    COMMUNITY_GALLERY_PREFIX: /CommunityGalleries/cocopodvm-d0e[4](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:4)f3[5](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:5)f-5530-4b9c-859[6](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:6)-11248[7](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:7)cdea[8](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:8)5
    PODVM_IMAGE_NAME: peerpod-image-625542[9](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:9)517-2
    SSH_USERNAME: peerpod
...
    PODVM_DISTRO: ubuntu
Error: unknown command ".cloudimg.ubuntu.focal.amd64.url | select(. != null)" for "yq"
Run 'yq --help' for usage.
../../podvm/../Makefile.defaults:[16](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6255429517/job/17008716701#step:16:16): *** cloudimg.ubuntu.focal.amd64.url is not set, and could not be automatically set from /home/runner/work/cloud-api-adaptor/cloud-api-adaptor/cloud-api-adaptor/versions.yaml.  Stop.
Error: Process completed with exit code 2.
```

The generated path is weird: `/home/runner/work/cloud-api-adaptor/cloud-api-adaptor/cloud-api-adaptor/versions.yaml`.

**Comment by mkulke** [comment]
> The generated path is weird: `/home/runner/work/cloud-api-adaptor/cloud-api-adaptor/cloud-api-adaptor/versions.yaml`.

Apparently this is an idiosyncratic property of Github actions: the default cwd of a job is `/home/runner/work/<your-repo>/<your-repo`. so it's probably what we desire, since we clone the repo into a child folder.

**Comment by mkulke** [comment]
I find this error curious, because i ndicates that an outdated version of yq is being used:

`Error: unknown command ".cloudimg.ubuntu.focal.amd64.url | select(. != null)" for "yq"`

I can reproduce it with yq v3:

```
yq_v3 '.cloudimg.ubuntu.focal.amd64.url | select(. != null)' versions.yaml
Error: unknown command ".cloudimg.ubuntu.focal.amd64.url | select(. != null)" for "yq"
Run 'yq --help' for usage.
```

It's weird, though that the "read properties from versions.yaml" step is using the same syntax and not failing. It's as if the Makefile would use another version of yq

**Comment by mkulke** [comment]
got it 😒 it's downgrading to yq v3 in the kata build

![image](https://github.com/confidential-containers/cloud-api-adaptor/assets/273280/ab0cfdcc-f98e-4898-ae5f-c2387f41d146)

1 more reason to not build kata in this repo
