### ISSUE TITLE
Optimise detection of provider  from within podvm

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#1458]
Currently AWS and Azure provider are detected from within podvm by connecting to respective metadata service url. 
Ref: 
https://github.com/confidential-containers/cloud-api-adaptor/blob/main/pkg/adaptor/cloud/aws/misc.go#L19
https://github.com/confidential-containers/cloud-api-adaptor/blob/main/pkg/adaptor/cloud/azure/misc.go#L20

We perform potentially unnecessary roundtrips to the IMDS endpoints. Also when extending this approach to other providers, if the IMDS endpoints are same then we cannot determine the provider deterministically. 

This issue is a tracker to investigate alternatives like build time option, getting the platform from sysfs etc.

**Comment by bpradipt** [comment]
cc @mkulke

**Comment by mkulke** [comment]
this should be addressed with #2172  we can use cpuid as a heuristic to know the clowd provider
