### ISSUE TITLE
Azure-e2e-test: Add test to verify SKR

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1471]
Right now, we just deploy CAA on Azure and don't do any tests that ensure confidentiality. So with this issue there should be a test that deploys everything (along with KBS) and does an SKR test.

**Comment by mkulke** [comment]
Note: in scope of v0.8, we'll probably only be able to do use cc_kbc for registry creds, and image decryption keys (maybe signatures).

**Comment by surajssd** [comment]
We can use CDH for runtime key release and image decryption keys both.
