### ISSUE TITLE
A badge to display the successful azure-nightly-podvm-builds

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1491]
Right now, sometimes the nightly build fails and right now the instructions specify that users use the image from last night. If we could display a badge of last successful nightly build on the README [here](https://github.com/confidential-containers/cloud-api-adaptor/tree/main/azure#build-caa-pod-vm-image), it would be useful for users to see what version to use.

Here are the various options:

- GH default

```
[![azure podvm image nightly build](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml/badge.svg)](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml)
```
which looks like this: 

[![azure podvm image nightly build](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml/badge.svg)](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml)

This does not tells us what version of the latest image to use.

- Or we can simply ask users to checkout what the latest build is and figure out the version from there: https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml

**Comment by surajssd** [comment]
There is one more way to do this. We don't even need any badge.

- Create a branch on this repo, let's call it `azure-podvm-nightly-versions`.
- On this branch there is no code just a file called `version.txt` with version in it in the format `x.y.z`.
- Whenever a build passes, we checkout this branch from CAA repo, update the `version.txt` commit and push.
- In the documentation we reference this file from that branch.

**Comment by kartikjoshi21** [comment]
> There is one more way to do this. We don't even need any badge.
> 
> 1. Create a branch on this repo, let's call it `azure-podvm-nightly-versions`.
> 2. On this branch there is no code just a file called `version.txt` with version in it in the format `x.y.z`.
> 3. Whenever a build passes, we checkout this branch from CAA repo, update the `version.txt` commit and push.
> 4. In the documentation we reference this file on the branch `azure-podvm-nightly-versions` using `curl`.

Thanks Suraj, i think this will suffice all our needs for this. I will start working on it.

**Comment by kartikjoshi21** [comment]
Added steps to the documentation. This issue is not needed anymore. Closing this one. Thanks
https://github.com/confidential-containers/confidentialcontainers.org/pull/20
