### ISSUE TITLE
`KATA_SRC_REF` is not used anywhere

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#1504]
We define `KATA_SRC_REF` but we don't make use of it anywhere. Also, during the podvm build, we expect the kata-containers repository to exist already.

**Comment by surajssd** [comment]
I guess we rely on `KATA_SRC_BRANCH` a lot but not in the `Makefile` though. Since this is not in the Makefile, when doing local builds one has to manually go to the `kata-containers` directory sitting adjacent to the current CAA directory and manually checkout that directory, this is not documented anywhere. Not codified either.

I guess we should not rely on the kata-containers repository sitting adjacent to the CAA repo. We should download this tar directly from GH for the CCv0 branch and use that to do the builds.

**Comment by jtumber-ibm** [comment]
This has been fixed in https://github.com/confidential-containers/cloud-api-adaptor/pull/1448
