### ISSUE TITLE
Build arch build in docker buildx separately in GHA runner

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#1521]
Refer: https://cloud-native.slack.com/archives/C04A2EJ70BX/p1697121903059729

image build pops error like:
```
build and push / build and push (release, linux/amd64,linux/s390x,linux/ppc64le)
The hosted runner: GitHub Actions 17 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`
```
https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6493871571

Suspecting which might be caused by OOM in docker `buildx`, the default runner resource listed in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners, which is:
```
2 cores, 7G RAM, 14G SSD
```  

An alternative might be use a larger runner https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/managing-larger-runners

**Comment by huoqifeng** [comment]
Tried `'--memory="5g" --memory-swap="10g"'` in branch https://github.com/confidential-containers/cloud-api-adaptor/tree/image-action, still have failures. This seems not a resource constraint or buildx OOM problem.

**Comment by huoqifeng** [comment]
Tried to separate the build per arch, the build time has been reduced greatly, so, we may considering build arch build separately and hen generate the images manifest file. Also we can build the libvirt in all arch's build and remove dev-xxx tag.

**Comment by bpradipt** [comment]
If we remove dev-xxx tag, then all the builds will be dynamically linked as libvirt uses CGO. Let's hear from others if it's fine.

**Comment by huoqifeng** [comment]
- Flow:
![image](https://github.com/confidential-containers/cloud-api-adaptor/assets/15607193/4ad502fc-62d8-4c3c-8cbd-726dd52b0ec6)


- Code Change
https://github.com/confidential-containers/cloud-api-adaptor/commit/c7768829cfa190001eb27ea2aceb204b12c0603d

- Image Build Action
https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/6582408046/job/17884771082

- Built Images
https://quay.io/repository/confidential-containers/cloud-api-adaptor?tab=tags

Achieved: Looks good in quay, and can be pulled on different platform, however, the `"Architecture": "amd64"` returns for `docker inspect quay.io/confidential-containers/cloud-api-adaptor:c7768829cfa190001eb27ea2aceb204b12c0603d` on s390x, but it's s390x image indeed. -- maybe its because of the docker cli limitation described in https://github.com/moby/moby/pull/43103

**Comment by huoqifeng** [comment]
`docker load` and `docker import` did lost the architecture info, maybe, push arch specific image to registry is right approach.

**Comment by huoqifeng** [comment]
I'll start working on the alternative action: basic flow is:
- Job 1:
  - Build arch specific image and push it
  - Export the `dev_tags` and `release_tags` and upload it to GHA artifactory
  - Export the arches file to artifactory
- Job 2
  - Download the files from artifactory
  - Read `dev_tags` and `release_tags`
  - Read all arches
  - Iterate the arches and tags and generate the manifest
  - Push the manifest
- Job 3
  - Download the files from artifactory
  - Read `dev_tags` and `release_tags`
  - Read all arches
  - Verify all arches by pulling manifest from registry

**Comment by huoqifeng** [comment]
Good news is the image building GHA all succeeded when build it one by one.
