### ISSUE TITLE
Release v0.8.0

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/cloud-api-adaptor#1548]
Issue tracker for the CAA release as part of [CoCo v0.8.0](https://github.com/confidential-containers/confidential-containers/issues/145)

## v0.8.0-alpha.1

- [x] IBM Cloud amd64
- [x] IBM Cloud s390x
- [x] Azure, AKS, SEV-SNP, Ubuntu 22.04
- [x] Libvirt amd64
- [ ] AWS EKS

**Comment by wainersm** [comment]
Kata Containers for CoCo 0.8.0 RC1 - commit 424de1cbfa4e1da9ecf9a56b1d1e1a11a4f339cd

**Comment by wainersm** [comment]
guest-components for CoCo 0.8.0 RC1 - commit 615a46ff16ee8670014946d14e44e85cede82f01 (same commit pinned on kata's 424de1cbfa4e1da9ecf9a56b1d1e1a11a4f339cd)

**Comment by stevenhorsman** [comment]
I've raised PR https://github.com/confidential-containers/cloud-api-adaptor/pull/1559

To cover this sections:
> Update the csi-wrapper and peerpod-ctrl go modules to use the tagged version of cloud-api-adapter, by running:
> ```
> go get github.com/confidential-containers/cloud-api-adaptor@v<version>-alpha.1
> go mod tidy
> ```
> in their directories and removing the local replace references if we needed to add them earlier.

of the release doc

**Comment by stevenhorsman** [comment]
I've created pre-release https://github.com/confidential-containers/cloud-api-adaptor/releases/tag/v0.8.0-alpha.1 now, which should trigger the podvm build process to test that.

**Comment by stevenhorsman** [comment]
As reported on Slack, I've manually tested the RC podvm and CAA code for IBM Cloud with amd64 and s390x clusters/peer pods

**Comment by mkulke** [comment]
I tested azure podvm & caa images built on the `v0.8.0-alpha.1` rev. looks good, also remote attestation seems to work.

**Comment by mkulke** [comment]
hmm, when running the e2e test suite, other than in my manual test, i'm seeing snapshot errors:

```
Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull
  and unpack image "docker.io/library/nginx:latest": failed to prepare
  extraction snapshot "extract-218425411-EbOv
  sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a":
  missing CRI reference annotation for snaposhot 8: unknown
  ```
Note the typo "snaposhot", that's from nydus apparently

**Comment by wainersm** [comment]
> @stevenhorsman managing to run the alpha.1 release with AWS

The simple pod failed on AWS (AKS) and remaining tests didn't run because it hit the timeout:
```
=== RUN   TestAwsCreateSimplePod
=== RUN   TestAwsCreateSimplePod/SimplePeerPod_test
    assessment_runner_test.go:190: timed out waiting for the condition
--- FAIL: TestAwsCreateSimplePod (900.53s)
    --- FAIL: TestAwsCreateSimplePod/SimplePeerPod_test (900.53s)
```

I will get more information.

FYI @bpradipt

**Comment by stevenhorsman** [comment]
> > @stevenhorsman managing to run the alpha.1 release with AWS
> 
> The simple pod failed on AWS (AKS) and remaining tests didn't run because it hit the timeout:
> 
> ```
> === RUN   TestAwsCreateSimplePod
> === RUN   TestAwsCreateSimplePod/SimplePeerPod_test
>     assessment_runner_test.go:190: timed out waiting for the condition
> --- FAIL: TestAwsCreateSimplePod (900.53s)
>     --- FAIL: TestAwsCreateSimplePod/SimplePeerPod_test (900.53s)
> ```

Hey Wainer, does your cluster have multiple worker nodes by any chance. I've just realised that my nydus verification tests just runs on the first CAA ds it finds, so wouldn't be reliable on a mutli node cluster. I'm looking to fix it soon, but can back out the test failure in the short-term if it's causing issues?

**Comment by wainersm** [comment]
> > > @stevenhorsman managing to run the alpha.1 release with AWS
> > 
> > 
> > The simple pod failed on AWS (AKS) and remaining tests didn't run because it hit the timeout:
> > ```
> > === RUN   TestAwsCreateSimplePod
> > === RUN   TestAwsCreateSimplePod/SimplePeerPod_test
> >     assessment_runner_test.go:190: timed out waiting for the condition
> > --- FAIL: TestAwsCreateSimplePod (900.53s)
> >     --- FAIL: TestAwsCreateSimplePod/SimplePeerPod_test (900.53s)
> > ```
> 
> @wainersm - Hey Wainer, does your cluster have multiple worker nodes by any chance. I've just realised that my nydus verification tests just runs on the first CAA ds it finds, so wouldn't be reliable on a mutli node cluster. I'm looking to fix it soon, but can back out the test failure in the short-term if it's causing issues?

Hi @stevenhorsman , it is a single-node cluster but good to know tests aren't reliable on a multi-node cluster!

The problem is actually the region the framework deployed the cluster does not support confidential VM, which is now the default since commit e4059a5223bf4a955391b7f87178af9b11809dc2 . I will disable CVM and see if it passes the simple tests.

**Comment by stevenhorsman** [comment]
> it is a single-node cluster but good to know tests aren't reliable on a multi-node cluster!

I've created https://github.com/confidential-containers/cloud-api-adaptor/pull/1562 which I hope fixes the issue

**Comment by wainersm** [comment]
@bpradipt @stevenhorsman the status of my tests for AWS is:

* I deployed the AKS cluster in a region that doesn't support AMD SEV-SNP so I had to disable CVM (`DISABLECVM=true`)
* Some tests started to pass, others not. The "simple pod" which checks the nydus snapshotter is used failed; it turned out the AKS cluster have containerd 1.6 installed, whereas CoCo 0.8.0 requires +1.7
* I managed to install the operator with `INSTALL_OFFICIAL_CONTAINERD=true` which forced the operator to superseed the system's containerd with its own 1.7
* Now the "simple pod" fails to start with a nydus related error:
```
  Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-101183212-RW23 sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 3: unknown
  Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-967947483-KBeo sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 4: unknown
  Warning  Failed     47m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-758725951-sRqW sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 5: unknown
```
Does it ring a bell?

My cluster was gone overnight and I am working to re-install it to obtain more information.

**Comment by mkulke** [comment]
> * Now the "simple pod" fails to start with a nydus related error:
> 
> ```
>   Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-101183212-RW23 sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 3: unknown
>   Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-967947483-KBeo sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 4: unknown
>   Warning  Failed     47m                    kubelet         
> ```

Oh, that's relieving to see 😅 

but are we talking about _AKS_ or _EKS_ (on AWS)? AKS clusters should bundle containerd 1.7, I think?

**Comment by wainersm** [comment]
> > * Now the "simple pod" fails to start with a nydus related error:
> > 
> > ```
> >   Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-101183212-RW23 sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 3: unknown
> >   Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-967947483-KBeo sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 4: unknown
> >   Warning  Failed     47m                    kubelet         
> > ```
> 
> Oh, that's relieving to see 😅
> 
> but are we talking about _AKS_ or _EKS_ (on AWS)? AKS clusters should bundle containerd 1.7, I think?

Sorry, I meant AWS EKS :)

**Comment by wainersm** [comment]
> > > * Now the "simple pod" fails to start with a nydus related error:
> > > 
> > > ```
> > >   Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-101183212-RW23 sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 3: unknown
> > >   Warning  Failed     48m                    kubelet            Failed to pull image "nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to prepare extraction snapshot "extract-967947483-KBeo sha256:ec983b16636050e69677eb81537e955ab927757c23aaf73971ecf5f71fcc262a": missing CRI reference annotation for snaposhot 4: unknown
> > >   Warning  Failed     47m                    kubelet         
> > > ```
> > 
> > 
> > Oh, that's relieving to see 😅
> > but are we talking about _AKS_ or _EKS_ (on AWS)? AKS clusters should bundle containerd 1.7, I think?
> 
> Sorry, I meant AWS EKS :)

Yesterday I tried again on AWS EKS on two versions (1.26 and 1.28) of kubernetes; I got the same `missing CRI reference annotation for snaposhot ` error on both cases.

Then I deployed a kubeadm cluster via kcli on AWS with CentOS Stream 8 workers. This time I wasn't even able to get the podvm properly runnings (it fails on the "initializing" checks). This is the first time I tried that installation method it might be that I made some mistake.

@mkulke any luck with AKS?

**Comment by mkulke** [comment]
@wainersm: not yet, I'm trying to establish a working baseline with CLOUD_PROVIDER=libvirt on a single-node cluster. kcli also gave me grief, so I aborted that approach and i'm trying to deploy libvirt on single-node cluster created with kubeadm. It will start VMs, but the podvm do not seem to come up properly.

Do you think it makes sense to reference the `missing CRI reference annotation for snaposhot` to the [tracking issue](https://github.com/kata-containers/kata-containers/issues/8407) for remote-snapshotter on CC, now that we have this somewhat confirmed?

**Comment by wainersm** [comment]
> @wainersm: not yet, I'm trying to establish a working baseline with CLOUD_PROVIDER=libvirt on a single-node cluster. kcli also gave me grief, so I aborted that approach and i'm trying to deploy libvirt on single-node cluster created with kubeadm. It will start VMs, but the podvm do not seem to come up properly.
> 
> Do you think it makes sense to reference the `missing CRI reference annotation for snaposhot` to the [tracking issue](https://github.com/kata-containers/kata-containers/issues/8407) for remote-snapshotter on CC, now that we have this somewhat confirmed?

Good idea. let me add an entry on that for the peer pod issue.

**Comment by wainersm** [comment]
> > @wainersm: not yet, I'm trying to establish a working baseline with CLOUD_PROVIDER=libvirt on a single-node cluster. kcli also gave me grief, so I aborted that approach and i'm trying to deploy libvirt on single-node cluster created with kubeadm. It will start VMs, but the podvm do not seem to come up properly.
> > Do you think it makes sense to reference the `missing CRI reference annotation for snaposhot` to the [tracking issue](https://github.com/kata-containers/kata-containers/issues/8407) for remote-snapshotter on CC, now that we have this somewhat confirmed?
> 
> Good idea. let me add an entry on that for the peer pod issue.

Done :)

**Comment by mkulke** [comment]
Marked AKS as passing, also manually tested image decryption with snapshotter pulling, works as intended.

**Comment by stevenhorsman** [comment]
I've created https://github.com/confidential-containers/cloud-api-adaptor/pull/1570 to bump the versions to the 0.8 release

**Comment by stevenhorsman** [comment]
After the release I re-tested everything from scratch locally. For IBM cloud on s390x every test passed. For libvirt on kcli on x86 they all passed except nydus pull:
```
=== RUN   TestLibvirtCreateSimplePodWithNydusAnnotation/SimplePeerPod_test/PodVM_is_created
    assessment_helpers_test.go:162: Called PullImage explicitly, not using nydus-snapshotter :2023/11/14 15:08:25 [adaptor/proxy] CreateContainer: calling PullImage for "docker.io/library/alpine:latest" before CreateContainer (cid: "697963694d8aed2171cd3ea83759e0893c9f752b63c0e4047ffba26fc0c8e97d")
    assessment_runner_test.go:370: Expected to pull with nydus, but that didn't happen
time="2023-11-14T07:08:34-08:00" level=info msg="Deleting pod alpine..."
time="2023-11-14T07:08:44-08:00" level=info msg="Pod alpine has been successfully deleted within 60s"
--- FAIL: TestLibvirtCreateSimplePodWithNydusAnnotation (117.37s)
    --- FAIL: TestLibvirtCreateSimplePodWithNydusAnnotation/SimplePeerPod_test (117.36s)
        --- FAIL: TestLibvirtCreateSimplePodWithNydusAnnotation/SimplePeerPod_test/PodVM_is_created (1.57s)
```
I've manually checked and we aren't using the nydus pull with libvirt, but given that we've called that experimental I'm not sure if that is a problem at this point?

**Comment by wainersm** [comment]
> After the release I re-tested everything from scratch locally. For IBM cloud on s390x every test passed. For libvirt on kcli on x86 they all passed except nydus pull:
> 
> ```
> === RUN   TestLibvirtCreateSimplePodWithNydusAnnotation/SimplePeerPod_test/PodVM_is_created
>     assessment_helpers_test.go:162: Called PullImage explicitly, not using nydus-snapshotter :2023/11/14 15:08:25 [adaptor/proxy] CreateContainer: calling PullImage for "docker.io/library/alpine:latest" before CreateContainer (cid: "697963694d8aed2171cd3ea83759e0893c9f752b63c0e4047ffba26fc0c8e97d")
>     assessment_runner_test.go:370: Expected to pull with nydus, but that didn't happen
> time="2023-11-14T07:08:34-08:00" level=info msg="Deleting pod alpine..."
> time="2023-11-14T07:08:44-08:00" level=info msg="Pod alpine has been successfully deleted within 60s"
> --- FAIL: TestLibvirtCreateSimplePodWithNydusAnnotation (117.37s)
>     --- FAIL: TestLibvirtCreateSimplePodWithNydusAnnotation/SimplePeerPod_test (117.36s)
>         --- FAIL: TestLibvirtCreateSimplePodWithNydusAnnotation/SimplePeerPod_test/PodVM_is_created (1.57s)
> ```
> 
> I've manually checked and we aren't using the nydus pull with libvirt, but given that we've called that experimental I'm not sure if that is a problem at this point?

Hi Steve, currently kcli deploys Ubuntu 20.04 nodes with containerd 1.6. As we are not setting `INSTALL_OFFICIAL_CONTAINERD=true`  it is not replaced with containerd 1.7, thus nydus-snapshotter doesn't work. Let me send a PR to update the scripts to use ubuntu 22.04... hopefully it will work out of box.

**Comment by stevenhorsman** [comment]
> Let me send a PR to update the scripts to use ubuntu 22.04... hopefully it will work out of box.

@wainersm - FYI - I'm testing https://github.com/stevenhorsman/cloud-api-adaptor/tree/containerd-22.04-switch locally at the moment, but if you have already created this PR then let me know and I can switch to it

**Comment by wainersm** [comment]
> > Let me send a PR to update the scripts to use ubuntu 22.04... hopefully it will work out of box.
> 
> @wainersm - FYI - I'm testing https://github.com/stevenhorsman/cloud-api-adaptor/tree/containerd-22.04-switch locally at the moment, but if you have already created this PR then let me know and I can switch to it

I didn't create the PR because yesterday I couldn't setup the cluster with Ubuntu 22.04 due to this bug: https://github.com/karmab/kcli/issues/615 . I still don't know how to test the fix, whether kcli has nightly builds or not. Do you know? Can you create the cluster with the kcli version you have installed?

Ah, let's use your PR ;)

**Comment by stevenhorsman** [comment]
> Can you create the cluster with the kcli version you have installed?

So to start with the ubuntu 22.04 cluster seems correct:
```
ubuntu@peer-pods-worker-0:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by stevenhorsman** [comment]
I'm guessing that my libvirt testing on rc1 was before the operator change that removed containerd from always being installed and that's why it worked then

**Comment by mkulke** [comment]
> I'm guessing that my libvirt testing on rc1 was before the operator change that removed containerd from always being installed and that's why it worked then

yup. containerd is 1.6 on [ubuntu 22.04](https://packages.ubuntu.com/jammy/containerd). We need to set [that env](https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/peer-pods/kustomization.yaml#L29-L33).
