### ISSUE TITLE
Do not pull pause image in any case

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#1552]
nydus seems not append Device information for pause image sometimes as below:
```
2023/10/11 14:36:00 [adaptor/proxy]     storages:
2023/10/11 14:36:00 [adaptor/proxy]         mount_point:/run/kata-containers/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad/rootfs source:pause fstype:overlay driver:image_guest_pull
```
Which might be nydus or containerd algorithm change, shall we don't pull `pause` image for all cases to avoid trouble when containerd or nydus change?

For example, when we identified the `container_type` is `pod_sandbox` in `CreateContainer` like below. We can always leverage `pullImageInGuest` as which has been embedded in guest already.
```
"io.katacontainers.pkg.oci.container_type": "pod_sandbox",
```

**Comment by huoqifeng** [comment]
@bpradipt @stevenhorsman @yoheiueda idea?

**Comment by stevenhorsman** [comment]
@huoqifeng - I think we might have discussed this in https://github.com/confidential-containers/cloud-api-adaptor/issues/811 IIRC?

**Comment by stevenhorsman** [comment]
I think that with the guest-pull changes in `main`: https://github.com/kata-containers/kata-containers/blob/5d96734831213ac3e28eb2e64ce315caf9f5ede8/src/agent/src/image.rs#L161-L172 we correctly use the annotation to see if we are creating pause, rather than the name, so this should be resolved.
