### ISSUE TITLE
podvm: Remove skopeo and umoci from the peer pod VM image

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#164]
Once the skopeo to image-rs gaps have been resolved (such as signature verification in [https://github.com/kata-containers/kata-containers/issues/4888](https://github.com/kata-containers/kata-containers/issues/4888) and authenticated registry support in [https://github.com/kata-containers/kata-containers/issues/4601](https://github.com/kata-containers/kata-containers/issues/4601)) we should try removing all references to the umoci/skopeo binaries from the peer pod vm images (including the `USE_SKOPEO `, rather than just default to them not being used as per #256) and check that they still work as expected and there aren't any other skopeo specific features we were relying on in any cloud-providers.

The reason being that once we remove the kata-agent references to Skopeo and Umoci then we won't be able to use any skopeo/umoci functions, so want to understand this before we remove an upstream feature we require.

**Comment by ariel-adam** [comment]
@stevenhorsman is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by stevenhorsman** [comment]
Yes, this is relevant and we will hopefully have it for the mid-November release. Yohei is already looking into it IIRC

**Comment by ariel-adam** [comment]
I've mapped it to the CoCo release project, priority medium and drop V0.2.0 as the release

**Comment by yoheiueda** [comment]
I raised a duplicated issue https://github.com/confidential-containers/cloud-api-adaptor/issues/256, and PR #256 has already closed the issue.

**Comment by bpradipt** [comment]
@stevenhorsman any additional work pending w.r.to this issue ?

**Comment by stevenhorsman** [comment]
@bpradipt - yes. As per the description in this - it is about removing all references to building skopeo and umoci in our peer pod VM image builds, rather than just changing the default as #263 did. I want this as a gate for removing the ability to use skopeo in the kata-agent as only by removing the ability to use skopeo (which we know people are still using for authenticated registry support) will we drive out the remaining cases that need skopeo. Does that make sense?
