### ISSUE TITLE
ci/libvirt: pin the version of kcli installed

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/cloud-api-adaptor#1669]
On our libvirt e2e CI, kcli gets installed the latest always. Because kcli is a very active project and releases often, we sometimes install unstable versions that results on the jobs failing. One example is https://github.com/confidential-containers/cloud-api-adaptor/pull/1665

It has been used the https://raw.githubusercontent.com/karmab/kcli/main/install.sh installer in https://github.com/confidential-containers/cloud-api-adaptor/blob/main/libvirt/config_libvirt.sh#L58 that doesn't get a version option. 

@karmab is it possible to add an option to https://raw.githubusercontent.com/karmab/kcli/main/install.sh to get the exact version of kcli to be installed? e.g `curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | sudo bash -s -- -v kcli-99.0.0.git.202401181218`

**Comment by karmab** [comment]
about pinning, sadly only the containers are kept around (which can be installed with podman pull quay.io/karmab/kcli:$TAG)

for rpm and debs, we cant keep all of them in the corresponding copr and cloudsmith repos so we just keep the latest build (which hopefully is stable enough)

**Comment by wainersm** [comment]
> about pinning, sadly only the containers are kept around (which can be installed with podman pull quay.io/karmab/kcli:$TAG)
> 
> for rpm and debs, we cant keep all of them in the corresponding copr and cloudsmith repos so we just keep the latest build (which hopefully is stable enough)

oh, I see, of older versions are pruned.

Thanks once again for the quick response @karmab !

**Comment by karmab** [comment]
what you can do though is that you grab a version that works fine with your ci from https://cloudsmith.io/~karmab/repos/kcli/packages/ and store it where you want.
Note that there are also some snapshots from there that might suit you
for instance, you would pick the latest snapshot with

```
curl -1sLf \
  'https://dl.cloudsmith.io/public/karmab/kcli/setup.deb.sh' \
  | sudo -E bash
apt-get install python3-kcli=24.1.0-0
```
