### ISSUE TITLE
0.8.1 potential release plan

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1677]
Now that Magnus has been able to get everything (including image decryption) working with the `main` branch of CAA and the 0.8 release of the operator, we can think about create a new release to address the challenges with the 0.8 release. The path to do this looks something like:
- [x] Pin the working version of KBS in version.yamls
- [ ] Add the link to the instructions that create the correct encrypted image (based on https://github.com/confidential-containers/guest-components/pull/451)
- [x] Get someone else to check encrypted image works on main in their environment
- [x] Cut an 0.8.1-alpha following the release process
- [ ] Re-test everything
- [ ] Full release

Note - we are not planning to bump kata-runtime, or any extra component versions, so the full release process we normally have isn't required. We might want to add a disclaimer message on the release notes that this is an interim release though

**Comment by bpradipt** [comment]
@stevenhorsman can we create a release (may be an alpha to reduce full release related work) so that we have a working set of components based on CCv0 kata runtime?

I believe a full release might make sense with main as lots of things have changed and CCv0 might not be relevant as is evident here - https://github.com/confidential-containers/cloud-api-adaptor/issues/1750

**Comment by stevenhorsman** [comment]
Yeah I'm happy to create an alpha based on `CCv0` - I guess that we need to find a version of the attestation-agent that is compatible with `CCv0` kata-agent first, or fixed up the `CCv0` version, as it sounds like the latest version of our code isn't working?

**Comment by mkulke** [comment]
I was thinking the same thing. with https://github.com/confidential-containers/cloud-api-adaptor/pull/1748 merged, there would be a somewhat stable foundation (well tested on the CI) that works with trustee/kbs v0.8.2 (tested manually)

I would also like to a fix a race condition for api-server-rest described in #1695 ...testing a fix for that at the moment. but admittedly the race condition is not a regression, it was always there.
