### ISSUE TITLE
azure peerpod image on northeurope

### ISSUE THREAD

**Issue by aep** [confidential-containers/cloud-api-adaptor#1690]
Hi,

could someone push the image to northeurope?
```
{
  "error": {
    "code": "GalleryImageNotFound",
    "message": "\"The gallery image /CommunityGalleries/cococommunity-42d8482d-92cd-415b-b332-7648bd978eff/Images/peerpod-podvm-ubuntu2204-cvm-snp/Versions/0.8.0 is not available in northeurope region. Please contact image owner to replicate to this region, or change your requested region.\"",
    "target": "imageReference"
  }
}
```

i tried building it myself according to  https://github.com/confidential-containers/cloud-api-adaptor/blob/main/azure/build-image.md

but the script assumes push access to quay

**Comment by kartikjoshi21** [comment]
@aep please refer to this [comment ](https://github.com/confidential-containers/cloud-api-adaptor/issues/1696#issuecomment-1934942535 ). You can add replication region in packer config to push it. Also you should use your personal quay credentials in case you want to build local image. The official gallery is supposed to be used for released images only.

**Comment by mkulke** [comment]
images are now pushed to northeurope
