### ISSUE TITLE
Make cloud providers be loaded as plugins for CAA

### ISSUE THREAD

**Issue by liudalibj** [confidential-containers/cloud-api-adaptor#1692]
After the https://github.com/confidential-containers/cloud-api-adaptor/pull/1508 and https://github.com/confidential-containers/cloud-api-adaptor/pull/1642 the CAA codes can be used by other project as package.
We use `Compile-time plugins` to built-in the cloud providers(aws azure ibmcloud vsphere libvirt) into CAA binary from source codes as https://github.com/confidential-containers/cloud-api-adaptor/tree/main/cmd/cloud-api-adaptor.

If we want to add a new cloud provider we need copy the [main.go](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/cmd/cloud-api-adaptor/main.go) and new a providername.go under the same folder and then build updated CAA from source. This is not good enough if we want to support more cloud providers.
When a new provider be added:
- CAA need be rebuild
  - provider define need be added to https://github.com/confidential-containers/cloud-api-adaptor/tree/main/pkg/adaptor/cloud
  - compile-time plugin need be loaded to https://github.com/confidential-containers/cloud-api-adaptor/tree/main/cmd/cloud-api-adaptor
- peerpod-ctrl need be rebuild
  - complie-time plugin need be loaded to https://github.com/confidential-containers/cloud-api-adaptor/tree/main/peerpod-ctrl/controllers for peerpod-ctrl 

The golang program support `Run-time plugin` too, refer to 
https://eli.thegreenplace.net/2021/plugins-in-go/ . If we implement the run-time plugin for CAA then we can use one static CAA binary from opensource and the different cloud provider plugin(.so files) from different cloud provider. This will make others extend CAA easily.

After we support `Run-time plugin` for cloud providers.
When a new provider be added:
- new provider need be added to https://github.com/confidential-containers/cloud-api-adaptor/tree/main/pkg/adaptor/cloud
  - the provider need be built out as .so file
- put the built out .so file to the cloud provider plugins folder

CAA and peerpod-ctrl with Run-time plugin support can load the new plugin from the `cloud provider plugins folder`, the CAA and peerpod-ctrl binaries not need be rebuild anymore.

**Comment by liudalibj** [comment]
@huoqifeng @stevenhorsman @magowan @bpradipt what do you think for we add the `Run-time plugin` for cloud providers.

**Comment by bpradipt** [comment]
> The golang program support `Run-time plugin` too, refer to
> https://eli.thegreenplace.net/2021/plugins-in-go/ . If we implement the run-time plugin for CAA then we can use one static CAA binary from opensource and the different cloud provider plugin(.so files) from different cloud provider. This will make others extend CAA easily.

If we are adding a new provider, the expectation is that the new provider will be added here, will be part of CI/CD and release cadence.
Is the idea to enable third party provider plugins which are proprietary or kept outside of CAA?

If that's the case, then it might be better to support both in-built providers that will be part of a release and dynamically loaded providers which anyone can add. 

I honestly don't know the complexity of supporting both inbuilt and dynamically loaded plugins. But this is something we should explore so that we can take a conscious decision.
