### ISSUE TITLE
Pod VM image in additional regions

### ISSUE THREAD

**Issue by cmaf** [confidential-containers/cloud-api-adaptor#1696]
Is it possible to add the image to the `eastus2` region?

```
 "error": {
    "code": "GalleryImageNotFound",
    "message": "\"The gallery image /CommunityGalleries/cocopodvm-d0e4f35f-5530-4b9c-8596-112487cdea85/Images/podvm_image0/Versions/2024.02.01 is not available in eastus2 region. Please contact image owner to replicate to this region, or change your requested region.\"",
    "target": "imageReference"
```

**Comment by cmaf** [comment]
cc @surajssd

**Comment by surajssd** [comment]
it is possible to replicate the image to other regions during build time by adding a field called `replication_regions` to the packer build script here: https://github.com/confidential-containers/cloud-api-adaptor/blob/372e4e72f7fef27b5adb5376e0361f01b901a8a7/azure/image/ubuntu/azure-ubuntu.pkr.hcl#L26C3-L33

Packer docs here: https://developer.hashicorp.com/packer/integrations/hashicorp/azure/latest/components/builder/arm#shared-image-gallery-destination

If you are willing to try the pod vm image build for Azure here is the documentation: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/azure/build-image.md

**Comment by cmaf** [comment]
Thanks @surajssd. I created PR https://github.com/confidential-containers/cloud-api-adaptor/pull/1698 to add the replication region. 

Is there more documentation about dependencies and build environment for Option 1 in the image build instructions? I have not been able to successfully build it yet due to multiple errors with missing dependencies and environment variables.

**Comment by surajssd** [comment]
> Is there more documentation about dependencies and build environment for Option 1 in the image build instructions? I have not been able to successfully build it yet due to multiple errors with missing dependencies and environment variables.

@cmaf thanks for the feedback, here is the PR that updates the documentation: https://github.com/confidential-containers/cloud-api-adaptor/pull/1699.
