### ISSUE TITLE
azure: support Azure TDX CVMs for podvms

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/cloud-api-adaptor#1703]
at the moment we only build podvms images for Azure's SNP cvms. I think we need to need to extend the guest-components build-flags to also build the `az-vtpm-tdx` attester.

it's probably sufficient to extend `make KBC="cc_kbc_az_snp_vtpm"` to `make KBC="cc_kbc_az_snp_vtpm cc_kbc_az_tdx_vtpm"` for the guest-components's build. alternatively we can add guest-components build flag `cc_kbc_az-cvm-vtpm` that covers both.

**Comment by cmaf** [comment]
@mkulke from the logs in a TDX VM in Azure using the nightly build image, I retrieved

```
[    0.000000] Hyper-V: Isolation Config: Group A 0x1, Group B 0xbe3
```

(from https://www.youtube.com/watch?v=bG7T1Stm2c0). Is this sufficient or do we still need additional guest component build flags?

**Comment by mkulke** [comment]
So, if you are booting an instance size and see this in the logs, you can be positive that we're running on a TDX vm on azure.

```bash
sudo dmesg | grep -i encryption
[    0.624581] Memory Encryption Features active: Intel TDX
[    1.029536] software IO TLB: Memory encryption is active and system is using DMA bounce buffers
```

However if you want to do remote attestation with CoCo we need to add a compile-time-flag (i think) to guest-components: `cc_kbc_az_tdx_vtpm`, it might automagically work out of the box, but i'd be surprised. you could do a call to api-server-rest from inside the peerpod to see whether you can get a TDX report/TPM quote (kubectl exec into it):

```bash
curl http://127.0.0.1:8006/aa/evidence\?runtime_data\=xxxx
```

**Comment by fidencio** [comment]
> (suggested in https://www.youtube.com/watch?v=bG7T1Stm2c0). Is this sufficient or do we still need additional guest component build flags?

@cmaf, this is sufficient, and this is what we use as part of the cpuid project to check whether the VM is a `TDX_GUEST` or not, please, see: https://github.com/klauspost/cpuid/commit/3a00e73348c959330a0c0346a77696e81fd8dc0d

You're, indeed, running on a TDX guest!
