### ISSUE TITLE
Revert #1774

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1792]
Pr #1774 was delivered during release freeze and after a lot of debugging on the release, we found that it breaks the image publish and the push doesn't contain the tags, so it tried to push latest:
https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/8664530199/job/23765073592
```
Using default tag: latest
The push refers to repository [quay.io/confidential-containers/cloud-api-adaptor]
tag does not exist: quay.io/confidential-containers/cloud-api-adaptor:latest
```

Revert it and then cut a new release.

**Comment by liudalibj** [comment]
@stevenhorsman ah, sorry for I forget that we are in release freeze window, won't merge any PRs after we finish the release process.
