### ISSUE TITLE
podvm-mkosi build fails

### ISSUE THREAD

**Issue by wobito** [confidential-containers/cloud-api-adaptor#1843]
When building the podvm-mkosi, the Makefile takes in a `AA_KBC` value for various build steps, but in the AA build stage, there is a `ATTESTER` value available in the sub Makefile for only building some attesters, yet in setting that value it isn't honoured during the podvm-mksoi. ref #1576

```
make ATTESTER=snp-attester
```

Fails with the same error from https://github.com/confidential-containers/cloud-api-adaptor/pull/1576#issuecomment-1810016224

**Comment by stevenhorsman** [comment]
This is outdated, so closing
