### ISSUE TITLE
ibmcloud|demo: Specify existing VPC custom image for e2e script

### ISSUE THREAD

**Issue by jtumber-ibm** [confidential-containers/cloud-api-adaptor#189]
For the e2e terraform script demo the majority of time is taken up capturing an image of the worker instance to create a custom VPC image of the podvm (podvm-build module). In some cases an up-to-date image might already exist that the demo can use, this would save time and also act as a test for the custom image.

There are two approaches that could be taken (maybe others too):

1. Use the `podvm_image_name` variable and check to see if a matching name exists in the VPC images list, if it does then use it instead of creating a new one
2. Or, check to see if a matching image exists for the naming convention `podvm-<commit hash>-<arch>` for the latest commit. 

Currently when cleaning up after the e2e terraform script (`terraform destroy`) will delete the podvm image that was created. So the image needs to have been created separately. The image is also region-locked.

In the case where there is an image available, terraform would still need to run through most of the modules to setup the infrastructure.

**Comment by ariel-adam** [comment]
@jtumber-ibm is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by jtumber-ibm** [comment]
@ariel-adam Probably not, as we are moving towards operator model I doubt the ibmcloud terraform demo will see much development
