### ISSUE TITLE
ci: podvm-mkosi: workflow not working correctly

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1949]
In running the https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/podvm_mkosi_image.yaml
recently we are seeing a failure:
```
#2 [internal] load metadata for docker.io/library/fedora-binaries-builder-s390x:latest
#2 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/library/fedora-binaries-builder-s390x:latest:
------

 1 warning found (use --debug to expand):
 - InvalidDefaultArgInFrom: Default value for ARG ${BUILDER_IMG} results in empty or invalid base image name (line 9)
Dockerfile.podvm_binaries.fedora:9
--------------------
   7 |     ARG BUILDER_IMG
   8 |     
   9 | >>> FROM ${BUILDER_IMG} AS podvm_builder
  10 |     
  11 |     ARG CLOUD_PROVIDER
--------------------
ERROR: failed to solve: fedora-binaries-builder-s390x: failed to resolve source metadata for docker.io/library/fedora-binaries-builder-s390x:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
The `fedora-binaries-builder-s390x` image is built in the previous step, so I guess there is an issue with docker contexts or something where the image can't be found locally anymore, hence looking on docker hub?

**Comment by stevenhorsman** [comment]
cc @BbolroC @genjuro214

**Comment by stevenhorsman** [comment]
It looks like buildkit v0.15.0 that released two weeks ago added `InvalidDefaultArgInFrom` validation: https://github.com/moby/buildkit/releases/tag/v0.15.0, so that is probably the reason it is failing now?

**Comment by stevenhorsman** [comment]
@BbolroC - not urgent, but it would be interesting to check if the local image is present and if there are any more clue on the s390x runner - if that's possible?

**Comment by BbolroC** [comment]
Yes, the image is present:

```
$ docker images
REPOSITORY                      TAG               IMAGE ID       CREATED         SIZE
fedora-binaries-builder-s390x   latest            e5bd625a7aab   2 minutes ago   3.56GB
moby/buildkit                   buildx-stable-1   47bee0bebd30   13 days ago     214MB
```

I got the same CI failure on my runner. I will dig into it a little bit and raise a PR to resolve this. Thanks!

**Comment by huoqifeng** [comment]
Thanks! @BbolroC CC @liudalibj
