### ISSUE TITLE
Integrate pause container image in pod VM image

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#196]
Pause container image is now embedded in the rootfs image of the upstream Kata Containers.

https://github.com/kata-containers/kata-containers/issues/4768

We also need to embed a pause image in the pod VM image.

**Comment by bpradipt** [comment]
> Pause container image is now embedded in the rootfs image of the upstream Kata Containers.
> 
> [kata-containers/kata-containers#4768](https://github.com/kata-containers/kata-containers/issues/4768)
> 
> We also need to embed a pause image in the pod VM image.

@yoheiueda is it really needed for peer-pods ? I understand this is needed when not using peer-pods, till complete support for image. offload is available in containerd/crio.

**Comment by yoheiueda** [comment]
@bpradipt 

The current kata-agent always use the embedded pause image, when PullImage is called for pause image.

https://github.com/kata-containers/kata-containers/blob/55c8c7226d0b81d383e609c7a5a7f3da5652313b/src/agent/src/image_rpc.rs#L239-L240

If a pause image is not embedded, PullImage fails with error message `Pause image not present in rootfs`.
https://github.com/kata-containers/kata-containers/blob/55c8c7226d0b81d383e609c7a5a7f3da5652313b/src/agent/src/image_rpc.rs#L155

So, fixing it requires to modify kata-agent to make the feature optional.

**Comment by bpradipt** [comment]
> @bpradipt
> 
> The current kata-agent always use the embedded pause image, when PullImage is called for pause image.
> 

Ah :-(.. Adds more dependencies for the VM image.

Anyways, looks like this need to be addressed within kata-containers and currently we have to live with it. 
@yoheiueda, thanks for the clarification.

**Comment by yoheiueda** [comment]
@bpradipt can you also apply this change to VM images for other platforms such as AWS? Do I need to reopen this issue, or will you open another issue?
