### ISSUE TITLE
Replace AA_KBC_PARAMS after enable initdata 

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#1985]
initdata is enabled in https://github.com/confidential-containers/cloud-api-adaptor/issues/1895 via https://github.com/confidential-containers/cloud-api-adaptor/pull/1912 and we're still keeping `AA_KBC_PARAMS` approach. Initdata will not take effect if `AA_KBC_PARAMS` set. 

In this story, we'll

  - [x] Add the kbs e2e tests to use initdata
      - [x] Migrate existing test cases 
      - [ ] Considering use KBS cert
      - [ ] Considering measurements/runtime_data checks for initdata.digest.
          - [ ] Requires reconcile with upstream for digest comparing for TEE drivers
  - [x] Remove the AA_KBC_PARAMS logic
  - [x] Adjust documentation
  - [x] Providing default initData via configMap to improve the UX
         https://github.com/confidential-containers/cloud-api-adaptor/pull/2006#issuecomment-2295728211

**Comment by huoqifeng** [comment]
CC @mkulke @stevenhorsman @liudalibj @bpradipt

**Comment by huoqifeng** [comment]
@bpradipt @mkulke I noticed that the `TEST_TRUSTEE_OPERATOR` is used to test `TestTrusteeOperatorKeyReleaseForSpecificKey` for a pre-configured cluster in azure. Does the TrusteeOperator support https now? Considering the complexity when enable https in KBS, I think maybe we should use `TrusteeOperator` to test KBS https and the certificates in aa.toml and cdh.toml which will be passed in by initdata.  wdyt?

**Comment by bpradipt** [comment]
> @bpradipt @mkulke I noticed that the `TEST_TRUSTEE_OPERATOR` is used to test `TestTrusteeOperatorKeyReleaseForSpecificKey` for a pre-configured cluster in azure. Does the TrusteeOperator support https now? Considering the complexity when enable https in KBS, I think maybe we should use `TrusteeOperator` to test KBS https and the certificates in aa.toml and cdh.toml which will be passed in by initdata. wdyt?

I used CA signed certificates with TrusteeOperator, however I think we should be able to use self-signed certificates as well. Let me know if you need any help.

**Comment by huoqifeng** [comment]
> I used CA signed certificates with TrusteeOperator, however I think we should be able to use self-signed certificates as well. Let me know if you need any help.

OK, I think e2e test will use self-signed certificate. I'll add it.

**Comment by stevenhorsman** [comment]
KBS cert depends on the KBS repo for support, but we can split this out into a separate issues for clarity if we want to test this in peer pods at all (rather than leave it to the attestation - kbs testing to cover).
