### ISSUE TITLE
While running CAA for provider libvirt getting Unsupported cloud provider error 

### ISSUE THREAD

**Issue by rafsal-rahim** [confidential-containers/cloud-api-adaptor#2032]
### Describe the bug

Encountering `Unsupported cloud provider` error while using CAA image with any tag other than `latest` in daemonset peerpodconfig-ctrl-caa-daemon

```
2024/09/09 12:01:13 [adaptor/cloud] Cloud provider external plugin loading is disabled, skipping plugin loading
cloud-api-adaptor: Unsupported cloud provider: libvirt

Usage: cloud-api-adaptor <provider-name> [options] | help | version

Supported cloud providers are:
	ibmcloud
	vsphere
	gcp
	azure
	aws

Use "cloud-api-adaptor <provider-name> -help" to show options for a cloud provider
```

### How to reproduce

- kubectl edit ds/peerpodconfig-ctrl-caa-daemon -n openshift-sandboxed-containers-operator
-  change CAA image to `latest-s390x` or any commit id

### CoCo version information

na

### What TEE are you seeing the problem on

None

**Comment by stevenhorsman** [comment]
Hi Rafsal, I think that part of this (the default image) should be helped by https://github.com/confidential-containers/cloud-api-adaptor/pull/2004, which I created a few weeks ago. I'm trying to understand the other part of this:
`latest-s390x` is not working. IIUC `latest-s390x` is a release build, not a dev build, so doesn't have libvirt support in. If you pick dev-6cf36c1a802ac61bc3ca5529828d4cea41c6a6b7-s390x then `libvirt` should work.

**Comment by rafsal-rahim** [comment]
sure thanks @stevenhorsman will check.
