### ISSUE TITLE
Add github action to build container image for cloud-api-adaptor

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#205]

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
@knrt10 assigning this issue to you based on your comment above.

@ariel-adam this is a relevant issue.

**Comment by ariel-adam** [comment]
Added the issue to the CoCo releases project drop V0.2.0 priority medium
