### ISSUE TITLE
Archive unmaintained repositories

### ISSUE THREAD

**Issue by mythi** [confidential-containers/cloud-api-adaptor#2145]
### Describe the bug

It looks the following repositories are no longer maintained since the code is moved to this repo:
https://github.com/confidential-containers/peerpodconfig-ctrl
https://github.com/confidential-containers/cloud-providers
https://github.com/confidential-containers/peerpod-ctrl

Can they be archived?

### How to reproduce

Observe repository activity and notice no updates in 9+months.

### CoCo version information

cloud-api-adaptor HEAD

### What TEE are you seeing the problem on

None

**Comment by stevenhorsman** [comment]
Sure, I will action this now.

**Comment by stevenhorsman** [comment]
Hey @mythi - we had a chat on the peer pods community call and agreed that we don't need these repos at all, so I've since deleted them to avoid any archived cluster. Thanks for bringing it to our attention.
