### ISSUE TITLE
Enable operator installation for IBM Cloud

### ISSUE THREAD

**Issue by inatatsu** [confidential-containers/cloud-api-adaptor#240]
It is convenient that the operator supports installation on IBM Cloud. Potential work items are:

- [x] Providing a kustomize overlay for IBM Cloud
- [ ] Enable multi-architecture (i.e. amd64 and s390x) artifacts for installation

Any other?

**Comment by stevenhorsman** [comment]
FYI - I have issue https://github.com/confidential-containers/operator/issues/107 to cover getting the coco operator working with s390x. Once that is done (and depending on how). I guess we might need to update the cloud-api-adaptor payload build to base on the new multi-arch image, or have a separate s390x version of the build?

**Comment by jtumber-ibm** [comment]
This has been completed with the multiarch work finished.
