### ISSUE TITLE
Pod IP is unreachable when Calico VXLAN mode is set to Always

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#244]
When pod network is set up with Calico, and its inter-node communication is configured to use VXLAN, the pod IP on a pod VM is unreachable from the worker node.

```
# curl http://172.20.189.195
curl: (7) Failed to connect to 172.20.189.195 port 80: No route to host
```

This problem does not occur with Flannel even though Flannel also uses VXLAN.

The used VXLAN IDs (VNIs) are as follows, so there are no conflicts.

| | VXLAN ID |
| --- | --- |
| Peer Pod | 555000 |
| Calico VXLAN | 4096 |
| Flannel | 1 |

**Comment by yoheiueda** [comment]
There are iptables rules set by Calico to drop VXLAN packets.

```
-A cali-INPUT -p udp -m comment --comment "cali:MYAij0dXtIVCOZ-i" -m comment --comment "Allow IPv4 VXLAN packets from whitelisted hosts" -m multiport --dports 4789 -m set --match-set cali40all-vxlan-net src -m addrtype --dst-type LOCAL -j ACCEPT
-A cali-INPUT -p udp -m comment --comment "cali:c3JpWekSTKWcdGH0" -m comment --comment "Drop IPv4 VXLAN packets from non-whitelisted hosts" -m multiport --dports 4789 -m addrtype --dst-type LOCAL -j DROP
-A cali-OUTPUT -p udp -m comment --comment "cali:gPT-T3DOftxv-f7s" -m comment --comment "Allow IPv4 VXLAN packets to other whitelisted hosts" -m multiport --dports 4789 -m addrtype --src-type LOCAL -m set --match-set cali40all-vxlan-net dst -j ACCEPT
```

I manually added pod VM IP address by executing the following command, but the added IP address immediately deleted.

```
ipset add cali40all-vxlan-net 10.244.65.74
```

**Comment by yoheiueda** [comment]
A possible workaround of this issue is to use another UDP port for VXLAN packets.

**Comment by yoheiueda** [comment]
I confirmed that changing the UDP port fixes the connectivity issue.

**Comment by yoheiueda** [comment]
Another workaround is to add an iptables rule that explicitly allows VXLAN packets by peer pod tunnels.

Calico's configuration parameter `chainInsertMode`  is set to `Insert` by default. This feature always keeps the Calico rules ahead of the other rules. So, we need to turn this feature off to add a rule that permits peer pod VXLAN packets.

https://projectcalico.docs.tigera.io/reference/resources/felixconfig
https://github.com/projectcalico/calico/blob/v3.24.1/felix/iptables/table.go#L1179-L1190

**Comment by huoqifeng** [comment]
> A possible workaround of this issue is to use another UDP port for VXLAN packets.

@yoheiueda do you mean a separate VxLAN UDP port for peerpod? if it does not require calico config change, I think it's preferred.

**Comment by yoheiueda** [comment]
> > A possible workaround of this issue is to use another UDP port for VXLAN packets.
> 
> @yoheiueda do you mean a separate VxLAN UDP port for peerpod? if it does not require calico config change, I think it's preferred.

I am working of making VXLAN UDP port in cloud-api-adaptor configurable. Then, we can use a different VXLAN port in cloud-api-adaptor, while we are using the default VXLAN port in Calico.

**Comment by jepio** [comment]
Thanks for chasing this down @yoheiueda, we hit the same issue when implementing Azure support.

If calico does not want to change their behavior then it would be good to change the default vxlan port so that we don't have to pass a custom port in every provider.
