### ISSUE TITLE
Invalid bundle path is generated due to a pull request by the custom containerd

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#259]
The protobuf definition of PullImageRequest in the custom containerd for CCv0 does not contain a container ID.

https://github.com/confidential-containers/containerd/blob/4b12e77e79dccebba54e0ec91cc24d6a51a85fa6/runtime/v2/task/image.proto#L28-L31
```
message PullImageRequest {
    // Name of the image.
    string image = 1;
}
```

So, the CRI plugin does not send a container ID in a PullImageRequest.

https://github.com/confidential-containers/containerd/blob/4b12e77e79dccebba54e0ec91cc24d6a51a85fa6/pkg/cri/services/cc/service.go#L989-L992
```
	req := &task.PullImageRequest{}
	if r.Image != nil {
		req.Image = r.Image.Image
	}
```

The protobuf definition of PullImageRequest in the  CCv0 `kata-agent` **does** contain a container ID.

https://github.com/kata-containers/kata-containers/blob/8ad86e2ec9d26d2ef07f3bf794352a3fda7597e5/src/libs/protocols/protos/image.proto#L18-L25
```
message PullImageRequest {
    // Image name (e.g. docker.io/library/busybox:latest).
    string image = 1;
    // Unique image identifier, used to avoid duplication when unpacking the image layers.
    string container_id = 2;
    // Use USERNAME[:PASSWORD] for accessing the registry
    string source_creds = 3;
}
```

But, `kata-shim` does **not** send a container ID to `kata-agent`.

https://github.com/kata-containers/kata-containers/blob/8ad86e2ec9d26d2ef07f3bf794352a3fda7597e5/src/runtime/virtcontainers/kata_agent.go#L2284-L2286
```
	r := &grpc.PullImageRequest{
		Image: req.Image,
	}
```

The CCv0 `kata-agent` behaves differently based on whether a container ID is supplied or not.

When a container ID is not supplied, the image name is used as a container ID.

https://github.com/kata-containers/kata-containers/blob/8ad86e2ec9d26d2ef07f3bf794352a3fda7597e5/src/agent/src/image_rpc.rs#L226-L236
```
        if cid.is_empty() {
            let v: Vec<&str> = image.rsplit('/').collect();
            if !v[0].is_empty() {
                // ':' have special meaning for umoci during upack
                cid = v[0].replace(':', "_");
            } else {
                return Err(anyhow!("Invalid image name. {}", image));
            }
        } else {
            verify_cid(&cid)?;
        }
```

Then, a container image bundle path is generated from the container ID as follows.

https://github.com/kata-containers/kata-containers/blob/8ad86e2ec9d26d2ef07f3bf794352a3fda7597e5/src/agent/src/image_rpc.rs#L285
```
            let bundle_path = Path::new(CONTAINER_BASE).join(&cid);
```

The `cloud-api-adaptor` sends a PullImageRequest with a container ID just before sending a CreateContainerRequest.

https://github.com/confidential-containers/cloud-api-adaptor/blob/241448c33e983a49ebb3af8d9c296394149ad058/pkg/adaptor/proxy/service.go#L125-L128
```
		pullImageReq := &pb.PullImageRequest{
			Image:       imageName,
			ContainerId: req.ContainerId,
		}
```

If the custom containerd sends a PullImageRequest before sending CreateContainerRequest, kata-agent recieves two PullImageRequests. One without a contiaierID and another one with a container ID. This behavior confuses `kata-agent`,and causes the following error.

```
2022/09/26 07:40:20 [adaptor/proxy] CreateContainer: calling PullImage for "nginx:latest" before CreateContainer
2022/09/26 07:40:22 [adaptor/proxy] CreateContainer: successfully pulled image "nginx:latest"
2022/09/26 07:40:22 [adaptor/proxy] CreateContainer fails: rpc error: code = Internal desc = load image bundle

Caused by:
    No such file or directory (os error 2)
```

**Comment by yoheiueda** [comment]
@huoqifeng This issue is related to https://github.com/kata-containers/kata-containers/issues/4785

**Comment by yoheiueda** [comment]
Another problem is that containerd does not send an image name with annotation "io.kubernetes.cri.image-name" for pause containers, so a PullImageRequest to kata-agent must have a container ID in it.

https://github.com/kata-containers/kata-containers/blob/8ad86e2ec9d26d2ef07f3bf794352a3fda7597e5/src/agent/src/rpc.rs#L694-L696
```
        if let Some(image_name) = container_oci
            .annotations
            .get(&ANNO_K8S_IMAGE_NAME.to_string())
```

**Comment by bpradipt** [comment]
@yoheiueda if I understand correctly this is an issue only when using custom containerd with CAA and not using regular containerd ? Or with latest CCv0 the issue is there with regular containerd also ?

**Comment by yoheiueda** [comment]
I think this issue does not occur when a regular conatinerd is used.

**Comment by yoheiueda** [comment]
@bpradipt I confirmed that this issue does NOT occur when a pod VM image with skopeo installed.

So, fixing this issue wil be necessary when we remove skopoe and omoci from our pod VM image.
