### ISSUE TITLE
Parameterise pause image

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#268]
Currently the pause image is hard-coded which creates a problem when using CAA with a different kubernetes distribution with alternative pause image. For example OpenShift uses a different pause image with the binary named as `pod` instead of `pause` and CAA fails to work.

**Comment by yoheiueda** [comment]
@bpradipt kata-agent recognizes a pause image based on whether its name is `"pause"` or not.

Does the pause image of OpenShift have such a name?

https://github.com/kata-containers/kata-containers/blob/8ad86e2ec9d26d2ef07f3bf794352a3fda7597e5/src/agent/src/image_rpc.rs#L239-L241
```
        let v: Vec<&str> = image.rsplit('/').collect();
        if !v[0].is_empty() && v[0].starts_with("pause:") {
            Self::unpack_pause_image(&cid)?;
```
