### ISSUE TITLE
Plan to get peer-pods support as part of a coco release

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#271]
We want to work out what steps we need to take to have peer pods form part of a future CoCo release. It might be that we just tag a commit that lines up with the release to start with and have the CoCo release notes link to docs in this repo, but it would be good to get in as a feature and be able to create clouds-api-adaptor images that line up with the release.
This probably requires us to have some CI test for all the platforms we want to support, so we might need to incrementally add cloud providers with different releases.

**Comment by stevenhorsman** [comment]
We discussed this topic in the [peer pods community call](https://docs.google.com/document/d/1QtiOpSavz177Nq3jwzjQ5vvZjquOT7tFs9XBplNeC-o/edit#heading=h.lh1kp3a4hrla) on 11th Jan and are currently aiming for the CoCo 0.4 release. There was a candidate list of features discussed there.

**Comment by bpradipt** [comment]
This is currently aimed for 0.5.0 release.

**Comment by bpradipt** [comment]
This is completed.
