### ISSUE TITLE
ibmcloud: Handle long cluster/namespace names better

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#287]
At the moment we create an instance with the format <kubernetes-node-name>-<namespace>-<pod>-<first 8 chars of sandbox id>. 

An ibmcloud VSI instance has a max name length of 63 chars, so at the moment we can support creating VMs for scenarios where the node name, namespace and pod have a total length of <=51 characters. If we try and create one longer than this we get an invalid payload error:
```
2022/10/10 13:55:44 [helper/hypervisor] create a sandbox 5691f5a2d3bfea7b340793f43268f1e30ba6d36faea35fa12842fd2714979c8f for pod nginx in namespace a-namespace-that-is-very-long-and-62-characters-long-in-total (netns: /var/run/netns/cni-f1e07465-03cd-95bc-f2b8-090cdf4b65d6)
2022/10/10 13:55:44 [helper/hypervisor] StartVM: vmName: "peer-pod-cluster-worker-a-namespace-that-is-very-long-and-62-characters-long-in-total-nginx-5691f5a2"
2022/10/10 13:55:44 [helper/hypervisor] store daemon.json at /run/peerpod/pods/5691f5a2d3bfea7b340793f43268f1e30ba6d36faea35fa12842fd2714979c8f
2022/10/10 13:55:44 [helper/hypervisor] failed to create an instance : Invalid json payload provided and the response is {
    "StatusCode": 400,
    "Headers": {
        "Cache-Control": [
            "max-age=0, no-cache, no-store, must-revalidate"
        ],
        "Cf-Cache-Status": [
            "DYNAMIC"
        ],
        "Cf-Ray": [
            "757fdaf8cb6ba1e4-YYZ"
        ],
        "Content-Length": [
            "162"
        ],
        "Content-Type": [
            "application/json; charset=utf-8"
        ],
        "Date": [
            "Mon, 10 Oct 2022 13:55:44 GMT"
        ],
        "Expires": [
            "-1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "cloudflare"
        ],
        "Strict-Transport-Security": [
            "max-age=31536000; includeSubDomains"
        ],
        "X-Content-Type-Options": [
            "nosniff"
        ],
        "X-Request-Id": [
            "429727de-f378-4c8f-9a78-bb895105cfb5"
        ],
        "X-Xss-Protection": [
            "1; mode=block"
        ]
    },
    "Result": {
        "errors": [
            {
                "code": "bad_field",
                "message": "Invalid json payload provided",
                "target": {
                    "name": "name",
                    "type": "field"
                }
            }
        ],
        "trace": "429727de-f378-4c8f-9a78-bb895105cfb5"
    },
    "RawResult": null
}
```
I think there are a couple of things we could do about this
- firstly providing a nicer error, or flowing back the ibmcloud api's error message would be helpful in seeing what went wrong
- Can we provide some truncation system where we ensure that the total of node name, namespace and pod name have a length <=51 chars automatically? I think due to the sandbox id there shouldn't be a big risk of clashes, so we'd just want to pick something sensible to make it most obvious to a user which pod the VM maps to, so probably prioritising preserving pod name over node name and namespace if we auto truncate is the best approach?

**Comment by mkulke** [comment]
the azure adaptor has a similar problem. maybe namespace, etc can be put into tags?

**Comment by bpradipt** [comment]
We can truncate the VM name to specific length in the following [method](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/util/hvutil/hvutil.go#L42) and add the details like namespace, worker node etc into tags.

**Comment by yoheiueda** [comment]
OK. Let's use the concatenation of (1) prefix `podvm`, (2)  pod name, and (3) sandbox ID.

Currently, VM name generation is done in a common method, but adding tags is specific to each cloud provider.

I'll first create a PR for fixing the VM name generation, and then will create a PR for IBM cloud.

Any volunteers for the other cloud providers?

**Comment by bpradipt** [comment]
@yoheiueda I'll make the changes for aws and libvirt. Will need to understand for @caavery on tagging resources in vsphere.
Hope @mkulke @knrt10 or @surajssd can take care of the changes for azure

**Comment by knrt10** [comment]
Sure. I can work on that

**Comment by surajssd** [comment]
Matching node-name and vm-name is for human readability. But it does not have to be like that! We can have a custom name mapping?

Just truncating will solve the problem, but then how we truncate will give us multiple VMs that have similar looking names. That destroys the whole purpose of naming for human readability.

But if we are willing to give up the human readability part, we can devise a method of naming that removes the need to truncate names. We can use the pod uuids as machine names.

**Comment by mkulke** [comment]
yup, `metadata.uid` should yield a predictable length string and still make it easy to correlate vms to pods.

**Comment by jtumber-ibm** [comment]
@stevenhorsman I think this was fixed awhile back, happy to close?
