### ISSUE TITLE
Deleting the CAA pod does not result in shutdown being called

### ISSUE THREAD

**Issue by caavery** [confidential-containers/cloud-api-adaptor#289]
kubectl delete of the CAA pod does not issue a SIGTERM and as a result the shutdown routine is never invoked.

**Comment by caavery** [comment]
Please assign this to Snir Sheriber

**Comment by bpradipt** [comment]
@snir911 would be great to have your views on this. The entrypoint.sh script might require changes to handle SIGTERM.

**Comment by snir911** [comment]
Thanks, I'll have a look next week
