### ISSUE TITLE
CAA pods should run as Daemonset?

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#293]
I see that the current deployment model of CAA is using Deployment. But shouldn't they run as daemonset?

Of course we can influence the scheduling based on the node affinity and taints / tolerations. But what is the use case of running two pods on the same node?

**Comment by bpradipt** [comment]
Initially the intent was to just run a single instance of CAA as a deployment and scale it to additional PODs running on different worker nodes if needed.  Afaik, there is no use case of running two CAA pods on the same node.

We have been thinking about switching to daemonset.  In fact @jensfr had also highlighted this earlier about using daemonset.

We just need to do it :-)

**Comment by knrt10** [comment]
I can work on this, if it's okay @surajssd?
