### ISSUE TITLE
Image building fails with `files/usr/bin/skopeo: not found`

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#295]
With the current `staging` HEAD building image fails with error: `/bin/sh: 1: files/usr/bin/skopeo: not found`.

I think this was introduced after in https://github.com/confidential-containers/cloud-api-adaptor/pull/263.

### Reproduce

```bash
git clone https://github.com/kata-containers/kata-containers -b CCv0
git clone https://github.com/confidential-containers/cloud-api-adaptor.git

cd cloud-api-adaptor/azure/image/
export CLOUD_PROVIDER=azure
```

```console
# make build
cd "../.." && make agent-protocol-forwarder
make[1]: Entering directory '/root/foobar/cloud-api-adaptor'
CGO_ENABLED=0 go build -tags=azure -o "agent-protocol-forwarder" "cmd/agent-protocol-forwarder/main.go"
...
...
   Compiling oci-distribution v0.8.1 (https://github.com/krustlet/oci-distribution?rev=1ba0d94a900a97aa1bcac032a67ea23766bcfdef#1ba0d94a)
   Compiling image-rs v0.1.0 (https://github.com/confidential-containers/image-rs?rev=a1d7ba31201d9d7a575d05c5fed1f2cb2142a842#a1d7ba31)
   Compiling kata-agent v0.1.0 (/root/foobar/kata-containers/src/agent)
    Finished release [optimized] target(s) in 5m 44s
make[1]: Leaving directory '/root/foobar/kata-containers/src/agent'
install -D --compare "../../../kata-containers/src/agent/target/x86_64-unknown-linux-musl/release/kata-agent" "files/usr/local/bin/kata-agent"
files/usr/bin/skopeo --policy "files/etc/containers/policy.json" copy "docker://k8s.gcr.io/pause:3.6" "oci:pause:3.6"
/bin/sh: 1: files/usr/bin/skopeo: not found
make: *** [Makefile:117: pause] Error 127
```

Same can be reproduced for `aws`.

**Comment by knrt10** [comment]
I can also reproduce this issue

**Comment by knrt10** [comment]
I think it is due to [azure/image/Makefile#L97-L119](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/azure/image/Makefile#L97-L119). PAUSE, SKOPEO and UMOCI_SRC should also only build when `USE_SKOPEO` is defined. I can make a PR for the same

**Comment by surajssd** [comment]
I think there are two things happening there.
- One aspect is not using skopeo in the guest. Which is replaced by image-rs. Which is solved with the PR.
- But it seems that we still need skopeo locally on the build machine for the pause image copying.

So we need to provide a mechanism where we build skopeo but we don't put it in the VM. And I think `USE_SKOPEO` is meant to put the binary inside the VM.

**Comment by yoheiueda** [comment]
@knrt10 @surajssd Thank you for the investigation.

Makefile for IBM Cloud does not have this problem, since pause image is prepared as follows.

https://github.com/confidential-containers/cloud-api-adaptor/blob/6f798ee679b4a8a80f28d190608e0dba3ac37770/ibmcloud/image/Makefile#L120-L124

I forgot to modify this change for Azure, AWS, and Libvirt by mistake.

I'll submit a PR to fix this.
