### ISSUE TITLE
azure, aws: `IMAGE_NAME` env var is never used

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#300]
`IMAGE_NAME` is set but it is never set to the image name. 

### Azure

It is defined here:

https://github.com/confidential-containers/cloud-api-adaptor/blob/f975b7687faa3ecef7368472b607f436372be47d/azure/image/Makefile#L19-L30

But then while creating the image something else is used:

https://github.com/confidential-containers/cloud-api-adaptor/blob/f975b7687faa3ecef7368472b607f436372be47d/azure/image/Makefile#L81

### AWS

It is defined here:

https://github.com/confidential-containers/cloud-api-adaptor/blob/f975b7687faa3ecef7368472b607f436372be47d/aws/image/Makefile#L19-L30

But then while creating the image something else is used:

https://github.com/confidential-containers/cloud-api-adaptor/blob/f975b7687faa3ecef7368472b607f436372be47d/aws/image/Makefile#L79

**Comment by knrt10** [comment]
yes, I think we can remove this code
