### ISSUE TITLE
All secrets are visible in the container log of CAA POD

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#313]
The entrypoint.sh uses `set -x` which prints all the secrets in the container log negating the redaction used in the cloud-api-adaptor binary.
This should be removed.

@jtumber-ibm, any other thoughts from you ?

**Comment by jtumber-ibm** [comment]
We should be able to remove the sensitive args from entrypoint.sh cloud-api-adaptor call.

i.e. 
```
cloud-api-adaptor-ibmcloud ibmcloud \
        -api-key "${IBMCLOUD_API_KEY}" \
        -iam-service-url "${IBMCLOUD_IAM_ENDPOINT}" \
```
`-api-key` option shouldn't be required anymore as it should get the correct value from `IBMCLOUD_API_KEY` env var now. Same should be true for the other providers.
