### ISSUE TITLE
Common Makefile for podvm image build across providers

### ISSUE THREAD

**Issue by jtumber-ibm** [confidential-containers/cloud-api-adaptor#314]
Currently each provider has their own `Makefile` in their respective image folders. The vast majority of the contents in these files is identical. Only changes between `aws` and `azure` is packer variables, `libvert` includes a couple extras e,g, `UBUNTU_IMAGE_URL` and `ibmcloud` has a few extra targets to push and verify. But the rest is the same.

Could this be refactored to avoid duplication and improve the onboarding for future providers? 

For example azure could become just...

```make
# Not certain where the common one would be stored
include ../Makefile

build: $(IMAGE_FILE)

$(IMAGE_FILE): $(BINARIES) $(FILES)
	mkdir -p toupload
	packer build -var client_id=${CLIENT_ID} \
		-var client_secret=${CLIENT_SECRET} \
		-var subscription_id=${SUBSCRIPTION_ID} \
		-var tenant_id=${TENANT_ID} \
		-var location=${LOCATION} \
		-var vm_size=${VM_SIZE} \
		-var resource_group=${RESOURCE_GROUP} \
		-var az_image_name=${IMAGE_NAME} .
	rm -fr toupload
```

and aws

```make
# Not certain where the common one would be stored
include ../Makefile

build: $(IMAGE_FILE)

$(IMAGE_FILE): $(BINARIES) $(FILES)
	mkdir -p toupload
	packer build -var vpc_id=${VPC_ID} \
		-var subnet_id=${SUBNET_ID} \
		-var account_id=${AWS_ACCOUNT_ID} \
		-var region=${AWS_REGION} \
		-var instance_type=${INSTANCE_TYPE} \
		-var ami_name=${IMAGE_NAME} .
	rm -fr toupload
```

**Comment by jtumber-ibm** [comment]
I'd like to propose a restructure of the current layout. Just including the files related to the VM image build

**Presently**

```
.
|-- aws
|   |-- image
|   |   |-- files
|   |   |-- Makefile
|   |   |-- aws-ubuntu.pkr.hcl
|   |   |-- copy-files.sh
|   |   `-- variables.pkr.hcl
|   `-- README.md
|-- azure
|   |-- image
|   |   |-- files
|   |   |-- Makefile
|   |   |-- azure-ubuntu.pkr.hcl
|   |   |-- copy-files.sh
|   |   `-- variables.pkr.hcl
|   `-- README.md
|-- docs
|   |-- DEVELOPMENT.md
|   |-- addnewprovider.md
|   |-- architecture.png
|   `-- vminfo.md
|-- ibmcloud
|   |-- demo
|   |   `-- ...
|   |-- image
|   |   |-- files
|   |   |-- Makefile
|   |   |-- build.sh
|   |   |-- delete.sh
|   |   |-- login.sh
|   |   |-- multipart_upload.sh
|   |   |-- push.sh
|   |   `-- verify.sh
|   |-- terraform
|   |   `-- ...
|   |-- README.md
|   `-- TROUBLESHOOTING.md
|-- libvirt
|   |-- image
|   |   |-- files
|   |   |-- Makefile
|   |   |-- copy-files.sh
|   |   |-- qemu-ubuntu.pkr.hcl
|   |   |-- userdata.cfg
|   |   `-- variables.pkr.hcl
|   `-- README.md
|-- ...
```

proposal 

```
.
|-- image
|   |-- aws
|   |   |-- files
|   |   |-- Makefile
|   |   |-- aws-ubuntu.pkr.hcl
|   |   |-- copy-files.sh
|   |   |-- README.md
|   |   `-- variables.pkr.hcl
|   |-- azure
|   |   |-- files
|   |   |-- Makefile
|   |   |-- azure-ubuntu.pkr.hcl
|   |   |-- copy-files.sh
|   |   |-- README.md
|   |   `-- variables.pkr.hcl
|   |-- ibmcloud
|   |   |-- demo
|   |   |   `-- ...
|   |   |-- terraform
|   |   |   `-- ...
|   |   |-- files
|   |   |-- Makefile
|   |   |-- build.sh
|   |   |-- delete.sh
|   |   |-- login.sh
|   |   |-- multipart_upload.sh
|   |   |-- push.sh
|   |   `-- verify.sh
|   |-- libvirt
|   |   |-- files
|   |   |-- Makefile
|   |   |-- copy-files.sh
|   |   |-- qemu-ubuntu.pkr.hcl
|   |   |-- userdata.cfg
|   |   |-- README.md
|   |   `-- variables.pkr.hcl
|   `-- Makefile (common)
|-- ...
```

**Comment by stevenhorsman** [comment]
Thanks @jtumber-ibm - that makes sense to me. One of the line items I had in my peer pod futures yesterday was ‘Refactor to reduce duplication in code base between cloud providers’ and this falls straight into this category.

My only suggestion would be that the ibmcloud directory has a whole load of extra stuff (terraform, demo scripts etc.), so I think it might make sense to continue to have it as a top level folder rather than it going under the image one. The fact that the peer pod vm image creation is pretty much decoupled from the rest of it means that shouldn’t be too much of a problem and might be neater?

@bpradipt - does this suggestion work okay for you with the other cloud-providers?

**Comment by bpradipt** [comment]
@jtumber-ibm  it definitely makes sense to use a common Makefile across the providers for podvm image generation.
I like the idea of having everything under a single top level `image` directory. 

Further, @stevenhorsman makes a valid point. The terraform code for ibmcloud should not be under the `image` directory.

**Comment by bpradipt** [comment]
Also can the `files` directory and helper scripts like copy-files.sh be also moved to top-level `image` directory to avoid duplicating it across the providers ?  
Only the packer configs are different for different providers, rest is common. So imho we can just keep the packer and related configs separate and move everything else under a common directory

**Comment by yoheiueda** [comment]
I agree with the restructure.

Makefile for IBM Cloud should only have targets specific to IBM Cloud, and needs to reuse targets in targets defined in the common Makefile.

I think we can also use prebuild binaries for skopeo/umoci.  Prebuild binaries for IBM Cloud s390x are not available, so only Makefile for IBM Cloud needs to have the rules to build the binaries from source code.

**Comment by jtumber-ibm** [comment]
So like this, @bpradipt @stevenhorsman  ?

```
|-- image
|   |-- files
|   |-- Makefile
|   |-- copy-files.sh
|   `-- README.md
|-- aws
|   |-- Makefile
|   |-- aws-ubuntu.pkr.hcl
|   |-- README.md
|   `-- variables.pkr.hcl
|-- azure
|   |-- Makefile
|   |-- azure-ubuntu.pkr.hcl
|   |-- README.md
|   `-- variables.pkr.hcl
|-- ibmcloud
|   |-- demo
|   |   `-- ...
|   |-- terraform
|   |   `-- ...
|   |-- Makefile
|   |-- build.sh
|   |-- delete.sh
|   |-- login.sh
|   |-- multipart_upload.sh
|   |-- push.sh
|   `-- verify.sh
|-- libvirt
|   |-- Makefile
|   |-- qemu-ubuntu.pkr.hcl
|   |-- userdata.cfg
|   |-- README.md
|   `-- variables.pkr.hcl
```

**Comment by huoqifeng** [comment]
Sounds e2e test scripts could also be common used like `libvirt/install_operator.sh` in PR https://github.com/confidential-containers/cloud-api-adaptor/pull/345/files with slightly change, I guess test cases would even common. @wainersm

**Comment by wainersm** [comment]
Hi @jtumber-ibm !

I just glanced at your PR but decided to make some comments here. Sorry for being late at this party :)

So stuffs I will say below are just nitpicking and can be ignored at your discretion.
 
> So like this, @bpradipt @stevenhorsman ?
> 
> ```
> |-- image
> |   |-- files
> |   |-- Makefile
> |   |-- copy-files.sh
> |   `-- README.md

Here I would change two things:
 * rename `image` to `podvm_common` (or something better). In this cloud/k8s/container world when I read `image` my brain immediately associate with container image. I added `common` to express that is common to other parts, not sure this is a good idea though.
 * rename `Makefile` to `Makefile.inc` so that one cannot run it; as it is meant to be included (so suffix `inc`). 

> |-- aws
> |   |-- Makefile
> |   |-- aws-ubuntu.pkr.hcl
> |   |-- README.md
> |   `-- variables.pkr.hcl
> |-- azure
> |   |-- Makefile
> |   |-- azure-ubuntu.pkr.hcl
> |   |-- README.md
> |   `-- variables.pkr.hcl
> |-- ibmcloud
> |   |-- demo
> |   |   `-- ...
> |   |-- terraform
> |   |   `-- ...
> |   |-- Makefile
> |   |-- build.sh
> |   |-- delete.sh
> |   |-- login.sh
> |   |-- multipart_upload.sh
> |   |-- push.sh
> |   `-- verify.sh

I like the idea of having a sub-folder here, named `podvm` so separate stuffs better. Also it implicitly gives meaning to some files like `build.sh` (to build what? the podvm? the VPC?).

> |-- libvirt
> |   |-- Makefile
> |   |-- qemu-ubuntu.pkr.hcl
> |   |-- userdata.cfg
> |   |-- README.md
> |   `-- variables.pkr.hcl
> ```
