### ISSUE TITLE
CI: add go fmt, go escapes detect checks in CI process

### ISSUE THREAD

**Issue by SamYuan1990** [confidential-containers/cloud-api-adaptor#320]
as title, I am not sure if we'd better add go fmt, go escapes detect  checks for this repo?

**Comment by SamYuan1990** [comment]
if yes, please assign this ticket to me, thanks.

**Comment by bpradipt** [comment]
tagging @wainersm @stevenhorsman for their comments

**Comment by huoqifeng** [comment]
@SamYuan1990 thanks for this. @wainersm and @stevenhorsman is working on CI related works.

**Comment by stevenhorsman** [comment]
Hi @SamYuan1990 - We have some basic linting that Wainer added in https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/.github/workflows/lint.yaml as you have probably seen, but if you can add things to improve the code consistency and readability then that sounds great. Thanks!

**Comment by SamYuan1990** [comment]
PR as #322
