### ISSUE TITLE
simplify entrypoint.sh

### ISSUE THREAD

**Issue by snir911** [confidential-containers/cloud-api-adaptor#326]
make it shorter will be easier to follow

**Comment by jtumber-ibm** [comment]
Hi @snir911 have you seen exposed secrets? Work has been done to remove these from logs and commands if you find more that have been missed we might need to remove them from other places not just entrypoint.sh

**Comment by snir911** [comment]
@jtumber-ibm, right i forgot about it, sorry, let me modify this issue
