### ISSUE TITLE
Using VM block device as container storage

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#338]
With Kata and local hypervisor we have the mechanism to use VM block device as container storage - 
https://github.com/confidential-containers/documentation/blob/main/quickstart.md#trusted-ephemeral-storage-for-container-images

This issue is a placeholder to have an equivalent mechanism when using the remote hypervisor approach

**Comment by bpradipt** [comment]
With remote hypervisor (cloud-api-adaptor) the VM is already having a block storage attached and the same can be used for storing the container images.  We don't really need any PV as is the case with local hypervisor (qemu/clh).

At a minimum we need a way to tell the kata-agent to not use `tmpfs` for unpacking the container images.

**Comment by bpradipt** [comment]
@yoheiueda @huoqifeng @stevenhorsman before I start looking at it further, wanted to check if you folks did any investigation ?

**Comment by huoqifeng** [comment]
> With remote hypervisor (cloud-api-adaptor) the VM is already having a block storage attached and the same can be used for storing the container images. We don't really need any PV as is the case with local hypervisor (qemu/clh).

@bpradipt do you mean the root disk in PeerPod for remote hypervisor case?

**Comment by stevenhorsman** [comment]
> Modifying the kata-agent.service definition should do the trick.

Hey Pradipta, I might be incorrect, but my understand is that image-rs downloads the layers to /run/image and the final unpacked image to `/run/kata-containers`, so maybe we need to mount bind that too?

**Comment by stevenhorsman** [comment]
FYI I did:
```
[Unit]
Description=Kata Agent
After=network.target

[Service]
ExecStart=/usr/local/bin/kata-agent --config /etc/agent-config.toml
# Download and unpack container images on the root disk
ExecStartPre=-mkdir -p /image /run/image
ExecStartPre=-+mount --bind /image /run/image
ExecStartPre=-mkdir -p /kata-containers /run/kata-containers
ExecStartPre=-+mount --bind /kata-containers /run/kata-containers
ExecStartPre=ip netns add podns
ExecStartPre=ip netns exec podns ip link set lo up
ExecStopPost=ip netns delete podns
# Now specified in the agent-config.toml Environment="KATA_AGENT_SERVER_ADDR=unix:///run/kata-containers/agent.sock"
SyslogIdentifier=kata-agent

[Install]
WantedBy=multi-user.target
```
and that seemed to do the trick:
```
df -h /run/image/
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        98G  3.5G   90G   4% /run/image
root@podvm-hpcs-servicemanager-deployment-8eb693fd:~# df -h /run/kata-containers/
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        98G  3.5G   90G   4% /run/kata-containers
```

**Comment by bpradipt** [comment]
Thanks a lot @stevenhorsman

**Comment by bpradipt** [comment]
This is from AWS pod vm
```
#  mount | grep -e image -e kata-containers
tmpfs on /run/kata-containers type tmpfs (rw,relatime,mode=755,inode64)
tmpfs on /run/kata-containers/shared/containers type tmpfs (rw,relatime,mode=755,inode64)
/dev/xvda1 on /run/image type ext4 (rw,relatime,discard)
/dev/xvda1 on /run/kata-containers type ext4 (rw,relatime,discard)
shm on /run/kata-containers/sandbox/shm type tmpfs (rw,relatime,inode64)
shm on /kata-containers/sandbox/shm type tmpfs (rw,relatime,inode64)
/dev/xvda1 on /run/kata-containers/c5cf97feb542a0a1030aa2abe4ffc64dd77153a8b74800942da5c7f27596e7fb/rootfs type ext4 (rw,relatime,discard)
/dev/xvda1 on /kata-containers/c5cf97feb542a0a1030aa2abe4ffc64dd77153a8b74800942da5c7f27596e7fb/rootfs type ext4 (rw,relatime,discard)
/dev/xvda1 on /run/kata-containers/d0be814b9389c2cd4782732c01e1f8557436c6824bef8bf58b8b9a059b15ad43/rootfs type ext4 (rw,relatime,discard)
/dev/xvda1 on /kata-containers/d0be814b9389c2cd4782732c01e1f8557436c6824bef8bf58b8b9a059b15ad43/rootfs type ext4 (rw,relatime,discard)
```

**Comment by knrt10** [comment]
cc @mkulke

**Comment by mkulke** [comment]
@stevenhorsman yup, we are observing the same issues. we have to look into the implications for disk encryption, but it's clear that the current setup is not practical. simple images like `library/perl` cannot be pulled/extracted on a 8GB instance. from my side: please go ahead and thanks for giving a heads up.
