### ISSUE TITLE
Support authenticated registries

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#344]
Currently following steps are required to support authenticated registry (thanks to @stevenhorsman )
* Create an auth.json file as per https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md and put it in your peer pod vm image in /root/.config/containers/auth.json
* Build the pod vm image with skopeo still included. 

Embedding the auth.json in the VM image or retrieving the auth.json via the attestation process is required to support confidential computing use case. However this also creates a practical problem when using CAA for pure container isolation cases. Consider the following use cases:
1. A customer getting started with CAA to try out isolated VM containers in the cloud for their workloads. Thereafter moving to confidential containers using the same underlying stack.
2. Having a simple development and test workflow for the stack.

Creating this issue to brainstorm how the standard K8s workflow of using `ImagePullSecrets` in the manifest can be accommodated.

cc @stevenhorsman @yoheiueda @liudalibj for your comments and guidance

**Comment by stevenhorsman** [comment]
@huoqifeng - I think you had a suggestion of using an init containers to talk to the kube api-server. I'm not sure if we need that for CC as we have the KBC, but maybe that approach could help with the nested sandbox case here?

**Comment by huoqifeng** [comment]
Not sure whether it suit for this case, the idea is we embed an init-container image in the PeerPod VM OS Image and inject the init-container for PeerPod. This init-container can be launched without pull image outside (as its embedded in the OS Image), It can then pull the auth.json somewhere (e.g. the secrets or configmap in api-server) and put it in /root/.config/containers/auth.json. The later containers will leverage this auth.json

**Comment by yoheiueda** [comment]
As described in this comment https://github.com/confidential-containers/cloud-api-adaptor/issues/99#issuecomment-1189209126, the custom conatinerd does not support image pull secrets, while kata agent protocol supports image pull secrets in PullImageRequest.

This means that CAA can inject an image pull secret into a PullImageRequest, since we have an agent protocol proxy in CAA.  CAA receives pod name and namespace from Kata shim, so it is possible to talk to kube API server to retrieve its pod definition that includes the image pull secret.

Another possible solution is to introduce mutating admission webhook to alter the pod definition to mount the Secret that contains the pull image secret to the pod as a volume. Then, kubelet prepares a directory that contains the Secret in a local directory, and CAA can access to the secret in the directory. CAA can also remove the volume definition from the CreateContainerRequest not to disclose the secret data to container workloads.

**Comment by liudalibj** [comment]
If the CAA is running as container then it can talk to kube API server to retrieve its pod definition that includes the image pull secret and get the image pull secret.
at here we have two option just follow comments in https://github.com/confidential-containers/cloud-api-adaptor/issues/344#issuecomment-1306769340 and https://github.com/confidential-containers/cloud-api-adaptor/issues/344#issuecomment-1306774963
1.  put the queried image pull secret to /root/.config/containers/auth.json in the podvm via file copy or cloud-init data.
2. pass the queried image pull secret to `PullImageRequest` via agent protocol proxy. 

One thing need think about is that how we protect the image pull secret? 
Will we use it directly or can we provide a more safely way(eg. encrypt the secret before put as secret object) so that not to disclose by kube admin?

**Comment by huoqifeng** [comment]
> As described in this comment [#99 (comment)](https://github.com/confidential-containers/cloud-api-adaptor/issues/99#issuecomment-1189209126), the custom conatinerd does not support image pull secrets, while kata agent protocol supports image pull secrets in PullImageRequest.
> 
> This means that CAA can inject an image pull secret into a PullImageRequest, since we have an agent protocol proxy in CAA. CAA receives pod name and namespace from Kata shim, so it is possible to talk to kube API server to retrieve its pod definition that includes the image pull secret.
> 
> Another possible solution is to introduce mutating admission webhook to alter the pod definition to mount the Secret that contains the pull image secret to the pod as a volume. Then, kubelet prepares a directory that contains the Secret in a local directory, and CAA can access to the secret in the directory. CAA can also remove the volume definition from the CreateContainerRequest not to disclose the secret data to container workloads.

@yoheiueda I agree this is a reasonable approach before containerd support image pull secret, which follows the existing CRI and k8s schema. a client to talk with api-server is possible as all certs are are available on worker. Maybe, @liudalibj concerns for secret exposure is another problem and can be addressed in future/separate issue?

**Comment by liudalibj** [comment]
> > As described in this comment [#99 (comment)](https://github.com/confidential-containers/cloud-api-adaptor/issues/99#issuecomment-1189209126), the custom conatinerd does not support image pull secrets, while kata agent protocol supports image pull secrets in PullImageRequest.
> > This means that CAA can inject an image pull secret into a PullImageRequest, since we have an agent protocol proxy in CAA. CAA receives pod name and namespace from Kata shim, so it is possible to talk to kube API server to retrieve its pod definition that includes the image pull secret.
> > Another possible solution is to introduce mutating admission webhook to alter the pod definition to mount the Secret that contains the pull image secret to the pod as a volume. Then, kubelet prepares a directory that contains the Secret in a local directory, and CAA can access to the secret in the directory. CAA can also remove the volume definition from the CreateContainerRequest not to disclose the secret data to container workloads.
> 
> @yoheiueda I agree this is a reasonable approach before containerd support image pull secret, which follows the existing CRI and k8s schema. a client to talk with api-server is possible as all certs are are available on worker. Maybe, @liudalibj concerns for secret exposure is another problem and can be addressed in future/separate issue?

I agree this approach too, the sample code to get `serverName` under `namespace` via kubeCoreClientset
```
secret := kubeCoreClientset.CoreV1().Secrets(namespace).Get(context, secretName, metav1.GetOptions{})
```

**Comment by bpradipt** [comment]
@liudalibj @yoheiueda do you know if adding the secret to the PullImageRequest require any changes to image-rs or image-rs already has support for it ?

**Comment by stevenhorsman** [comment]
> @liudalibj @yoheiueda do you know if adding the secret to the PullImageRequest require any changes to image-rs or image-rs already has support for it ?

DaLi and Yohei might have a better answer, but if we are talking about the kata agent PullImageRequest and injecting it to the request from the agent-protocol-forwarder - it always has support for user:password style credentials and the the agent flows them into image-rs. I've not tested this mechanism for about a year, but it used to work when I wrote to the original kata-agent pull image code. I hope that helps and I've not got the wrong end of the stick!

**Comment by liudalibj** [comment]
> > @liudalibj @yoheiueda do you know if adding the secret to the PullImageRequest require any changes to image-rs or image-rs already has support for it ?
> 
> DaLi and Yohei might have a better answer, but if we are talking about the kata agent PullImageRequest and injecting it to the request from the agent-protocol-forwarder - it always has support for user:password style credentials and the the agent flows them into image-rs. I've not tested this mechanism for about a year, but it used to work when I wrote to the original kata-agent pull image code. I hope that helps and I've not got the wrong end of the stick!


Yeah the image-rs support `user:password` style credentials for now, refer to https://github.com/confidential-containers/image-rs/blob/main/src/image.rs#L174

**Comment by liudalibj** [comment]
More details https://github.com/confidential-containers/image-rs/blob/main/docs/image_auth.md

**Comment by bpradipt** [comment]
Another option for the non-confidential case, is to add the creds file to the pod VM via the `userdata`.

Ref: https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/hypervisor/aws/service.go#L176

A possible approach:
1. Add a CLI option to CAA to provide an option `auth.json` file. CAA provides this file to the Pod VM via `userdata` during launch
2. The `auth.json` can be a k8s secret object and provided via volume mount to the CAA daemonset. 

We are already using `userdata` to put the `daemon.json`. Only restriction will be the `userdata` limit. 
However, this will be a dynamic mechanism in addition to the static embedding of auth.json in the pod VM image.

This approach of course won't be acceptable for confidential containers case, but for coco case we anyway would prefer to retrieve it post successful attestation.

wdyt @snir911 @stevenhorsman @liudalibj  @huoqifeng ?

**Comment by snir911** [comment]
Nice! the second approach sounds better to me, maybe even just use the pull-secrets used by the caa pod.
still a custom `imagePullSecrets` of pod won't be respected until fully delegating the pull request solution, however, for now, sounds to me like a good option (assuming passing secrets in userdata is acceptable)

**Comment by huoqifeng** [comment]
Let's take this as an example:
```
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: regcred
```
`regcred` will not be handled by customized containerd, I think what @yoheiueda suggested is to retrieve this `regcred` in CAA and add them into `*pb.PullImageRequest` in https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/proxy/service.go#L211 when detected there is a `imagePullSecrets` defined in Pod descriptor.
@yoheiueda please correct me if I undestood wrong.

**Comment by bpradipt** [comment]
Closing this issue since we have support for using authenticated registry by injecting auth.json to podvm
