### ISSUE TITLE
Public sample pod VM images

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#372]
To make it easier to try out peer pods having public sample pod vm images will be great.
This is a tracker issue to explore the feasibility.

**Comment by bpradipt** [comment]
@huoqifeng @stevenhorsman @knrt10 @mkulke any suggestions ..

**Comment by stevenhorsman** [comment]
I think this is a good idea, but I'm not sure of the best mechanism of how we do it. 
In theory for the ibm cloud provider we could create a publicly accessible qcow2 image and then give uses instructions of how to build the custom VSI image from that, but I'm not sure quite which account we'd host it under (it might be a bit dodgy for me to just share mine), but we can talk through that internally.
Excuse my ignorance, but I'm assuming that the packer process for the other cloud providers still generates a qcow2 image, which is then converted into the various required formats e.g. AMI file, so I wonder if sharing that qcow2 image pre-conversion is the path of least resistance.

Looking forward to hearing some better ideas though!

**Comment by bpradipt** [comment]
Packer is creating native images for the cloud providers. However it's possible to use qcow2 as the base to create cloud provider specific images (without using packer).

Currently we are using the same qcow2 for both libvirt and aws. AWS requires the qcow2 to be converted to a raw image before using the aws cli commands to create the AMI. I have seen a similar process for Azure (converting qcow2 to vhd and then uploading it).  Same for ibmcloud and vsphere.

@stevenhorsman, your suggestion of publishing a qcow2 image along with instructions to use the qcow2 image with different providers seems like a practical approach.

Github release allows to attach binaries limited to 2GB in size. This should be enough for attaching the qcow2 as the size is typically <500MB.

For providing native images for cloud providers, afaik we need csp accounts which then leads to cost, billings etc. This will need discussions.

**Comment by huoqifeng** [comment]
I was thinking whether it's reasonable to release podvm as another operators payload image, so that when user deploy peerpod via operator, the controller can pick the payload image and extract the qcow2 or other files and deploy it to cloud providers account. The returned image information may also be saved in the configuration of CAA via operator but don't need users input. payload images might be different per provider to reduce the size. But, Yeah, just rough thoughts because which might introduce complexity and put operator in risk.

**Comment by bpradipt** [comment]
@huoqifeng using the operator might be a possibility. May be using a separate controller to manage the cloud specific images. But will need some serious thinking on pros and cons.

**Comment by bpradipt** [comment]
> Packer is creating native images for the cloud providers. However it's possible to use qcow2 as the base to create cloud provider specific images (without using packer).
> 
> Currently we are using the same qcow2 for both libvirt and aws. AWS requires the qcow2 to be converted to a raw image before using the aws cli commands to create the AMI. I have seen a similar process for Azure (converting qcow2 to vhd and then uploading it). Same for ibmcloud and vsphere.
> 
> @stevenhorsman, your suggestion of publishing a qcow2 image along with instructions to use the qcow2 image with different providers seems like a practical approach.
> 
> Github release allows to attach binaries limited to 2GB in size. This should be enough for attaching the qcow2 as the size is typically <500MB.

I think it should be possible to use github action to create qcow2 using packer. I tried packer on a VM without kvm and it worked fine. Qemu was started with tcg (`emulation`)

```
/usr/bin/qemu-system-x86_64 -smp cpus=2 -cdrom cloud-init.img -device virtio-net,netdev=user.0 -boot c -machine type=pc,accel=tcg -vnc 127.0.0.1:73 -m 2048M -serial mon:stdio -drive file=output/podvm-c9fec479-dirty-amd64.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2 -name podvm-c9fec479-dirty-amd64.qcow2 -netdev user,id=user.0,hostfwd=tcp::4002-:22
```

**Comment by huoqifeng** [comment]
@bpradipt Start from an oci image might be a intermediate step to operator. We can provide the podvm image deploy scripts and build the qcow2 disk files into an oci image, end user can start a container via podman/docker `run` command with providers apikey passed in and trigger a podvm image deployment in the container.

**Comment by jtumber-ibm** [comment]
Could use https://github.com/marketplace/actions/packer-github-actions ?

In the podvm directory we could have a qcow build for generic none provider specifc image, that could be built in the action and then imported by the users into their required provider?

**Comment by jtumber-ibm** [comment]
Hi @bpradipt have you already started work on using github actions for generating public sample pod VM images?
