### ISSUE TITLE
Handle dangling cloud resources

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#375]
In the following issue - https://github.com/confidential-containers/cloud-api-adaptor/issues/328 we discussed about the dangling cloud resource problem. Currently cloud-api-adaptor (CAA) is stateless and this results in cases where the pod VM instances created by the caa is not deleted if the worker node reboots (on error, node maintenance etc).

To handle such cases, we felt the need to have a CRD for pod VM to maintain the state and perform required cleanups.

cc @yoheiueda @jensfr @surajssd

**Comment by yoheiueda** [comment]
Currently, `cloud-api-adaptor` uses a on-memory map to manage mapping between VM instances and pod VMs. `cloud-api-adaptor` runs on a worker node, so a worker node crash results in a loss of the mapping information. This leads to dangling pod VMs.

To solve this problem, we can use a CRD object to represent a pod VM.  CRD objects are resilient to worker node crashes, and we can implement a controller to monitor CRD objects to clean dangling pod VMs.

This is the (incomplete) controller code that implements a similar mechanism. This code comes from  my project project, so cannot directly be applied to cloud-api-adaptor, but we can use it as a reference.

https://gist.github.com/yoheiueda/122619c2b12457edd46105741a14bf09

PeerPod is a CRD that represents a peer pod VM. There is a 1-1 mapping between Pod and PeerPod objects. A PeerPod objects contains VM instance information such as ID and IP address.

A PeerPod has a owner reference to the Pod object. This reference manages mapping between PeerPod and Pod, and guarantees the PeerPod object is automatically deleted, when the corresponding Pod object is deleted.
https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/

When the controller detects a new Pod creation with a specific runtimeClass, it creates a PeerPod object with a owner reference to the original Pod object.

The controller monitors PeerPod object creation, and when it detects a new PeerPod object, it talks with a cloud API endpoint to create a new VM instance. When it obtains VM information such as IP address of the newly created VM instance, it updates the PeerPod object to include such VM information.

When CAA receives a CreateSandboxRequest from Kata shim, it talks with Kubernetes API server to wait for the corresponding PeerPod object becoming ready. Then, CAA gets the IP address information from the updated PeerPod object, and establishes a tunnel for agent protocol communication between kata shim and kata agent.

When the controller detects deletion of a PeerPod objects, it talks with the cloud API endpoint to delete the VM instance.

With this approach, we don't need to care about dangling VM problem. Kubernetes guarantees the PeerPod object is deleted when the corresponding Pod object is deleted.

**Comment by mkulke** [comment]
I wonder whether we can introduce this change more incrementally:

If we create/delete the PeerPod CRD Object in the CAA daemonset, instead of provisioning the peerpod compute resources directly and have a controller handle the Peerpod objects to provision/cleanup vm, etc resources. would that work? 

A crash in the daemonset might still produce dangling Peerpod objects, but if we annotate them with an `OwnerReference` to the pod,  a deletion of the pod would cascade to the peerpod.

This way we'd keep the daemonset setup in place and offload the CSP resource mgmt to a dedicated controller.

**Comment by bpradipt** [comment]
@mkulke If I understand correctly, you are suggesting to create the PeerPod CRD from the CAA daemonset and set the `OwnerReference` to the Pod. We'll still need the CRD controller to ensure no cloud instance remains post pod deletion.
I am in favour of this approach as we can keep the daemonset setup in place and make gradual changes.

**Comment by mkulke** [comment]
@bpradipt yes, this would be my suggestion. keeping the daemonset in place, adding a controller/crd as layer of indirection, manage crds instead of calling out to CSP APIs directly in the daemonset.

**Comment by jensfr** [comment]
I agree, that's a good first step!

**Comment by bpradipt** [comment]
cc @snir911
