### ISSUE TITLE
ibmcloud: podvm-build terraform template can get stuck and run indefinitely

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#38]
It is possible to get into a state where the podvm-build step runs 'forever' (I've left it for 2 hours and it still hasn't completed). I think it is to do with a combination of the ansible playbook not detecting a failure and quiting/timing out and a problem occurring in the push step fails.

I think the path to re-produce is:
- Create a new cos service instance using the `cos` terraform template
- Running the podvm-build terraform template using the cos instance info which creates the qcow2 into the cos bucket and imports that as a VPC custom image.
- Run `terraform destroy` on the podvm-build. AFAIK this doesn't actually delete the custom image, of qcow2 resources.
- Run `terraform destroy` on the `cos` template. This deletes the cos bucket and the qcow2 images
- Re-run `terraform apply` on the `cos` template. Due to the testing I was doing I had changed the `cos_service_instance_name` field name in `terraform.tfvars` before this, but I'm not 100% sure if that is required
- Run `terraform apply` on `podvm-build`. The `TASK [Push peer pod VM image to Cloud Object Store and verify the image]` task of this runs for 2 hours +

I manually `ssh`'d into the worker node and tried to manually run the process that the script was doing:
```
cd cloud-api-adaptor/ibmcloud/image/
export IBMCLOUD_API_KEY="<My API key>"
export IBMCLOUD_COS_SERVICE_INSTANCE=<my cos service instance name>
export IBMCLOUD_COS_BUCKET=<My cos bucket name>
export IBMCLOUD_COS_REGION=jp-tok
export IBMCLOUD_COS_SERVICE_ENDPOINT=https://s3.jp-tok.cloud-object-storage.appdomain.cloud
export CLOUD_PROVIDER=ibmcloud
make push
```
This resulted in the output:
```
Successfully updated service endpoint URL.
+ ibmcloud cos config crn --crn 6a18343c-b4f5-4d05-988f-0653c5e63c4e
WARNING: You have already stored a service instance ID before.
It was last updated on Monday, May 30 2022 at 20:11:22.
Select the CRN
1. 6a18343c-b4f5-4d05-988f-0653c5e63c4e
2. ec1664a1-6fc2-49e4-8a30-8ae402edc19a
Enter a number (1)>
```
which is waiting for input. I'm guessing this might the reason for it hanging?
When I manually run this I don't get the issue, but after a fair bit of searching I've found that the make script creates a local bluemix config inside it's directory and I can see the state stored there:
```
cat /root/cloud-api-adaptor/ibmcloud/image/.bluemix/plugins/cloud-object-storage/config.json
{
  "CRN": "ec1664a1-6fc2-49e4-8a30-8ae402edc19a",
  "HMACProvided": false,
  "Last Updated": "Monday, May 30 2022 at 20:50:17",
  "ServiceEndpointURL": "https://s3.jp-tok.cloud-object-storage.appdomain.cloud"
}
```
I can't find any command to reset this using the IBM Cloud CLI, so I did a workaround on the system by deleting the config file. and then the terraform template worked.

**Comment by ariel-adam** [comment]
@stevenhorsman is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by stevenhorsman** [comment]
AFAIK this issue hasn't been addressed. It's probably not high priority as we'd like to have CI/CD to automate some of this in future which should lead to it being run on 'clean' systems and therefore not hit this problem though.

**Comment by ariel-adam** [comment]
Marking it as a low priority with not target drop
