### ISSUE TITLE
Generate qcow2 image for all providers

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#391]
Having the qcow2 image generation process in the common `podvm` directory will make it easier to generate qcow2 images for all providers which can then be converted to native format as needed.

This will also help with releasing qcow2 images for podvm as release artifacts.

**Comment by jtumber-ibm** [comment]
I did some testing with generating s390x qcow image in github actions earlier this week. Which worked, just need to extend some wait times as the emulation seems to be a little slow.

To produce a full image though we will also need to cross-compile, the binaries.
