### ISSUE TITLE
Add troubleshooting guide

### ISSUE THREAD

**Issue by davidhay1969** [confidential-containers/cloud-api-adaptor#40]
There's a need for an additional document - a troubleshooting guide - to be linked from the [README](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/ibmcloud/README.md) for the IBM Cloud playbooks etc. for Peer Pods VMs.

This issue is to track the creation of such a guide.

**Comment by mattarnoatibm** [comment]
Hi Dave. In the staging branch, there is now a troubleshooting guide at the end of the readme here https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud#troubleshooting

**Comment by davidhay1969** [comment]
Awesome, didn't see that, thanks @mattarnoatibm

**Comment by davidhay1969** [comment]
As discussed with Matt, I will move the existing Troubleshooting [tip](https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud#cluster-creation-when-switching-use-ssh_pub_key) into the separate document which I've created, and link to that document from the [README](https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud) itself.

**Comment by davidhay1969** [comment]
PR [Add separate troubleshooting guide #42](https://github.com/confidential-containers/cloud-api-adaptor/pull/42) raised

**Comment by davidhay1969** [comment]
Working through a review with Matt on the above PR ...
