### ISSUE TITLE
Refactor cloud provider code

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#458]
Cloud API Adaptor supports multiple cloud providers, but the current implementation contains a lot of duplicated code among multiple providers.

We need to refactor cloud provider code to reduce such duplication as well as addressing the following issues.

### Modification of the duplicated code

If we need to implement a new feature in the duplicated code, we need to write the same code to all of the duplicated code.
Example: https://github.com/confidential-containers/cloud-api-adaptor/pull/381

### Build constrains

We currently rely on build constraints to select a specific cloud provider. We can enable only a single cloud provider in a single binary, and we cannot enable multiple cloud providers in a single binary, even though we need to specify a cloud provider name as a command line argument. This design prevents us to build a common binary that supports all cloud providers. 

https://github.com/confidential-containers/cloud-api-adaptor/blob/2c01e3445274dc250e92c1686e53fbf078d5f458/pkg/adaptor/hypervisor/registry/ibmcloud.go#L1-L13

### Unit tests in CI

Currently, unit tests are executed for all cloud providers. This is redundant, since the same tests are executed multiple times. We can execute unit tests using a single run if we can fix the build constraint problem.

https://github.com/confidential-containers/cloud-api-adaptor/blob/2c01e3445274dc250e92c1686e53fbf078d5f458/.github/workflows/build.yaml#L44

**Comment by yoheiueda** [comment]
We first introduce a common package to refactor cloud provider code, and then refactor each cloud provider code one by one.

- [ ] Introduce common package for the shared code among multiple cloud providers
- [ ] Refactor ibmcloud provider
- [ ] Refactor aws provider
- [ ] Refactor azure provider
- [ ] Refactor vsphere provider
- [ ] Refactor libvirt provider
- [ ] Remove dead code
- [ ] Update CI to avoid redundant unit test execution

**Comment by yoheiueda** [comment]
@bpradipt  refactoring ibmcloud code is done, and we need to refactor the other cloud providers one by one.

The new code layout is described here https://github.com/confidential-containers/cloud-api-adaptor/pull/329#issuecomment-1376843922.

The ibmcode code is https://github.com/confidential-containers/cloud-api-adaptor/pull/329/commits/c89daf702de4e342df8b9b52ec1c19fdec4d59ae for a reference.

**Comment by knrt10** [comment]
I can work on the Azure part if it's okay @yoheiueda ?

**Comment by bpradipt** [comment]
@yoheiueda created PR for aws provider #580

**Comment by bpradipt** [comment]
@yoheiueda can this be closed now ?

**Comment by yoheiueda** [comment]
I was also planning to refactor CI tests to redundancy as I describted at https://github.com/confidential-containers/cloud-api-adaptor/issues/458#issuecomment-1363171148, but it is somewhat off topic for this issue.

I close this issue for now, and will raise another issue for the topic.
