### ISSUE TITLE
Failed to create peer pods with error "Invalid internetworking model"

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#505]
Setup a new peer pods demo environment, and try to create a peer pod with runtimeclass kata.

It failed in pod description:
```
Warning  FailedCreatePodSandBox  21s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: Invalid internetworking model: unknown
```

Check caa log `/var/log/cloud-api-adaptor.log`:
```
2023/01/10 08:32:54 [adaptor/proxy] established cri uds connection to /run/containerd/containerd.sock
2023/01/10 08:33:04 [adaptor/proxy] failed to establish agent proxy connection to 10.244.64.31:15150: dial tcp 10.244.64.31:15150: i/o timeout. (retrying... 1/20)
2023/01/10 08:33:14 [adaptor/proxy] failed to establish agent proxy connection to 10.244.64.31:15150: dial tcp 10.244.64.31:15150: connect: connection refused. (retrying... 2/20)
2023/01/10 08:33:24 [adaptor/proxy] failed to establish agent proxy connection to 10.244.64.31:15150: dial tcp 10.244.64.31:15150: connect: connection refused. (retrying... 3/20)
2023/01/10 08:33:24 [adaptor/proxy] established agent proxy connection to 10.244.64.31:15150
2023/01/10 08:33:24 [helper/hypervisor] agent proxy is ready
2023/01/10 08:33:24 [adaptor/proxy] shutting down socket forwarder
2023/01/10 08:33:25 [helper/hypervisor] deleted an instance 02f7_efb9955b-ff04-4f65-a3ec-a3123e91d340
```
The connection is established, but the sandbox/pod vm is shut down soon.

Check kata logs:
```
Jan 10 08:34:29 ibm-caa-worker kata[261107]: time="2023-01-10T08:34:29.773508281Z" level=info msg="calling remote hypervisor StartVM (timeout: 600)"
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.701441048Z" level=info msg="hypervisor pid is 261107" name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=sandbox
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.702363934Z" level=info msg="veth interface found" name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=network
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.702417759Z" level=info msg="Attaching endpoint" endpoint-type=virtual hotplug=true name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=network
Jan 10 08:35:12 ibm-caa-worker kata[261107]: time="2023-01-10T08:35:12.702458597Z" level=error msg="Error bridging virtual ep" error="Invalid internetworking model" name=containerd-shim-v2 pid=261107 sandbox=81a3b027a709db0549e4ac7d0cae84cd8f3e909a3d71895c97a753170091c77f source=virtcontainers subsystem=network
```

**Comment by genjuro214** [comment]
I doubt it's related to the recent merge from main branch:
https://github.com/kata-containers/kata-containers/commit/e8c63ccc4d93ae1e4019ed1e310938328e8044bb#diff-a6e45adf0a559c18c61d84b1ea3225f62c1cf6166c7bf1f5b24e5c034921db09

because this check: https://github.com/kata-containers/kata-containers/blob/CCv0/src/runtime/virtcontainers/sandbox.go#L1267, network.AddEndpoints() is invoked unexpected for remote hypervisor.

**Comment by stevenhorsman** [comment]
It's in sandbox networking, so way outside of my comfort zone, but I think the issue boils down to:
- https://github.com/kata-containers/kata-containers/commit/578a9c25f05c53525319a968f379ca718e8c9db7 added:
```
// We need to rescan and handle the change.
	if s.factory != nil || prestartHookFunc != nil {
```
which means `s.network.AddEndpoints(ctx, s, nil, true)` is now called during `startVM`
- `AddEndpoints` calls `func (n *LinuxNetwork) addSingleEndpoint(ctx context.Context, s *Sandbox, netInfo NetworkInfo, hotplug bool) (Endpoint, error) {` which calls `func (endpoint *VethEndpoint) HotAttach(ctx context.Context, h Hypervisor) error {` which calls `func xConnectVMNetwork(ctx context.Context, endpoint Endpoint, h Hypervisor) error { `
- This has a switch on the networking model with cases for `mactap` and `tcfilter` and a default which gives `err = fmt.Errorf("Invalid internetworking model")`
- Our configuration for peer pods is `internetworking_model="none"` so we fall into the default case.

I've no idea if we need to have a fix to `xConnectVMNetwork` to support none, or do something to stop it being called for the remote hypervisor, but it's not clear to me where that should be as I think that sandbox is a high layer of abstraction above hypervisor? Or alternatively someone like @yoheiueda who is an actual expert might have a better solution.

**Comment by stevenhorsman** [comment]
FYI I've created https://github.com/kata-containers/kata-containers/pull/6022 for this. I suspect it is not the best change, but I figured that creating a PR might be the best way to start the discussion in kata-containers.

**Comment by yoheiueda** [comment]
@genjuro214 and @stevenhorsman Thank you for the investigation!

Adding support of `internetworking_model="none"` to Kata looks reasonable to me.

**Comment by stevenhorsman** [comment]
FYI: Tao made a fix upstream and I've created a PR to cherry-pick this into `CCv0`: https://github.com/kata-containers/kata-containers/pull/6057 which is in test now.

I tried the ibm cloud e2e flow pointing at that branch and it seems to be working correctly, so hopefully once that merges we can test and close this issue

**Comment by stevenhorsman** [comment]
The PR has been merged, so I think this issue is resolved now.

**Comment by genjuro214** [comment]
I'm fine to close this issue.
