### ISSUE TITLE
podvm: reduce size of layers in containers builds

### ISSUE THREAD

**Issue by snir911** [confidential-containers/cloud-api-adaptor#524]

**Comment by jtumber-ibm** [comment]
Hi @snir911 could you describe the problem in more detail? Is this size of the layers having an impact on the performance of the scripts? And would it be more preferable to do a shallow clone of the kata repository than try to delete stuff afterwards?

**Comment by snir911** [comment]
@jtumber-ibm so the idea is just to reduce the size of the layers committed during the build, one way is to clean the trees, not because of the git repos themselves but mostly because of other unneeded artifacts of the build, mostly from the rust target folders IIRC, this should require less space for container builds.
Another thing is to speed up the process be avoid forcing re-build
