### ISSUE TITLE
vsphere: vmdk-to-ovf.sh centos qcow2 does not work

### ISSUE THREAD

**Issue by whitebrandy** [confidential-containers/cloud-api-adaptor#527]
CentOS qcow2 cloud images do not work with EFI and vsphere has deprecated legacy bios. While we cross the bridge when it comes to it, for now, the most likely solution is to disable efi when generating templates from Centos qcow2s.

**Comment by bpradipt** [comment]
@whitebrandy can this issue be closed ?

**Comment by whitebrandy** [comment]
yes, not sure why it didn't happen automatically when #528 was merged
