### ISSUE TITLE
Vsphere: Podvm built from rhel8.iso does not contain the attestation-agent (AA) 

### ISSUE THREAD

**Issue by caavery** [confidential-containers/cloud-api-adaptor#529]
vsphere/image iso build needs to be built with AA_KBC otherwise the peer pod fails with

2023/01/13 17:58:40 [adaptor/proxy] CreateContainer: failed to call PullImage, probably because the image has already been pulled. ignored: rpc error: code = Internal desc = failed to pull manifest Not authorized: url

@whitebrandy @bpradipt

**Comment by bpradipt** [comment]
I think this is no longer valid as community binaries are build with AA_KBC - https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/podvm/Dockerfile.podvm_binaries.rhel#L13
If you are building your own image, then AA_KBC needs to be set explicitly.
