### ISSUE TITLE
Azure: Use VNET, Subnet and NSG information instead of the autogenerated `AZURE_VM_NAME`

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#551]
Right now Azure provider asks the user to provide the `AZURE_VM_NAME` when it should ask specific information like the following:

- virtual network name
- subnet name
- nsg name

https://github.com/confidential-containers/cloud-api-adaptor/blob/7ea33fb00114bc9132313258ac92f7d808ccb437/entrypoint.sh#L52-L53

https://github.com/confidential-containers/cloud-api-adaptor/blob/7ea33fb00114bc9132313258ac92f7d808ccb437/install/overlays/azure/kustomization.yaml#L22

In a set up where the user has created a VM (that starts CAA pod VM) different from the default set up then this may not work, so asking specific information is better than autogenerating the vnet name, subnet name, nsg name, etc.

cc: @knrt10

**Comment by knrt10** [comment]
Cool, will create a PR for the same.
