### ISSUE TITLE
Azure: Path to SSH Key

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#552]
This should be the path to the public key, so that the CAA can give it to the Azure APIs to be able to create the VM

https://github.com/confidential-containers/cloud-api-adaptor/blob/7ea33fb00114bc9132313258ac92f7d808ccb437/install/overlays/azure/kustomization.yaml#L41

cc: @knrt10

**Comment by knrt10** [comment]
Make sense. Will update it
