### ISSUE TITLE
vsphere: CAA no longer builds image without error

### ISSUE THREAD

**Issue by caavery** [confidential-containers/cloud-api-adaptor#554]
This appears to be due to one of the recent multi arch support commits. 

registry=quay.io/cavery/new/cloud-api-adaptor-vsphere CLOUD_PROVIDER=vsphere make image

ubuntu@buildserver:~/remote-hyp/cloud-api-adaptor.upstream$ registry=quay.io/cavery/new/cloud-api-adaptor-vsphere CLOUD_PROVIDER=vsphere make image
hack/build.sh
/mnt/build/remote-hyp/cloud-api-adaptor.upstream ~/remote-hyp/cloud-api-adaptor.upstream
[+] Building 0.0s (0/0)
ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
make: *** [Makefile:81: image] Error 1

@bpradipt @snir911

**Comment by bpradipt** [comment]
@jtumber-ibm

**Comment by jtumber-ibm** [comment]
Did you try the suggested `docker buildx create --use` ? 

Since #547 has gone in you can also now specify which platforms to build from e.g. `export ARCHES="linux/amd64"`

**Comment by caavery** [comment]
Did I miss new instructions? I install docker buildx and then what?

**Comment by jtumber-ibm** [comment]
> Did I miss new instructions? I install docker buildx and then what?

after you've run the `docker buildx create --use` you should be able to run the same command as before. 

`registry=quay.io/cavery/new/cloud-api-adaptor-vsphere CLOUD_PROVIDER=vsphere make image`

or 

`ARCHES=linux/amd64 registry=quay.io/cavery/new/cloud-api-adaptor-vsphere CLOUD_PROVIDER=vsphere make image` 

to just build the amd64 image

**Comment by jtumber-ibm** [comment]
@caavery can this be closed?
