### ISSUE TITLE
vsphere make image does not create a latest tag in quay.io

### ISSUE THREAD

**Issue by caavery** [confidential-containers/cloud-api-adaptor#558]
ARCHES=linux/amd64 registry=quay.io/cavery/new http://quay.io/cavery/new CLOUD_PROVIDER=vsphere make image

So a few things that are different and I'm not sure if they are intentional or not. 

*There is no latest tag

*The make image creates a new directory cloud-api-adaptor-vsphere where it did not before.
old command:
ARCHES=linux/amd64 registry=quay.io/cavery/new/cloud-api-adaptor-vsphere CLOUD_PROVIDER=vsphere make image

Now I have to run this
ARCHES=linux/amd64 registry=quay.io/cavery/new CLOUD_PROVIDER=vsphere make image
or I get the image in cavery /new/cloud-api-adaptor-vsphere/cloud-api-adaptor-vsphere instead of cavery /new/cloud-api-adaptor-vsphere

*And could we default to ARCHES=linux/amd64 ?

**Comment by jtumber-ibm** [comment]
Hi @caavery seperating out the registry and the image name was on purpose to help consistancy of naming across hosting providers. i.e. if we host it in `uk.icr.io/james-tumber` or `quay.io/cavery/new` we don't also have to specify the image name `cloud-api-adaptor-vsphere`.

I'll make a PR for the other changes, to include the latest tag and default to single arch
