### ISSUE TITLE
Merge peer-pods and CoCo operator/payloads together

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#561]
At the moment there is a fair bit of duplication between the peer pod and coco operator, as we look to make peer pods part of the coco release ideally we'd reduce this and maybe even get to the point that we can get rid of the separate peer pod operator completely?

This is my completely non-expert take, so please update this description as necessary to correct things

### Runtime-payload

When the peer pods controller was first created we had to have a custom kata-shim as it was built on the remote hypervisor support just in Yohei's branch, but it's since been merged into CCv0, so do we have an opportunity to merge the runtime-payloads closer together now (and perhaps entirely?)

Currently https://github.com/confidential-containers/cloud-api-adaptor/blob/0591f4302bbd82f51429b3fde64a0e94dc14f1bd/install/runtime-payload/Dockerfile#L1-L16
the extras in the peer pods runtime-payload are:
- copying over the `containerd-shim-kata-v2` - I think this is the same binary as in CoCo now so can be removed?
- Copying the remote kata config file - There is a question here of whether we introduce a new kata-remote runtime class and then this config to the CoCo operator for 0.4 as we are planning to be part of the release
- An updated kata-deploy script - In my non-expert view it looks like there is a little bit new relating to crio and k3s, but otherwise the differences are just due to refactors in `CCv0`?

### Pre-install payload

The peer pod pre-install has some systemd artifacts. It's not clear from https://github.com/confidential-containers/cloud-api-adaptor/pull/545#issuecomment-1402177995 whether these are even needed anymore?

### Peer-pod-controller

Could we add extra controllers e.g. peer-pod controller to the CoCo operator?

**Comment by stevenhorsman** [comment]
\cc @fidencio @bpradipt @jensfr @snir911 @jtumber-ibm - sorry for my ignorance, but I thought it would be good to get this conversation started in public

**Comment by bpradipt** [comment]
@stevenhorsman I think we really don't need the runtime-payload code anymore once we have the remote hypervisor config added to the Kata ccv0 release payload.

**Comment by bpradipt** [comment]
Minor correction. We will still need the runtime-payload for cri-o which we'll base it on the ccv0 release payload.

**Comment by fidencio** [comment]
@stevenhorsman, I'd go for:
* Add the new peer-pods configuration as part of the default configs for CCv0
* I'd like to take a at the kata-deploy script, as I'm pretty sure it can be merged to the current one without any problems (and hey, I can help here).

**Comment by stevenhorsman** [comment]
FYI I've created
https://github.com/kata-containers/kata-containers/issues/6349 - which I have a draft PR for and https://github.com/kata-containers/kata-containers/issues/6351 to cover this work in kata-containers.

**Comment by stevenhorsman** [comment]
FYI - https://github.com/kata-containers/kata-containers/issues/6349 - which I have a draft PR for and https://github.com/kata-containers/kata-containers/issues/6351 have closed, so I think we can start removing our own copy of the runtime-payload?

**Comment by stevenhorsman** [comment]
The operator blocker is now resolved, so I've created https://github.com/confidential-containers/operator/issues/186 to cover updating the coco operator to add the runtime class. I have a question on how much of the custom peer pod cc-runtime we can remove and merge into the coco version in that though

**Comment by stevenhorsman** [comment]
I've carried on working on this and tried to use https://github.com/stevenhorsman/cloud-api-adaptor/blob/8c5414e30c5cf59f4203cea7e68d6b80a16d4c94/install/yamls/kustomization.yaml to overwrite the values in the cc runtime, so that cc runtime is the same as the coco version and then we can get rid of it, but I can't get the kustomize to work and it's not pulling the image I specify in there, but instead the base image:
```
 Warning  Failed     61s (x4 over 2m24s)  kubelet            Failed to pull image "quay.io/confidential-containers/runtime-payload:kata-containers": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/confidential-containers/runtime-payload:kata-containers": failed to resolve reference "quay.io/confidential-containers/runtime-payload:kata-containers": quay.io/confidential-containers/runtime-payload:kata-containers: not found
```
so I think someone who understand the operator better than me need to pick this up and move it along

**Comment by stevenhorsman** [comment]
With the changes that Pradipta made in https://github.com/confidential-containers/operator/pull/202 I think the main piece of this is complete. What remains is:
- Updating our documentation to reflect the new two stage process:
  - Using CoCo operator to deploy the base stack
  - Deploy the CAA pod and config
- Remove the old code that isn't used anymore
  - pre-install and runtime payload directories
  - yamls/deploy.yaml and yamls/ccruntime-peer-pods.yaml
  
These could be split out under a separate issue, or done here.

**Comment by ariel-adam** [comment]
@stevenhorsman should this be moved to 0.6.0 for the list of issues not complete yet?

**Comment by stevenhorsman** [comment]
Thanks for the nudge Ariel, to have track these tasks better I broke them out into individual issues, so I think that can be close now:

- Update runtimeclass in docs/demos/tests to kata-remote: https://github.com/confidential-containers/cloud-api-adaptor/issues/869 
- Update doc, Makefile/provisioning/e2e test to use ‘merged’ process and test: https://github.com/confidential-containers/cloud-api-adaptor/issues/870 
Once stable remove old methods: https://github.com/confidential-containers/cloud-api-adaptor/issues/871 
Later add the peerpodconfig-ctrl and peerpod-ctrl: https://github.com/confidential-containers/cloud-api-adaptor/issues/872

I'll add them to the 0.6 release.
