### ISSUE TITLE
Support multiple cloud providers in a single binary

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#573]
The current implementation uses build tag to select a single cloud provider code to be built into a single binary. This design can reduce the binary size, since unnecessary cloud provider code are not build into a binary.

For a case where binary size does not matter, we can enhance `cloud-api-adaptor` to support multiple or all of cloud providers into a single binary.  

Currently, we need to specify a cloud provider name in the first argument to the command line, so a `cloud-api-adaptor` process can dynamically select an appropriate cloud provider based on the argument.

https://github.com/confidential-containers/cloud-api-adaptor/blob/e09a1ea0c8a22d8d192ef5815eb585a48b629fc9/cmd/cloud-api-adaptor/main.go#L58-L59

While supporting multiple cloud providers does not complicate the code, it will have some benefits.

- We can create a single universal binary that supports all cloud providers
- CI tests are needed to be executed once ([currently CI tests needed to be executed per cloud provider](https://github.com/confidential-containers/cloud-api-adaptor/blob/e09a1ea0c8a22d8d192ef5815eb585a48b629fc9/.github/workflows/build.yaml#L15-L20))
- Friendly to go lint (currently we need to suppress golint errors by editing [.golangci.yaml](https://github.com/confidential-containers/cloud-api-adaptor/blob/e09a1ea0c8a22d8d192ef5815eb585a48b629fc9/.golangci.yaml#L281-L287))
-  Friendly to IDEs like VS Code (currently we need to specify a cloud provider like `GOFLAGS=tags=ibmcloud`, and language support does not work in the code for the other cloud providers)

The current libvirt support uses CGO, so it is probably convenient to keep using a build tag for the libvirt provider code, until swiching to pure go libvirt implementation is done. https://github.com/confidential-containers/cloud-api-adaptor/issues/119

**Comment by bpradipt** [comment]
@yoheiueda switching to pure go implementation for libvirt will be risky going forward. The pure go implementation is available from - https://github.com/digitalocean/go-libvirt whereas the one we use in CAA is the `official` libvirt go module available from - https://gitlab.com/libvirt/libvirt-go-module
Imho let's continue using the official libvirt go module which requires dynamic linking. 

Given that we create a container image for deployment of CAA, I think it should be ok to switch to a single dynamically linked binary for cloud-api-adaptor and agent-protocol-forwarder.

Wdyt ?

**Comment by yoheiueda** [comment]
@bpradipt I see. I think it is a good idea to keep using the official libvirt go module.

> Given that we create a container image for deployment of CAA, I think it should be ok to switch to a single dynamically linked binary for cloud-api-adaptor and agent-protocol-forwarder.

I agree. It makes sense.

**Comment by yoheiueda** [comment]
The current code already supports multiple cloud providers in a single binary if we forcibly set multiple build tags like `-tags aws,ibmcloud`. To officially support this, we need to update the `Makefile` and the help message of the command line.

https://github.com/confidential-containers/cloud-api-adaptor/blob/5d18b67acdb693439b4aaddd149a1dc52fda582b/cmd/cloud-api-adaptor/cloudmgr/manager.go#L19-L23

**Comment by bpradipt** [comment]
Just listing down the related items when moving to single binary

1. Update Makefile to create a single cloud-api-adaptor and agent-protocol-forwarder binary
2. Update Dockerfiles to use a single cloud-api-adaptor and agent-protocol-forwarder binary
3. Update github actions workflow to remove matrix runner for different cloud providers

**Comment by snir911** [comment]
I think also removing the remaining build tags
