### ISSUE TITLE
Cannot git-add files under  cmd/cloud-api-adaptor

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#578]
When I tries to stage changes to the files under `cmd/cloud-api-adaptor` with `git add`, I got the following error.

```
$ git add cmd/cloud-api-adaptor/main.go
The following paths are ignored by one of your .gitignore files:
cmd/cloud-api-adaptor
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

This is due to `.gitignore` has the following lines.

```
# Binaries
agent-protocol-forwarder
cloud-api-adaptor
kata-agent
```

**Comment by yoheiueda** [comment]
@jtumber-ibm You mentioned that modifying `.gitignore` is not necessary at https://github.com/confidential-containers/cloud-api-adaptor/pull/329#discussion_r1060514354

But, I still encounter the issue. What did you exactly mean by the comment? Can we modify `.gitignore` something like this?

```
# Binaries
/agent-protocol-forwarder
/cloud-api-adaptor
```

**Comment by bpradipt** [comment]
> @jtumber-ibm You mentioned that modifying `.gitignore` is not necessary at [#329 (comment)](https://github.com/confidential-containers/cloud-api-adaptor/pull/329#discussion_r1060514354)
> 
> But, I still encounter the issue. What did you exactly mean by the comment? Can we modify `.gitignore` something like this?
> 
> ```
> # Binaries
> /agent-protocol-forwarder
> /cloud-api-adaptor
> ```

The above is the fix which works. I faced this issue when refactoring for aws provider and had used the same entry in gitignore - https://github.com/bpradipt/cloud-api-adaptor/commit/a2271250e32f68bf82e1eb0ad314ebefeb3a0c00
