### ISSUE TITLE
New CAA framework: No DeleteProvider hook.

### ISSUE THREAD

**Issue by caavery** [confidential-containers/cloud-api-adaptor#593]
There does not seem to be a hook in the new CAA frame work so I can logout of vcenter when the CAA terminates.

type Cloud interface {
    ParseCmd(flags *flag.FlagSet)
    LoadEnv()
    NewProvider() (cloud.Provider, error)
} 

I just realized it was missing . I used to call it in Shutdown.

 func (s *server) Shutdown() error {
    DeleteGovmomiClient(s.gclient)
    s.stopOnce.Do(func() {
        close(s.stopCh)
    })
    return nil
}
@yoheiueda @bpradipt

**Comment by yoheiueda** [comment]
Thank you for reporting the issue.

I think what we need is a cleanup hook in the `cloud.Provider` interface, instead of the `cloudmgr.Cloud` interface.

I prepared a PR #594 to add a hook in  `cloud.Provider`.

@caavery Could you check whether it actually meets your requirement?
