### ISSUE TITLE
Permissions of directories in ConfigMap volumes are not correctly set

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#616]
When I created pods with runc and peer pod, the permissions of directories in ConfigMap volumes are differently set. In the example below, `/etc/config` is a volume made from a ConfigMap. 

|   |  runc | peer-pod  |
| --- | ---  | --- |
|  ` /etc/config/` |  777 | 750  |
|  ` /etc/config/..2023_02_15_14_11_11.2457166559` |  755 | 750  |

Peer-pod must be consistent with runc.

### runc
```
$ kubectl exec  pod/nginx -- ls -la /etc/config/
total 16
drwxrwxrwx 3 root root 4096 Feb 15 08:43 .
drwxr-xr-x 1 root root 4096 Feb 15 08:43 ..
drwxr-xr-x 2 root root 4096 Feb 15 08:43 ..2023_02_15_08_43_37.2076608953
lrwxrwxrwx 1 root root   32 Feb 15 08:43 ..data -> ..2023_02_15_08_43_37.2076608953
lrwxrwxrwx 1 root root   18 Feb 15 08:43 example.txt -> ..data/example.txt
```

### peer pod
```
$ kubectl exec  pod/nginx -- ls -la /etc/config/
total 16
drwxr-x--- 3 root root 4096 Feb 15 14:11 .
drwxr-xr-x 1 root root 4096 Feb 15 14:11 ..
drwxr-x--- 2 root root 4096 Feb 15 14:11 ..2023_02_15_14_11_11.2457166559
lrwxrwxrwx 1 root root   32 Feb 15 14:11 ..data -> ..2023_02_15_14_11_11.2457166559
lrwxrwxrwx 1 root root   18 Feb 15 14:11 example.txt -> ..data/example.txt
```

**Comment by yoheiueda** [comment]
I suspect this is due to the kata-agent implementation.

https://github.com/kata-containers/kata-containers/blob/ad889489a095d73e8d1bdb813533f72b43e6357e/src/runtime/virtcontainers/sandbox.go#L81-L82
https://github.com/kata-containers/kata-containers/blob/ad889489a095d73e8d1bdb813533f72b43e6357e/src/runtime/virtcontainers/kata_agent.go#L2170-L2171

kata-shim seems to send FileMode correctly to kata-agent, and I guessed kata-agent applies DirMode(0750) to FileMode when it creates a directory by mistake.

But, as far as I checked the source code of kata-agent, it seems to properly set a permission based on FileMode, and it doesn't apply DirMode when it creates a target directory.
https://github.com/kata-containers/kata-containers/blob/ad889489a095d73e8d1bdb813533f72b43e6357e/src/agent/src/rpc.rs#L2031

I will dig into the kata-agent implementation, and find out what is happening.

**Comment by yoheiueda** [comment]
I raise a PR to fix this issue. https://github.com/kata-containers/kata-containers/pull/6368

**Comment by stevenhorsman** [comment]
I've merged https://github.com/kata-containers/kata-containers/pull/6368 into `main`, but due to the CoCo 0.4 release code freeze it might be a week or so before it gets into the `CCv0` branch. I'll try and remember to update this issue when that happens though.

**Comment by jtumber-ibm** [comment]
This change is now in `CCv0` @yoheiueda good to close?

**Comment by stevenhorsman** [comment]
> This change is now in `CCv0` @yoheiueda good to close?

I don't think it is in `CCv0` yet - we've not done a merge since code-freeze opened last night.

**Comment by stevenhorsman** [comment]
I've just merged the `main` branch into `CCv0`, so this should be resolved now.

**Comment by yoheiueda** [comment]
I confirmed that this problem is fixed in with https://github.com/kata-containers/kata-containers/commit/45759e82b1bd035f8c87ee4157cafcf301743c88 with 23e2d16cdddb4065feb07ef23a42b568cb1d7a60.

```
$ kubectl exec  pod/nginx -- ls -la /etc/config/
total 16
drwxrwxrwx 3 root root 4096 Mar 20 00:38 .
drwxr-xr-x 1 root root 4096 Mar 20 00:38 ..
drwxr-xr-x 2 root root 4096 Mar 20 00:38 ..2023_03_20_00_37_50.2216911623
lrwxrwxrwx 1 root root   32 Mar 20 00:38 ..data -> ..2023_03_20_00_37_50.2216911623
lrwxrwxrwx 1 root root   18 Mar 20 00:38 example.txt -> ..data/example.txt
```
