### ISSUE TITLE
Add ibmcloud provisoner self-managed cluster for e2e test

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#620]
This will extend https://github.com/confidential-containers/cloud-api-adaptor/issues/490 to support self-managed cluster in IBM Cloud, besides IKS managed cluster.

- [ ] Self-Managed Cluster
   - [ ] VSI
   - [ ]  K8s Cluster

**Comment by stevenhorsman** [comment]
This isn't high priority, as we can use terraform to create clusters, so closing this.
