### ISSUE TITLE
ibmcloud: Terraform/ansible build needs libvirt-dev package installed on the build machine

### ISSUE THREAD

**Issue by mattarnoatibm** [confidential-containers/cloud-api-adaptor#636]
Terraform / ansible cluster creation for IBM Cloud provider needs the libvirt-dev package installed on the build machine. Otherwise, the build machine fails to build the Cloud API Adaptor with:

```
Package libvirt was not found in the pkg-config search path.
```

**Comment by bpradipt** [comment]
@mattarnoatibm try the build with `RELEASE_BUILD=true` which excludes libvirt provider
