### ISSUE TITLE
cloud-api-adaptor container image usage

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#637]
We have two types of builds:
- dev: includes all the provider including libvirt. 
- release: includes all the provider excluding libvirt. 

We need to decide on the following:
1. Publish both dev and release builds simultaneously for every PR merge ?
2. Publish only dev builds for every PR merge and release builds per release ?
3. Publish release builds for every PR merge?

**Comment by bpradipt** [comment]
@jtumber-ibm @snir911 @wainersm @stevenhorsman

**Comment by stevenhorsman** [comment]
My initial reaction is number 2, if the other difference is libvirt them I don't see much harm in publishing that on each PR merge. I don't have strong opinions on this though, so happy to go with the other suggestions.

**Comment by jtumber-ibm** [comment]
It would be nice to have the s390x images as up to date as the x86 for testing

**Comment by bpradipt** [comment]
@jtumber-ibm in that case we need to build both release and dev builds or figure out a way to create dev builds (no static builds) for s390x. Is it possible? Based on my previous experience with cross-compiling on ppc64le there were issues when using cgo so had to build natively. Hence the question.

**Comment by jtumber-ibm** [comment]
> 

If we need to wait for #119 to be able to have a s390x dev image then we can try to priorities that? Happy to have just dev (without s390x) for each PR at the moment.

**Comment by bpradipt** [comment]
@jtumber-ibm we won't be able to have a pure go implementation for libvirt in near future :-( . The official libvirt-go bindings need cgo and for long term maintainability it's better we stick to the official libvirt-go bindings. 
I see no harm in creating different builds for each PR.  We will need to figure out a way to tag or name it properly.

**Comment by snir911** [comment]
2 sounds like a good option (i assume runtime issues are less likely to appear with the non-cgo (release) build, although i'm not completely sure if it's actually true)

**Comment by bpradipt** [comment]
> @jtumber-ibm we won't be able to have a pure go implementation for libvirt in near future :-( . The official libvirt-go bindings need cgo and for long term maintainability it's better we stick to the official libvirt-go bindings. I see no harm in creating different builds for each PR. We will need to figure out a way to tag or name it properly.

By different builds, I meant dev and release builds.
