### ISSUE TITLE
Organise e2e/test packages for different providers

### ISSUE THREAD

**Issue by jtumber-ibm** [confidential-containers/cloud-api-adaptor#640]
Currently the e2e/test directory doesn't contain any subfolders and each provider is kept at a first level. IBM are currently planning in add two "provision" methods, using the IBMCloud managed kubernetes service (IKS) and spinning up our own cluster using the IBMCloud VPC infrastructure (Self Managed). To avoid bloating the tests I'd like to suggest the following structure. I've only included IBM for brevity.

The two "provisioner" only matter for starting up the cluster, once it has been created the rest of the test should operate in the same way so the `ibmcloud` "provider" should be used for both.

### e2e/test tree structure
```
.
├── ibmcloud_test.go
├── main_test.go
├── provider
│   ├── ibmcloud.go
│   └── types.go
├── provisioner
│   ├── ibmselfmanaged.go
│   ├── iks.go
│   └── types.go
└── README.md
```

This would hopefully lead to a tidier workspace.

Thoughts? @wainersm @bpradipt @snir911 

@huoqifeng this may help with #620

**Comment by wainersm** [comment]
hi @jtumber-ibm , it is a good idea. To be honest, when I started this code, lacked me golang experience to break it down into packages. Now it reached a point where the code is too convoluted, so we better organize it.
