### ISSUE TITLE
Disable unnecessary systemd services in pod vm images

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#699]
Ref: https://github.com/confidential-containers/cloud-api-adaptor/issues/343#issuecomment-1461252713
Disabling the unnecessary systemd services improves the boot up time.

**Comment by yoheiueda** [comment]
I previously analyzed systemd services in a different context.

https://github.com/confidential-containers/cloud-api-adaptor/pull/389#issuecomment-1333082911
