### ISSUE TITLE
Automatic generation of TLS certificates

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#705]
The agent protocol communication between `cloud-api-adaptor` and `agent-protocol-forwarder` can now be encrypted with TLS when certificates and keys are specified in the command line argument. #681

I think we can automate this TLS configuration by generating necessary certificates in cloud-api-adaptor in most of use cases.

From the perspective of `agent-protocol-forwarder`, network traffics coming from outside of a peer pod VM are not trusted at all. `cloud-api-adaptor` is not a trusted entity for `agent-protocol-forwarder`, so it can't trust the incoming network traffic even if the connection is encrypted. Ultimately, `agent-protocol-forwarder` should validate the incoming agent API requests by other means.

From the perspective of `cloud-api-adaptor`, TLS still has some meanings to reduce security risks as a defense-in-depth approach.

Since administrators of `cloud-api-adaptor` need to trust cloud environments such as the worker node VM instance and its background cloud infrastructure, `cloud-api-adaptor` can generate a pair of server cert/key for a peer pod VM, and then send them to the peer pod VM via cloud-init data.

I don't think sending a server private key to a peer pod VM via cloud-init data degrades security. From the perspective of `cloud-api-adaptor`, cloud-init data is considered as a secure communication channel. From the perspective of `agent-protocol-forwarder`, the TLS connection is not trusted anyway.

The steps to generate certificates and keys will be something like this. We can reuse the TLS mechanism introduced in #681.

1. At start up, `cloud-api-adaptor` generates the following two sets of certificate/key pairs
   * Self-signed client certificate and its private key
   * Self-signed server CA certificate and its private key
2. Before creating a peer pod VM, `cloud-api-adaptor` generates a pair of server certificate and private key using the server CA certificate.
3.  Before creating a peer pod VM, `cloud-api-adaptor` sends the generated server certificate/key as well as client certificate to a newly created pod VM via cloud-init data
4. `agent-protocol-adaptor` starts TLS listener using the server cert/key
5. `cloud-api-adaptor` initiates TLS connection to agent-protocol-forwarder using the client cert/key
6. `agent-protocol-adaptor` validates incoming TLS connection using the client certificate
7. `cloud-api-adaptor` validates the server certificate sent from agent-protocol-forwarder using the server CA certificate

Note that we can still use manual TLS configuration for use cases that the above assumptions are not met.

**Comment by bpradipt** [comment]
@yoheiueda few questions
1. Regarding `cloud-init data is considered as a secure communication channel`
Is this a valid assumption from confidential containers threat model ?

2. For automatic cert generation, can we rely on cert-manager deployed in K8s infrastructure ?

**Comment by yoheiueda** [comment]
> 1. Regarding `cloud-init data is considered as a secure communication channel`
Is this a valid assumption from confidential containers threat model ?

Please note that  `cloud-init data is considered as a secure communication channel` is only from the perspective of worker node. I am NOT saying `cloud-init data` is trusted from the perspective of secure enclaves such as peer pod VMs.

I suppose peer pod VMs are secure enclaves, and worker node VMs are not. In this case,  cloud administrators can access TLS session keys on a worker node, and decrypt TLS communications initiated from it. In other words, from the perspective of worker node, cloud administrators should be trusted.

For other use cases, for example, running worker nodes in secure enclaves as well, the above assumption does not meet, so we can use manual TLS configuration.

> 2. For automatic cert generation, can we rely on cert-manager deployed in K8s infrastructure ?

I am thinking of a simple mechanism that is built into cloud-api-adaptor.  I am preparing a draft PR, and will submit it probably tomorrow.
