### ISSUE TITLE
A provisioner cli for development 

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#731]
Leverage the provision API and the providers support in e2e test framework https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/test/provisioner/provision.go, we provided a very simple CLI https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/cmd/cluster-provisioner/main.go to provision a cluster and deploy the cloud-api-adaptor via operator. We'd like to discuss:

- What's the best place to put the CLI code?
- What actions (parameters) the CLI should accept?
- How to best support all the providers, eg. the UploadPodVM interface when uplaod a qcow2 or native image?
- Document the CLI

Let's discuss the approach in this issue.

**Comment by huoqifeng** [comment]
@bpradipt @stevenhorsman @kartikjoshi21 @mkulke @snir911 Here is the issue for the provisioner CLI.

**Comment by bpradipt** [comment]
> What's the best place to put the CLI code?

Imho, a better location for infra tooling used for CI or occasionally used by developers is `test/infra` or `test/utils`. 
Let's keep the `cmd`, `pkg` folder aligned to the primary functionalities of the project as much as possible. 

> What actions (parameters) the CLI should accept?

This depends on the scope of the tool. From the overall project stand-point creating a cluster is not the primary  functionality, so my personal opinion is to restrict the scope for CI to begin with. 

> How to best support all the providers, eg. the UploadPodVM interface when uplaod a qcow2 or native image?

Most likely the different providers will have different implementations. Uploading qcow2 and creating an AWS AMI or an Azure VM image from it is tedious. So using qcow2 for libvirt (and ibmcloud ?) and using packer for cloud providers. 

> Document the CLI

Great, this will be helpful

**Comment by huoqifeng** [comment]
Maybe, we can move the cli to `test/cli` and document the current usage as 1st step, and then add more incrementally docs while adding more functions/providers.

**Comment by stevenhorsman** [comment]
I re-opened this as I think issues 1 & 4 have been addressed, but we might want to still use this issue to discussion the other points?

**Comment by wainersm** [comment]
Hi @huoqifeng , we might consider renaming the variables like `TEST_E2E_PROVISION_PODVM_IMAGE` to something more generic like `PROVISION_PODVM_IMAGE` as now we got the CLI tool. I was prefixing with `TEST_E2E_` to avoid clash with other variables exported.

**Comment by huoqifeng** [comment]
> Hi @huoqifeng , we might consider renaming the variables like `TEST_E2E_PROVISION_PODVM_IMAGE` to something more generic like `PROVISION_PODVM_IMAGE` as now we got the CLI tool. I was prefixing with `TEST_E2E_` to avoid clash with other variables exported.

@wainersm what about use `TEST_` to replace `TEST_E2E_`? so that we can still avoid conflict as much as possible and keep the variable meaningful?

**Comment by huoqifeng** [comment]
https://github.com/confidential-containers/cloud-api-adaptor/issues/764 and https://github.com/confidential-containers/cloud-api-adaptor/issues/765 created for the open issue, and will close this story for 0.5 CoCo release.
