### ISSUE TITLE
Peer Pod VM build schedule

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#732]
We currently have the GHA workflows [podvm_builder](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/.github/workflows/podvm_builder.yaml) which is triggered when a release is created and [podvm](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/.github/workflows/podvm.yaml) that builds the actual pod vm and pushes it to quay.io which runs after podvm_builder completes.

This means that we don't have regular, up-to-date peer pod vms for developers/ CI/CD pipelines to test with unless they build their own, so we want to consider improving this and more regularly creating the peer pod VM builds, considering the following:
- The peer pod vm build is computationally expensive, but we don't want to build it more often than necessary
- The peer pod VM doesn't depends on all the code in our repo (e.g. the cloud-api-adaptor changes don't affect it), but until we implement [versioning](https://github.com/confidential-containers/cloud-api-adaptor/issues/598), it pulls in new components (notably the kata-agent) outside of our repo, so we can't just rely on `paths` to know when to trigger it at the moment
- Because of the expense in building it, we probably want to have an 'approval' before running the build i.e. a committer/maintainer of the project approving
- We might want to keep our release builds separate from dev builds to provide better clarity/stability to end-users - this might be just via tags in the repo so that the cc runtime for each version is fixed?

Some possible ideas/suggestions:
- Mitigate the expense of the build by throwing more resources at it, so we run it on every PR and merge to the default branch?
- Add a [manual trigger](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) to the podvm_builder workflow. This would let us rebuild the default branch podvm ad-hoc when significant changes go in.
  - We could use the nightly CI/CD processes that we hope to have in place soon to spot breaking changes and then rebuild based on that, but that's quite reactive rather than pro-active
  - We could co-ordinate when significant PRs are merged to pro-actively rebuild
  - The negatives of this approach is that for anyone testing a PR for a peer pod VM image change, they'd still need to create the images manually
- Let committers/maintainers set a label on the PR that would trigger a workflow to be run as part of the PR testing. This is slightly more complicated, but has advantages
  - This could let us proactively produce peer pods vm images for PR testing
  - We'd want to keep PR tests separate from `latest` default branch builds so that people don't accidentally pick up WIP images to test. Maybe we could have a system that builds the commit sha tagged image on the PR and then once the PR is merged updates `latest` to this version?
- Some other suggestion that is better?

**Comment by kartikjoshi21** [comment]
cc @surajssd

**Comment by wainersm** [comment]
This topic is connected with running the e2e tests which I've invested a good time on it. So thanks for bringing this up and tagging me. 
 
> We currently have the GHA workflows [podvm_builder](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/.github/workflows/podvm_builder.yaml) which is triggered when a release is created and [podvm](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/.github/workflows/podvm.yaml) that builds the actual pod vm and pushes it to quay.io which runs after podvm_builder completes.
> 
> This means that we don't have regular, up-to-date peer pod vms for developers/ CI/CD pipelines to test with unless they build their own, so we want to consider improving this and more regularly creating the peer pod VM builds, considering the following:
> 
>     * The peer pod vm build is computationally expensive, but we don't want to build it more often than necessary
> 
>     * The peer pod VM doesn't depends on all the code in our repo (e.g. the cloud-api-adaptor changes don't affect it), but until we implement [versioning](https://github.com/confidential-containers/cloud-api-adaptor/issues/598), it pulls in new components (notably the kata-agent) outside of our repo, so we can't just rely on `paths` to know when to trigger it at the moment
> 
>     * Because of the expense in building it, we probably want to have an 'approval' before running the build i.e. a committer/maintainer of the project approving
> 
>     * We might want to keep our release builds separate from dev builds to provide better clarity/stability to end-users - this might be just via tags in the repo so that the cc runtime for each version is fixed?
> 
> 
> Some possible ideas/suggestions:
> 
>     * Mitigate the expense of the build by throwing more resources at it, so we run it on every PR and merge to the default branch?
> 
>     * Add a [manual trigger](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) to the podvm_builder workflow. This would let us rebuild the default branch podvm ad-hoc when significant changes go in.
>       
>       * We could use the nightly CI/CD processes that we hope to have in place soon to spot breaking changes and then rebuild based on that, but that's quite reactive rather than pro-active

What nightly CI/CD processes do you mean? is it the http://jenkins.katacontainers.io/job/confidential-containers-ci/ that triggers the operator CI jobs on changes on both kata-containers and operator? If so, I didn't understand why a break change would trigger a rebuild of the podvm...unless... are you building on the kata containers' main branch?

>       * We could co-ordinate when significant PRs are merged to pro-actively rebuild
>       * The negatives of this approach is that for anyone testing a PR for a peer pod VM image change, they'd still need to create the images manually
>

I like the manual trigger approach, but thinking about the e2e tests, it doesn't solve the problem. Unless we want to manually trigger the e2e tests, and in this case we won't be testing pre-merge.

On the other hand, this approach can be implemented independently of any other, we just need to ensure the images are tagged properly so that everybody understand how they were generated, if they were tested by CI...etc... 

>     * Let committers/maintainers set a label on the PR that would trigger a workflow to be run as part of the PR testing. This is slightly more complicated, but has advantages
>

For e2e tests I was thinking in use a similar approach: allow committers/maintainers to comment "/test-e2e". Use label works as well, perhaps it is even better because we could have post-merge actions tied with the existence of a label.
 
>       * This could let us proactively produce peer pods vm images for PR testing
>       * We'd want to keep PR tests separate from `latest` default branch builds so that people don't accidentally pick up WIP images to test. Maybe we could have a system that builds the commit sha tagged image on the PR and then once the PR is merged updates `latest` to this version?
>

I kind of created a prototype for that idea already in https://github.com/confidential-containers/cloud-api-adaptor/pull/611 . It builds the podvm and pushes to the github registry with a label that traces the image back to the pull request number. Suppose that a developer opened a PR, a committer tagged the PR as 'test-e2e', the PR was tested and merged, then a post-merge automation could simply push the image to quay.io and delete it from the github registry. There is a caveat though: the PR code base might not be rebased with latest upstream. Suppose PR A and B, A is two commits behind latest, B is one; both are "test-e2e", B gets in first, then A.... clearly the resulting 'latest' podvm image is outdated.   
 
>     * Some other suggestion that is better?

I'm still thinking about this all. I hope this night on the shower I get a good idea :)

**Comment by surajssd** [comment]
> The peer pod VM doesn't depends on all the code in our repo (e.g. the cloud-api-adaptor changes don't affect it), but until we implement [versioning](https://github.com/confidential-containers/cloud-api-adaptor/issues/598), it pulls in new components (notably the kata-agent) outside of our repo, so we can't just rely on `paths` to know when to trigger it at the moment

Can't we rely on the last kata-cc tagged release for this one?

**Comment by stevenhorsman** [comment]
> What nightly CI/CD processes do you mean? is it the http://jenkins.katacontainers.io/job/confidential-containers-ci/ that triggers the operator CI jobs on changes on both kata-containers and operator? If so, I didn't understand why a break change would trigger a rebuild of the podvm...unless... are you building on the kata containers' main branch?

In the absence of the ability to run all our peer pod tests in open-source the 'plan' is for certain providers e.g. IBM to run the peer pod e2e suite every night and then upload the results somewhere open. My suggestion about involving this is that when a change that requires a new podvm to be genned went in - if it wasn't rebuilt then the peer pod e2e test would fail. I hope that helps clarify?

> I like the manual trigger approach, but thinking about the e2e tests, it doesn't solve the problem. Unless we want to manually trigger the e2e tests, and in this case we won't be testing pre-merge.
> 
> On the other hand, this approach can be implemented independently of any other, we just need to ensure the images are tagged properly so that everybody understand how they were generated, if they were tested by CI...etc...

Yes - having the workflow_dispatch trigger on the default branch independently of other triggers is a really simple and helpful backup plan.

> For e2e tests I was thinking in use a similar approach: allow committers/maintainers to comment "/test-e2e". Use label works as well, perhaps it is even better because we could have post-merge actions tied with the existence of a label.


> I kind of created a prototype for that idea already in #611 . It builds the podvm and pushes to the github registry with a label that traces the image back to the pull request number. Suppose that a developer opened a PR, a committer tagged the PR as 'test-e2e', the PR was tested and merged, then a post-merge automation could simply push the image to quay.io and delete it from the github registry. There is a caveat though: the PR code base might not be rebased with latest upstream. Suppose PR A and B, A is two commits behind latest, B is one; both are "test-e2e", B gets in first, then A.... clearly the resulting 'latest' podvm image is outdated.

That's a good point - could we get the sha of the default branch after merging and then look for an image that exists from the PR that merged and if so point to it and otherwise rebuild from the default branch?
