### ISSUE TITLE
regression: peer-pod is failing to establish connection

### ISSUE THREAD

**Issue by snir911** [confidential-containers/cloud-api-adaptor#746]
Failed on normal setup with libvirt, using the publicy available ubuntu podvm image,
This is that only error i saw:
```
Mar 26 11:17:16 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: 2023/03/26 11:17:16 [podnetwork] routes on netns /proc/963/task/986/ns/net
Mar 26 11:17:16 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: 2023/03/26 11:17:16 [podnetwork]     default via 192.168.122.1 dev ens2
Mar 26 11:17:16 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: 2023/03/26 11:17:16 [podnetwork]     192.168.122.1/32  dev ens2
Mar 26 11:17:16 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: 2023/03/26 11:17:16 [util/netops] RouteAdd details: table(0), dest(<nil>), gw(10.244.1.1), dev(vxlan0)
Mar 26 11:17:16 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: 2023/03/26 11:17:16 [util/netops] RouteAdd details: table(0), dest(10.244.0.0/16), gw(10.244.1.1), dev(vxlan0)
Mar 26 11:17:40 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:17:40Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:17:50 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:17:50Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:18:00 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:18:00Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:18:10 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:18:10Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:18:20 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:18:20Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:18:30 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:18:30Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:18:40 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:18:40Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
Mar 26 11:18:50 podvm-fedora-kata-sleep-69bd48b9 agent-protocol-forwarder[963]: time="2023-03-26T11:18:50Z" level=error msg="error receiving message" error="failed to discard after receiving oversized message: EOF"
```

bisecting pointed out this commit: ff8cc10a301226cf2f1104c4fa0a352d3a9565ab
cc @yoheiueda

**Comment by yoheiueda** [comment]
@snir911 Sorry for the inconvenience.

Could you enable the `-disable-tls` option in both `cloud-api-adaptor` and `agent-prococol-forwarder` to avoid the problem for the moment?

https://github.com/confidential-containers/cloud-api-adaptor/blob/eee670fff747727bc29cf8e8f78a1d758bad5d03/cmd/cloud-api-adaptor/main.go#L73
https://github.com/confidential-containers/cloud-api-adaptor/blob/eee670fff747727bc29cf8e8f78a1d758bad5d03/cmd/agent-protocol-forwarder/main.go#L63

How did you set up your libvirt environment and the pod VM image? Did you enable explicit TLS configuration?

If you have a log of `cloud-api-adaptor`, you can find the location of `daemon.json` stored in the worker-node side. Could you share the content of `daemon.json` if possible?

https://github.com/confidential-containers/cloud-api-adaptor/blob/eee670fff747727bc29cf8e8f78a1d758bad5d03/pkg/adaptor/cloud/cloud.go#L248-L253

**Comment by snir911** [comment]
> Could you enable the -disable-tls option in both cloud-api-adaptor and agent-prococol-forwarder to avoid the problem for the moment?

aren't we allow to disable it using environment variable (i.e. by modifying kustomiztion.yaml) ?

> How did you set up your libvirt environment and the pod VM image? Did you enable explicit TLS configuration?

I didn't use explicit TLS configuration, i used the `libvirt/cli_cluster.sh create` to create the cluster (in addition to volume creation and setting ssh-key for authentication) 

> If you have a log of cloud-api-adaptor, you can find the location of daemon.json stored in the worker-node side. Could you share the content of daemon.json if possible?

sure, [daemon.json](https://pastebin.com/m6MMK0Gn)

thanks!

**Comment by snir911** [comment]
In second thought maybe public images weren't updated after this change? I'll try to build a fresh one

**Comment by yoheiueda** [comment]
Is this the image are you using? It looks two months old. The pod VM image  also needs to be updated.

https://quay.io/repository/confidential-containers/podvm-libvirt-centos?tab=tags

**Comment by snir911** [comment]
out-of-date image indeed seems to be the issue, closing for now, sorry for the noise @yoheiueda 
(images update will be triggered upon the pre-release)
