### ISSUE TITLE
pod vm image creation failing with latest ubuntu image

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#753]
Ref image: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
gh-action job - https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/4534666068/jobs/7998000405

cc @jtumber-ibm if you have any idea.

**Comment by jtumber-ibm** [comment]
Without `PACKER_INFO` set, my only guess is it was running too slowly and didn't get to the point where it sets up the `PeerP0D` ssh username and password. As the s390x version, which has a longer boottime set was able to ssh in.

With `failed to push quay.io/confidential-containers/podvm-generic-ubuntu-s390x:latest: unexpected status: 401 UNAUTHORIZED` for s390x is that a expired API key?

**Comment by bpradipt** [comment]
Right. The s390x succeeded and it's available now. I had to fix the permissions.

**Comment by bpradipt** [comment]
Stale issue.
