### ISSUE TITLE
Consolidate provider specific documents under the doc folder

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#78]
Currently the provider specific documentation is in the root of the project. It will be better to consolidate these under the docs folder

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
Closing this as a duplicate of #966
