### ISSUE TITLE
Update the attestation agent built into a peer pod image so it's compatible with the grpc -> ttrpc change in Kata

### ISSUE THREAD

**Issue by mattarnoatibm** [confidential-containers/cloud-api-adaptor#803]
In the kata agent this PR switched the agent from using the gprc feature to the ttrpc feature of image-rs https://github.com/kata-containers/kata-containers/pull/6404.

In the peer pod image image pulls / unpacks fail with 
```
"msg":"pull and unpack image \"registry.k8s.io/pause:3.7\", cid: \"415c599ecaaba4551e7e13571cc2ffd1651df46abbe34a3ab553c25e8562093c\", with image-rs failed with \"ttrpc client init failed\"
```

So we need to investigate if we need to add a newer version of the attestation agent to the peer pod image for the image-rs image pulls to work.

**Comment by bpradipt** [comment]
cc @snir911

**Comment by stevenhorsman** [comment]
I've attempted to bump the attestation-agent in https://github.com/confidential-containers/cloud-api-adaptor/compare/staging...stevenhorsman:cloud-api-adaptor:bump-aa, but I'm still getting the same failure as Matt is seeing and through the e2e test process I can't seem to ssh into my peer pod vm to debug it, so I'll have to try a different approach tomorrow.

**Comment by stevenhorsman** [comment]
The missing piece in my attempted fix is that grpc mode is still the default in the attestation-agent, which I didn't realise, so I updated my PR to enable the ttrpc feature and it's working now.
