### ISSUE TITLE
Reconsider embedding pause container image in pod VM

### ISSUE THREAD

**Issue by yoheiueda** [confidential-containers/cloud-api-adaptor#811]
According to the issue https://github.com/confidential-containers/cloud-api-adaptor/issues/803#issue-1662481625, a pause container image is pull from a remote registry, while we embed a pause container image in the pod VM image.

Previously, a pause container image must be embedded. Otherwise, PullImage fails with error message `Pause image not present in rootfs`. https://github.com/confidential-containers/cloud-api-adaptor/issues/196#issuecomment-1241524111

I think we need to identify the condition when the embedded pause container image is used, and we can remove the embedded image if it is turned out to be no more necessary.

**Comment by bpradipt** [comment]
In CRIO we don't need to embed the pause-image. Jfyi

**Comment by yoheiueda** [comment]
I am not 100% sure, but I think commit ade3125e5417b842b319caaa75877e5dcc8571ae changes the behavior as a side effect.

I think we can force `kata-agent` to use the embedded pause image again if we want by setting `""` in `ContainerId` of `PullImageRequest` only for `pause` container.

We can simplify the build process of the pod VM image, if we remove the embedded pause image.

On the other hand, one benefit of embedding a pause image in the pod VM image is that we can use a trusted pause container image. If `kata-agent` pulls a pause image from a public registry, we need to validate it in some way.

**Comment by bpradipt** [comment]
With latest changes to kata/main, pause image needs to be embedded in guest rootfs
