### ISSUE TITLE
Feature Request - can we obfuscate the API key in cloud-api-adaptor ?

### ISSUE THREAD

**Issue by davidhay1969** [confidential-containers/cloud-api-adaptor#83]
At present the API key is visible in the process listing: -

`ps -ef | grep cloud-api-adaptor`

```text
root     22197     1  0 Jul05 ?        00:00:11 /usr/local/bin/cloud-api-adaptor ibmcloud -api-key <<REDACTED>> -iam-service-url https://iam.cloud.ibm.com/identity/token -vpc-service-url https://jp-tok.iaas.cloud.ibm.com/v1 -key-id r022-80727076-b53b-4f7c-a7b3-96ef9b367ce5 -image-id r022-fe40596b-7cb4-4a37-afee-539c1fb25b61 -profile-name bz2-2x8 -zone-name jp-tok-2 -primary-subnet-id 02f7-13efe926-25f5-4ec6-b09c-aaeed55bebcb -primary-security-group-id r022-b48f040f-4ffc-45b1-8bd2-ac58b08bbaf6 -vpc-id r022-95078f9c-8ba8-482d-b9af-cfed7cf70abf -pods-dir /run/peerpod/pods -socket /run/peerpod/hypervisor.sock
```

and the logs: -

`cat /var/log/cloud-api-adaptor.log`

```text
cfg: &main.daemonConfig{helperDaemonRoot:"", httpTunnelTimeout:"", TunnelType:"vxlan", HostInterface:""}; hypcfg: hypervisor.Config{SocketPath:"/run/pe
erpod/hypervisor.sock", PodsDir:"/run/peerpod/pods", HypProvider:"ibmcloud"}
2022/07/05 20:09:57 [helper/hypervisor] hypervisor config {/run/peerpod/hypervisor.sock /run/peerpod/pods ibmcloud}
2022/07/05 20:09:57 [helper/hypervisor] cloud config {<<REDACTED>> https://iam.cloud.ibm.com/identity/token https://jp-
tok.iaas.cloud.ibm.com/v1  bz2-2x8 jp-tok-2 r022-fe40596b-7cb4-4a37-afee-539c1fb25b61 02f7-13efe926-25f5-4ec6-b09c-aaeed55bebcb r022-b48f040f-4ffc-45b1
-8bd2-ac58b08bbaf6   r022-80727076-b53b-4f7c-a7b3-96ef9b367ce5 r022-95078f9c-8ba8-482d-b9af-cfed7cf70abf}
2022/07/05 20:09:57 [helper/hypervisor] service config &{<<REDACTED>> https://iam.cloud.ibm.com/identity/token https://
jp-tok.iaas.cloud.ibm.com/v1  bz2-2x8 jp-tok-2 r022-fe40596b-7cb4-4a37-afee-539c1fb25b61 02f7-13efe926-25f5-4ec6-b09c-aaeed55bebcb r022-b48f040f-4ffc-4
5b1-8bd2-ac58b08bbaf6   r022-80727076-b53b-4f7c-a7b3-96ef9b367ce5 r022-95078f9c-8ba8-482d-b9af-cfed7cf70abf}
2022/07/05 20:10:53 [util/netops] route (dst:172.20.0.0/24, gw:172.20.0.0: dev:flannel.1) has unexpected flags 4. ignoring
```

which is a potential security concern, especially when demonstrating CAA or sharing the logs.

Is there any way in which we can obfuscate / obscure the API key in either/both places ?

**Comment by bpradipt** [comment]
Will this get resolved once the binary is run as a container and the parameters made available via env variables ? - https://github.com/confidential-containers/cloud-api-adaptor/pull/62

**Comment by davidhay1969** [comment]
Good question

**Comment by yoheiueda** [comment]
I think we need to mask API key in debug logs.

https://github.com/confidential-containers/cloud-api-adaptor/blob/a41a38c74df6a25643e9e863a545cb11b8c8b31f/pkg/adaptor/hypervisor/ibmcloud/server.go#L39
https://github.com/confidential-containers/cloud-api-adaptor/blob/a41a38c74df6a25643e9e863a545cb11b8c8b31f/pkg/adaptor/hypervisor/aws/server.go#L36
https://github.com/confidential-containers/cloud-api-adaptor/blob/a41a38c74df6a25643e9e863a545cb11b8c8b31f/pkg/adaptor/hypervisor/libvirt/server.go#L39

**Comment by davidhay1969** [comment]
If it helps, I'm happy to have a go at this @yoheiueda and PR it in ....

**Comment by yoheiueda** [comment]
@davidhay1969 yes, it should be fixed, and I'd appreciate if could fix it.

**Comment by davidhay1969** [comment]
Apologies for the delay, working on a mitigation for this, just about to retest with the most recent version of the `staging` branch, before raising a PR ... 🤞

**Comment by davidhay1969** [comment]
So I've updated [types.go](https://github.com/davidhay1969/cloud-api-adaptor/blob/obfuscate_api_key_ibmcloud/pkg/adaptor/hypervisor/ibmcloud/types.go) in my own fork/branch of the CAA repo, with a view to obfuscating the API key in the logs.

With this in place, I no longer see the API key in the logs, as per the following example: -

`cat /var/log/cloud-api-adaptor.log`

```text
cfg: &main.daemonConfig{helperDaemonRoot:"", httpTunnelTimeout:"", TunnelType:"vxlan", HostInterface:""}; hypcfg: hypervisor.Config{SocketPath:"/run/peerpod/hypervisor.sock", PodsDir:"/run/peerpod/pods", HypProvider:"ibmcloud"}
2022/07/15 22:38:11 [helper/hypervisor] hypervisor config {/run/peerpod/hypervisor.sock /run/peerpod/pods ibmcloud}
2022/07/15 22:38:11 [helper/hypervisor] cloud config {******** https://iam.cloud.ibm.com/identity/token r022-aac9a237-c1ef-47b2-a669-54ea0ceffb54 r022-827b6c6e-e3dd-4872-92ab-acd84d8c042e r022-0f81e5a1-7b26-4d52-90ab-91607f6dbd37 02f7-1f91f675-1429-49ea-8501-4aba057e1c2a bz2-2x8 618f9f59a78841c690648eaa1db5c90e   r022-cf50980e-1d97-407e-944e-8554ba3a1c3b https://jp-tok.iaas.cloud.ibm.com/v1 jp-tok-2}
2022/07/15 22:38:11 [helper/hypervisor] service config {******** https://iam.cloud.ibm.com/identity/token r022-aac9a237-c1ef-47b2-a669-54ea0ceffb54 r022-827b6c6e-e3dd-4872-92ab-acd84d8c042e r022-0f81e5a1-7b26-4d52-90ab-91607f6dbd37 02f7-1f91f675-1429-49ea-8501-4aba057e1c2a bz2-2x8 618f9f59a78841c690648eaa1db5c90e   r022-cf50980e-1d97-407e-944e-8554ba3a1c3b https://jp-tok.iaas.cloud.ibm.com/v1 jp-tok-2}
```

I've chosen a string of asterisks, but this could be anything we wish to use e.g. `REDACTED` etc.

All opinions gratefully received @jtumber-ibm @stevenhorsman @yoheiueda 

If this looks OK, I'll create a PR for this change, and then do the same for the AWS equivalent - [types.go](https://github.com/davidhay1969/cloud-api-adaptor/blob/obfuscate_api_key_ibmcloud/pkg/adaptor/hypervisor/aws/types.go) which uses `SecretKey` and, perhaps `AccessKeyId` ?

**Comment by davidhay1969** [comment]
With some very kind feedback from @jtumber-ibm I've amended the newly added `String()` function to **only** mask the API key, and also added `types_test.go` to actually test the change ( again thanks to JT )

I've opened a PR - [ibmcloud: Obfuscate API key in log file #103](https://github.com/confidential-containers/cloud-api-adaptor/pull/103) - and waiting for the tests to run ....

**Comment by jtumber-ibm** [comment]
Hi @yoheiueda, should this issue be reopened as the `ps -ef` issue has not been solved. Or create a new issue to introduce environment variable approach for api/sensitive keys?

**Comment by yoheiueda** [comment]
@jtumber-ibm thank you very much for letting me know it. I reopened this issue.
