### ISSUE TITLE
Allow image pull when enabled istio iptables in PeerPod

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#86]
Image pull will fail after injected istio in the PeerPod as the istio-init initContainer will add iptable rules as below:
```
huoqifengs-mbp:demo huoqifeng$ kubectl logs -f nginx-dc6c49ff7-2wz5w -c istio-init
2022-07-08T05:47:38.465049Z	info	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=

2022-07-08T05:47:38.465090Z	info	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
EXCLUDE_INTERFACES=

2022-07-08T05:47:38.465215Z	info	Writing following contents to rules file: /tmp/iptables-rules-1657259258465135802.txt3189668010
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2022-07-08T05:47:38.466087Z	info	Running command: iptables-restore --noflush /tmp/iptables-rules-1657259258465135802.txt3189668010
2022-07-08T05:47:38.501100Z	info	Writing following contents to rules file: /tmp/ip6tables-rules-1657259258501061480.txt891300661

2022-07-08T05:47:38.501115Z	info	Running command: ip6tables-restore --noflush /tmp/ip6tables-rules-1657259258501061480.txt891300661
2022-07-08T05:47:38.502157Z	info	Running command: iptables-save
2022-07-08T05:47:38.504687Z	info	Command output:
# Generated by iptables-save v1.8.4 on Fri Jul  8 05:47:38 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Fri Jul  8 05:47:38 2022
```

We need set iptable rules to still allow images pull with istio iptables rules injected in PeerPod VM

**Comment by huoqifeng** [comment]
@yoheiueda do you feel the istio iptables impact tunnel between worker and peerpod besides image pull?

**Comment by yoheiueda** [comment]
@huoqifeng 

Yes.
All TCP connections coming from the outside of the pod, or initiated from processes running in the pod are redirected to the Istio process.

**Comment by yoheiueda** [comment]
We can pull images in the host network namespace instead of the `podns` network namespace by running the `skopeo` command in the host network namespace.

In the host network namespace, run
```
ln -s /proc/1/ns/net /run/netns/hostns
```

Then, in the `podns` network namespace, we can run a command in the host network namespace.
```
ip netns exec hostns command
```

To run the `skopeo` command in the host network namespace, we rename the command to another name
```
mv /usr/local/bin/skopeo /usr/local/bin/skopeo.orig
```
Then, prepare a small shell script `/usr/local/bin/skopeo` as like this.
```
#!/bin/bash
exec ip netns exec hostns /usr/local/bin/skopeo.orig "$@"
```

`kata-agent` invokes this script to pull images, so image pulling will be done out side of the `podns` network namespace.

**Comment by yoheiueda** [comment]
@huoqifeng I raised PR #107 to fix this issue.

**Comment by huoqifeng** [comment]
@yoheiueda I heard there is ongoing work to replace skopeo with image-rs, is image-rs a kind of rust package rather than binary? will this approach still valid? I think @stevenhorsman know more details regard image-rs. I'll reopen it and wait for @stevenhorsman  comments to avoid it's ignored until end time. @stevenhorsman may you please comments on this issue? Maybe just close it if image-rs plan is not in near term or it will not impact this approach.

**Comment by huoqifeng** [comment]
oh, I just realized I don't have permission to reopen it yet :-)

**Comment by liudalibj** [comment]
Reopen this issue, as there are still some ongoing discuss.

**Comment by yoheiueda** [comment]
@huoqifeng I've also heard of it. The skopeo wrapper approach does not work if image pull mechanism is built into a single binary.

As described in the comment of the script, the wrapper approach is intended to be a temporary solution.
https://github.com/confidential-containers/cloud-api-adaptor/blob/b5ecb837f63dab71abf2b22d9f4cd729ea132271/ibmcloud/image/files/usr/bin/skopeo#L20-L22

The problem of network namespace separation affects multiple consideration points including image pull.

I will raise an issue about the problem of network namespace separation of kata-agent, and summarize some discussion points.

BTW, could you check whether this patch fixes the interference of image pulls due to iptables rules set by the init container?

**Comment by yoheiueda** [comment]
I raised https://github.com/confidential-containers/cloud-api-adaptor/issues/109

**Comment by huoqifeng** [comment]
> I raised #109

I'm happy to close this as https://github.com/confidential-containers/cloud-api-adaptor/issues/109 is created to trace the root cause and will give a reasonable solution.
