### ISSUE TITLE
Add peerpodconfig-ctrl and peerpod-ctrl into operator

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#872]
We've created peerpodconfig-ctrl and peerpod-ctrl to help manage VM resources we create for peer pods. Once we've done the work in https://github.com/confidential-containers/cloud-api-adaptor/issues/871 (and pre-reqs) to move to the coco operator and away from our forks, we should consider adding the deployment of these controllers into the cluster.

**Comment by bpradipt** [comment]
This should include webhook as well.. Updating the issue title accordingly

**Comment by bpradipt** [comment]
@caavery is working on it and hence changing the status to in-progress

**Comment by ariel-adam** [comment]
@caavery do you think this will converge for release 0.7.0 Feature freeze on 12th of July (GA on the 19th) or should we move this to release 0.8.0?

**Comment by caavery** [comment]
It should be moved to 0.8.0 as it will not be ready for 0.7.0.

**Comment by surajssd** [comment]
The concern I have with adding components from CAA to operator is introducing cyclical dependency.

CAA depends on operator to install all the necessary components. And installing stuff that CAA owns from the parent introduces cyclical dependency.

Also this will make the release harder. As in we first cut a release of operator and use that tag in CAA. But by making this change we don't know which release to cut when?

**Comment by bpradipt** [comment]
@surajssd any suggestions to avoid this dep?
Should we move the controllers to a separate repo (eg addon-controllers) since the controllers import CAA module? So release sequence may look like
1. Create CAA release
2. Create peerpod/peerpodconfig release
3. Create operator release

**Comment by bpradipt** [comment]
cc @stevenhorsman

**Comment by stevenhorsman** [comment]
So, I think that makes sense, if the peer-pod ctrl is added to the operator.
There is also a code cyclic dependency we have at the moment is that [peerpod-ctrl depends on cloud-api-adaptor](https://github.com/confidential-containers/cloud-api-adaptor/blob/aedfc751c71a24df948ab41806f66eaa6e82d8b3/peerpod-ctrl/go.mod#L6), but [cloud-api-adaptor also depends on peerpod-ctrl](https://github.com/confidential-containers/cloud-api-adaptor/blob/aedfc751c71a24df948ab41806f66eaa6e82d8b3/go.mod#L48), so I think we might want to think about that as well before doing any separation?

**Comment by surajssd** [comment]
> @surajssd any suggestions to avoid this dep? Should we move the controllers to a separate repo (eg addon-controllers) since the controllers import CAA module?

We can move the code out yes.

> So release sequence may look like
> 
> 1. Create CAA release
> 2. Create peerpod/peerpodconfig release
> 3. Create operator release

Isn't the order upside down, with operator release being the first to go out?

**Comment by caavery** [comment]
I've created a draft PR at https://github.com/confidential-containers/operator/pull/249

**Comment by caavery** [comment]
Is there a corresponding issue for operator?

**Comment by caavery** [comment]
@bpradipt @jensfr 

This issue has been fixed in https://github.com/confidential-containers/operator/pull/249

**Comment by stevenhorsman** [comment]
Pradipta merged this this under https://github.com/confidential-containers/operator/pull/349
