### ISSUE TITLE
ibmcloud: Create a SE enabled peer pod image in the docker and packer based peer pod image build on IBM Cloud VPC

### ISSUE THREAD

**Issue by liudalibj** [confidential-containers/cloud-api-adaptor#877]
Currently we can create a SE enable peer pod image by follow [the document](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/ibmcloud/SECURE_EXECUTION.md).
It's using the scripts under [ibmcloud/image](https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud/image) which is not consistency with the way `using docker and packer` to [build podvm](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/podvm/README.md).

We need update the old create SE enabled peer pod image to use `the docker and packer `

**Comment by yoheiueda** [comment]
@liudalibj I think it is a good idea to migrate to packer.

Do you know whether packer supports building images for SE?

**Comment by liudalibj** [comment]
> @liudalibj I think it is a good idea to migrate to packer.
> 
> Do you know whether packer supports building images for SE?
@yoheiueda I used the provision shell to implement the SE-Build, the pr is created https://github.com/confidential-containers/cloud-api-adaptor/pull/880
