### ISSUE TITLE
azure: packer podvm image build fails due to missing privileges

### ISSUE THREAD

**Issue by katexochen** [confidential-containers/cloud-api-adaptor#925]
When building podvm images with docker, packer fails due to missing privileges:

```
#12 0.868 ==> peer-pod-ubuntu.azure-arm.ubuntu: Running builder ...
#12 0.868 ==> peer-pod-ubuntu.azure-arm.ubuntu: Getting tokens using client secret
#12 1.064 Build 'peer-pod-ubuntu.azure-arm.ubuntu' errored after 195 milliseconds 936 microseconds: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'xxx'.\r\nTrace ID: xxx\r\nCorrelation ID: xxx\r\nTimestamp: 2023-05-10 14:35:20Z","error_codes":[7000215],"timestamp":"2023-05-10 14:35:20Z","trace_id":"xxx","correlation_id":"xxx","error_uri":"https://login.microsoftonline.com/error?code=7000215"} Endpoint https://login.microsoftonline.com/xxx/oauth2/token?api-version=1.0
```

[Packer documentation](https://developer.hashicorp.com/packer/plugins/builders/azure/arm#service-principal) states it needs Owner privileges on the resource group:

> The service principal specified in client_id must have full access to this subscription, unless build_resource_group_name option is specified in which case it needs to have owner access to the existing resource group specified in build_resource_group_name parameter.

**Comment by surajssd** [comment]
From the error what I understand is that the secrets that were provided were either corrupt or something like that. For lesser privileges we would have gotten an error that would have specifically pointed out that you cannot create x and y resource under a & b scope. The authorization errors are different from what we see in the aforementioned output.

**Comment by katexochen** [comment]
The cause for this issue seems to be timing/caching. Waiting ~10 min after service principal creation solved the issue for me.
