### ISSUE TITLE
Run kata-agent process in root namespace on Peer Pod VM

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#94]
We are trying to run a csi driver container on Peer Pod VM, It requires to mount a volume with mount progatation as true:
```
volumeMounts:
        - mountPath: /data
          mountPropagation: Bidirectional
          name: kubelet-data-dir
...
volumes:
    - hostPath:
        path: /root/data
        type: Directory
      name: kubelet-data-dir
```
About [Mount propagation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation), if it's set as **Bidirectional**, "all volume mounts created by the container will be propagated back to the host and to all containers of all pods that use the same volume."

However, Bidirectional doesn't work as expected. The CSI driver container mounts a device under the volume mount path /data, the mount info can't be found on host.

If creating it as a normal pod, Bidirectional works as expected, the device mount info is also visible on host.

----

According to our investigation, the root cause is currently **kata-agent** process on Peer Pod VM is running in new network namespace and mount namespace, because it's started with `ip netns exec`:
```
[Service]
ExecStart=ip netns exec podns /usr/local/bin/cgroup-exec /usr/local/bin/kata-agent
ExecStartPre=ip netns add podns
ExecStartPre=ip netns exec podns ip link set lo up
ExecStopPost=ip netns delete podns
Environment="KATA_AGENT_SERVER_ADDR=unix:///run/kata-containers/agent.sock"
```

namespaces on Peer Pod VM:
```
# lsns
        NS TYPE   NPROCS   PID USER             COMMAND
4026531835 cgroup    111     1 root             /sbin/init
4026531836 pid       109     1 root             /sbin/init
4026531837 user      111     1 root             /sbin/init
4026531838 uts       106     1 root             /sbin/init
4026531839 ipc       109     1 root             /sbin/init
4026531840 mnt       100     1 root             /sbin/init
4026532243 mnt         1   708 root             /usr/local/bin/kata-agent
4026532301 net         3   708 root             /usr/local/bin/kata-agent
4026532253 pid         1  1481 root             /home/ibm-csi-drivers/ibm-vpc-block-csi-driver
4026532254 mnt         1  1481 root             /home/ibm-csi-drivers/ibm-vpc-block-csi-driver
```

The problem is, `ip netns exec` will create a new mount namespace for kata-agent process, checking with **strace** below:
```
# strace -e unshare,mount  ip netns add ns1
mount("", "/run/netns", 0x55697318867f, MS_REC|MS_SHARED, NULL) = 0
unshare(CLONE_NEWNET)                   = 0
mount("/proc/self/ns/net", "/run/netns/ns1", 0x55697318867f, MS_BIND, NULL) = 0
+++ exited with 0 +++
# strace -e unshare,mount ip netns exec ns1 sleep 3600
unshare(CLONE_NEWNS)                    = 0
mount("", "/", 0x55a066feb67f, MS_REC|MS_SLAVE, NULL) = 0
mount("ns1", "/sys", "sysfs", 0, NULL)  = 0
```

`unshare(CLONE_NEWNS)` will create a new mount namespace, and then set mount propagation as **MS_SLAVE** from "/" recursively

Because **kata-agent** is running in a new mount namespace, and the propagation is set as **slave**, it prevents the mount propagation works in container mount namespace. The mount changes in container mount namespace can't be shared to other mount namespace, so Mount propagation Bidirectional doesn't work as expected for peer pod.

To resolve this problem, we need kata-agent process is running in root namespace on Peer Pod VM.

**Comment by huoqifeng** [comment]
I think it's same requirements for https://github.com/confidential-containers/cloud-api-adaptor/issues/86

**Comment by yoheiueda** [comment]
I think there are two options to go forward.

Option 1: Use `unshare` to access the 'podns' network namesapce, instead of using `ip netns exec`
Option 2: Use systemd service to launch the driver, instead of using a sidecar container

The behavior of `ip netns exec` regarding mnt namespace is documented.

https://man7.org/linux/man-pages/man8/ip-netns.8.html#DESCRIPTION

>         For applications that are aware of network namespaces, the
>        convention is to look for global network configuration files
>        first in /etc/netns/NAME/ then in /etc/.  For example, if you
>        want a different version of /etc/resolv.conf for a network
>        namespace used to isolate your vpn you would name it
>        /etc/netns/myvpn/resolv.conf.
> 
>        ip netns exec automates handling of this configuration, file
>        convention for network namespace unaware applications, by
>        creating a mount namespace and bind mounting all of the per
>        network namespace configure files into their traditional location
>        in /etc.

The `unshare` command provides more options to control namespaces, so I guess we can use this command to access the `podns`network namespace only.
https://man7.org/linux/man-pages/man1/unshare.1.html

If the option 2 is a feasible one, I think it makes things much simpler.

**Comment by huoqifeng** [comment]
@yoheiueda I think there are 2 advantages for Option 1:
- It's easy to place new CSI drivers in the PeerPod as its via container and can be added by webhook or in the yaml directly.
- It's easy for the CSI wrapper to talk to api-server with right permission by leverage the token mounted to the container.

**Comment by yoheiueda** [comment]
@genjuro214 @huoqifeng I noticed that `nsenter` is an appropriate command for our purpose.

I raised a PR to use this command instead of `ip netns exec`. Could you confirm this patch fixes your issue?

**Comment by genjuro214** [comment]
@yoheiueda , that's a good idea.

However, after applying the patch, the container can not be running.

On the peer pod VM, both kata-agent and agent-protocol-forwarder are running:
```
# ps aux | grep kata-agent
root         670  0.0  0.0 707880  5524 ?        Ssl  01:15   0:00 /usr/local/bin/agent-protocol-forwarder -host-interface ens4 -kata-agent-namespace /run/netns/podns -kata-agent-socket @/run/kata-containers/agent.sock
root         712  0.4  0.0  37208  8016 ?        Ssl  01:15   0:00 /usr/local/bin/kata-agent
```

But there is an error in **agent-protocol-forwarder** logs:
```
# systemctl status agent-protocol-forwarder.service --no-pager -l
● agent-protocol-forwarder.service - Agent Protocol Forwarder
     Loaded: loaded (/etc/systemd/system/agent-protocol-forwarder.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-07-18 01:15:12 UTC; 1min 10s ago
   Main PID: 670 (agent-protocol-)
      Tasks: 7 (limit: 9508)
     Memory: 7.2M
     CGroup: /system.slice/agent-protocol-forwarder.service
             └─670 /usr/local/bin/agent-protocol-forwarder -host-interface ens4 -kata-agent-namespace /run/netns/podns -kata-agent-socket @/run/kata-containers/agent.sock

Jul 18 01:15:12 cdlleili-peer-worker-default-busybox-a8d97c12 systemd[1]: Started Agent Protocol Forwarder.
Jul 18 01:15:13 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:13 [podnetwork] routes on netns /proc/670/task/699/ns/net
Jul 18 01:15:13 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:13 [podnetwork]     default via 10.240.64.1 dev ens3
Jul 18 01:15:13 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:13 [podnetwork]     10.240.64.1/32  dev ens3
Jul 18 01:15:13 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:13 [util/netops] RouteAdd details: table(0), dest(<nil>), gw(172.20.1.1), dev(vxlan0)
Jul 18 01:15:13 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:13 [util/netops] RouteAdd details: table(0), dest(172.20.0.0/16), gw(172.20.1.1), dev(vxlan0)
Jul 18 01:15:14 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:14 error connecting to kata agent socket: failed to call dialer at namespace "/run/netns/podns": dial unix @/run/kata-containers/agent.sock: connect: connection refused (retrying)
Jul 18 01:15:24 cdlleili-peer-worker-default-busybox-a8d97c12 agent-protocol-forwarder[670]: 2022/07/18 01:15:24 [daemon/agent] error copying connection from agent to shim: readfrom tcp 10.240.64.9:15150->10.240.64.5:35362: splice: connection reset by peer
```

Can you have a look?

**Comment by yoheiueda** [comment]
@genjuro214 thank you very much for confirming that the patch is functional.

Please raise another issue if you identify another problem that blocks your driver work.

**Comment by genjuro214** [comment]
Yes, the patch works for the mount progatation problem.

The new problem is for **privilleged: true**. I once have some patch to resolve the errors caused by privilleged as true for container on peer pod, but it doesn't work because of the new commit [runtime: Support the remote hypervisor type](https://github.com/confidential-containers/cloud-api-adaptor/issues/94), I think. I tried a quick fix so that the pod with privilleged true can be running. I'll raise another issue to track the problem for **privilleged: true**.

Anyway, for the mountPropagation issue, after applying @yoheiueda 's fix above, it works now.

I tried to mount a device **vdd** to the path under the volume /data with **mountPropagation Bidirectional**, in the container namespace:
```
# nsenter -a -t 1468 sh
# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop1     7:1    0 67.8M  1 loop
vdd     252:48   0   10G  0 disk /data/mnt
vdb     252:16   0  372K  0 disk
loop2     7:2    0   47M  1 loop
loop0     7:0    0 61.9M  1 loop
vdc     252:32   0   44K  0 disk
vda     252:0    0  100G  0 disk
├─vda15 252:15   0  106M  0 part
├─vda1  252:1    0 99.9G  0 part
└─vda14 252:14   0    4M  0 part
```

Now the mount info can also be found in the root namespace:
```
~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 61.9M  1 loop /snap/core20/1518
loop1     7:1    0 67.8M  1 loop /snap/lxd/22753
loop2     7:2    0   47M  1 loop /snap/snapd/16292
vda     252:0    0  100G  0 disk
├─vda1  252:1    0 99.9G  0 part /
├─vda14 252:14   0    4M  0 part
└─vda15 252:15   0  106M  0 part /boot/efi
vdb     252:16   0  372K  0 disk
vdc     252:32   0   44K  0 disk
vdd     252:48   0   10G  0 disk /run/kata-containers/shared/containers/2ee199e572474713c1dbe43c420b9bb737eb96f04d1d1c3e52fb211a29772cba-cbd4bc7316434d18-data/mnt
```
