### ISSUE TITLE
Add e2e tests for AWS

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#956]
Currently e2e test exists for Azure, Ibmcloud and libvirt. This issue is to track the work required to add e2e tests for AWS

https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/test/e2e

**Comment by wainersm** [comment]
Hi @bpradipt, we will have an intern starting at June 19th, developing his activities under my supervision. I wanted to assign him this work. Is it okay for you?

**Comment by ariel-adam** [comment]
@wainersm @bpradipt @jensfr let's consider moving this E2E CI to Azure instead of AWS given that we will have budget issues for AWS (and not for Azure)
