### ISSUE TITLE
podvm: building podvm binaries with `AA_KBC=cc_kbc_az_snp_vtpm` fails using docker

### ISSUE THREAD

**Issue by katexochen** [confidential-containers/cloud-api-adaptor#983]
```
$ cd podvm
$ DOCKER_BUILDKIT=1 docker build -f Dockerfile.podvm_binaries --build-arg AA_KBC=cc_kbc_az_snp_vtpm .
...
#9 520.0 error: failed to run custom build command for `tss-esapi-sys v0.4.0`
#9 520.0 
#9 520.0 Caused by:
#9 520.0   process didn't exit successfully: `/attestation-agent/target/release/build/tss-esapi-sys-a1e3fe1f3dab1805/build-script-build` (exit status: 101)
#9 520.0   --- stdout
#9 520.0   cargo:rerun-if-env-changed=TSS2_SYS_NO_PKG_CONFIG
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-musl
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_musl
#9 520.0   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-musl
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_musl
#9 520.0   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
#9 520.0   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
#9 520.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
#9 520.0 
#9 520.0   --- stderr
#9 520.0   thread 'main' panicked at 'Failed to find tss2-sys library.: pkg-config has not been configured to support cross-compilation.
#9 520.0 
#9 520.0   Install a sysroot for the target platform and configure it via
#9 520.0   PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
#9 520.0   cross-compiling wrapper for pkg-config and set it via
#9 520.0   PKG_CONFIG environment variable.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tss-esapi-sys-0.4.0/build.rs:42:14
```

**Comment by katexochen** [comment]
I've tried to `apt install libtss2-dev`, but that didn't help. Has anyone an idea how to fix this?

**Comment by katexochen** [comment]
So the problem here is we are missing to set `PKG_CONFIG_SYSROOT_DIR=/` for musl builds.

 Also, the builder is missing the `libtss2-sys` library, as we don't install it, and we cannot get it from apt in the required version ( `Requested 'tss2-sys >= 2.3.3' but version of tss2-sys is 2.3.2` ). We could upgrade Ubuntu to 22.04 to get `libtss2-sys` at v3.2.0. [All versions of `tss-esapi-sys` seem to require >= 2.3.3](https://crates.io/crates/tss-esapi-sys), so we cannot downgrade the crate instead.

**Comment by katexochen** [comment]
My current changes are at https://github.com/confidential-containers/cloud-api-adaptor/compare/main...katexochen:cloud-api-adaptor:fix/makearch

Opinions on upgrading Ubuntu @mkulke @stevenhorsman @bpradipt ?

**Comment by stevenhorsman** [comment]
> Opinions on upgrading Ubuntu @mkulke @stevenhorsman @bpradipt ?

We tried using a ubuntu 22.04 podvm a few months ago and couldn't get it working due to cgroup v2 issues, but I've seen some fixes for cgroup v2 in kata since then, so it might be working again now?

**Comment by mkulke** [comment]
also I would recommend to compile support for all attesters, otherwise we'll get to big confusing matrix of possible permutations (os X arch X attester X ...)

**Comment by katexochen** [comment]
Sounds good to me.

**Comment by bpradipt** [comment]
> The default for azure's packer build is 22.04 already, I don't think there are issues.
> 
> I'm not sure it's worth fixing the musl build for peerpod's since we have a full base-os here. I did some gymnastics to get to a working static binary on Ubuntu, but then it wasn't portable on RHEL.

Also we have used RHEL9 and CentOS9 as well which is cgroupv2. And I agree on not spending time to fix musl build.

**Comment by katexochen** [comment]
> also I would recommend to compile support for all attesters, otherwise we'll get to big confusing matrix of possible permutations (os X arch X attester X ...)

You mean in general? Is this possible with `offline_fs_kbc` or does that mean switching to `cc_kbc` per default?

**Comment by mkulke** [comment]
Yes, Attesters exist only in `kbc_cc`, but there should be no harm if `kbc_cc` is compiled into the attestation-agent, my reading from that code is that they are supposed to sit alongside and do not interfere with each other:

```rust
impl KbcModuleList {
    /// Create a new [KbcModuleList] and register all known KBC modules.
    pub fn new() -> KbcModuleList {
        let mut mod_list = HashMap::new();

        #[cfg(feature = "sample_kbc")]
        {
            let instantiate_func: KbcInstantiateFunc = Box::new(|kbs_uri: String| -> KbcInstance {
                Box::new(sample_kbc::SampleKbc::new(kbs_uri))
            });
            mod_list.insert("sample_kbc".to_string(), instantiate_func);
        }

        #[cfg(feature = "cc_kbc")]
        {
            let instantiate_func: KbcInstantiateFunc = Box::new(|kbs_uri: String| -> KbcInstance {
                Box::new(cc_kbc::Kbc::new(kbs_uri).unwrap())
            });
            mod_list.insert("cc_kbc".to_string(), instantiate_func);
        }
        ...
}
```

and if I understand correctly, specifying a `KBC` to AA's Makefile will just add that to the `default` feature, which is `sample-kbc`, so there are 2 kbc impl's in an AA build.

https://github.com/confidential-containers/cloud-api-adaptor/blob/5997d8183cab6a883e5bd763301ce17425642989/podvm/Makefile.inc#L144

fwiw, when I run image-rs tests and enable an additional kbc module `--feature attestation_agent/cc_kbc` (the tests use `offline_fs_kbc`) there's no breakage.

**Comment by mkulke** [comment]
should be fixed by now
