### ISSUE TITLE
Publish Azure pod vm images to be consumed directly

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#986]
Right now we publish the CAA container images, also publish the podvm images to be directly consumable by an user without building it from scratch.

**Comment by surajssd** [comment]
We can use this feature to publish pod vm images: https://learn.microsoft.com/en-gb/azure/virtual-machines/azure-compute-gallery#community-gallery

**Comment by katexochen** [comment]
Jerimi implemented the possibility to use community gallery images in https://github.com/confidential-containers/cloud-api-adaptor/pull/1202, I guess the next step would be to publish images there from the CI.

**Comment by mkulke** [comment]
they are being published
