### ISSUE TITLE
Allow private image pull

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#99]
In IKS managed cluster, istio is saved in ICR IBM Cloud Registry which requires image pull credentials when pull the istio sidecar images in PeerPod, I'd like we support private image pull in PeerPod so that IKS istio can be supported.

**Comment by yoheiueda** [comment]
Image registry credentials are supported when we use the custom containerd.
https://github.com/confidential-containers/containerd/tree/CC-main

**Comment by yoheiueda** [comment]
Sorry, I was wrong.

The custom containerd and kata CCv0 do not support image pulling with registry credentials.

https://github.com/confidential-containers/containerd/blob/4b12e77e79dccebba54e0ec91cc24d6a51a85fa6/pkg/cri/services/cc/service.go#L984-L1001
```
func (cc *ccService) PullImage(ctx context.Context, r *runtime.PullImageRequest) (*runtime.PullImageResponse, error) {
	log.G(ctx).Debugf("cc service pull image, req: %v", r)
	name := server.MakeSandboxName(r.SandboxConfig.GetMetadata())
	sandboxID := cc.SandboxNameIndex.GetKeyByName(name)


	req := &task.PullImageRequest{}
	if r.Image != nil {
		req.Image = r.Image.Image
	}
	resp, err := cc.v2Runtime.PullImage(ctx, sandboxID, req)
	if resp != nil {
		ret := &runtime.PullImageResponse{
			ImageRef: resp.ImageRef,
		}
		return ret, err
	}
	return nil, err
}
```

https://github.com/kata-containers/kata-containers/blob/da7ba2ef71152281452e667d4a37d81405af5095/src/libs/protocols/protos/image.proto#L27-L31
```
message PullImageResponse {
    // Reference to the image in use. For most runtimes, this should be an
    // image ID or digest.
    string image_ref = 1;
}
```

**Comment by huoqifeng** [comment]
@yoheiueda I think you're right, CCv0 does not support private image yet, comments what I got from @stevenhorsman in an internal ticket refers to https://github.com/kata-containers/kata-containers/issues/4601

**Comment by yoheiueda** [comment]
@huoqifeng Thank you for the info.

For now, we can edit the `policy.json` file to be embedded into a pod VM image to include registry credentials, and rebuild the pod VM image.

https://github.com/confidential-containers/cloud-api-adaptor/blob/b5ecb837f63dab71abf2b22d9f4cd729ea132271/ibmcloud/image/files/etc/containers/policy.json#L1-L3

The `policy.json` file is used by `skopeo`, and will probably be also used by image-rs.

https://github.com/confidential-containers/image-rs/blob/main/docs/ccv1_image_security_design.md#policy

@huoqifeng Is it OK for now to use this work around for your Istio work, or do we need to implement another option?

**Comment by huoqifeng** [comment]
@yoheiueda it's OK to workaround in istio, I can move ahead now. But policy.json might not be a perfect solution in production as the use case is that: The image pull credentials is added to the pod descriptor by istio admission controller dynamically, the source is secrets in k8s cluster. I think we'll need support the normal image pull credential similar as containerd/crio in IKS managed istio.

**Comment by yoheiueda** [comment]
@huoqifeng I agree. `imagePullSecrets` should also be supported for compatibility.

Implementing the support of `imagePullSecrets`  only in `cloud-api-adaptor` requires a lot of efforts. I think we should wait until the Kata side decides how to implement the feature.

**Comment by ariel-adam** [comment]
@huoqifeng is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
Closing this as we have support for authenticated registries now using auth.json file. For supporting additional approaches we can create new issues as relevant.
