### ISSUE TITLE
azure: leaking network interfaces on podvm creation failure

### ISSUE THREAD

**Issue by katexochen** [confidential-containers/cloud-api-adaptor#997]
When the podvm deployment fails, caa will repeatedly retry the deployment. Currently, network interfaces are leaking in this process.

![screenshot-20230523-185401](https://github.com/confidential-containers/cloud-api-adaptor/assets/49727155/d981fbd0-a0a5-47bd-93ca-bd8faf5e7920)

**Comment by bpradipt** [comment]
@snir911

**Comment by mkulke** [comment]
thanks for reporting, I also encountered this
